// Code generated by conjure-go. DO NOT EDIT.

package discovery

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/olehmushka/open-faith-map/internal/conjure/internal/conjureerrors"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/errors"
	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
	"github.com/palantir/pkg/uuid"
	werror "github.com/palantir/witchcraft-go-error"
)

type forbidden struct{}

func (o forbidden) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *forbidden) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// NewForbidden returns new instance of Forbidden error.
func NewForbidden() *Forbidden {
	return &Forbidden{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), forbidden: forbidden{}}
}

// WrapWithForbidden returns new instance of Forbidden error wrapping an existing error.
func WrapWithForbidden(err error) *Forbidden {
	return &Forbidden{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), cause: err, forbidden: forbidden{}}
}

// Forbidden is an error type.
// The caller does not hold the registration-operator's target-scoped grant on the root unit.
type Forbidden struct {
	errorInstanceID uuid.UUID
	forbidden
	cause error
	stack werror.StackTrace
}

// IsForbidden returns true if err is an instance of Forbidden.
func IsForbidden(err error) bool {
	if err == nil {
		return false
	}
	_, ok := errors.GetConjureError(err).(*Forbidden)
	return ok
}

func (e *Forbidden) Error() string {
	return fmt.Sprintf("PERMISSION_DENIED Discovery:Forbidden (%s)", e.errorInstanceID)
}

// Cause returns the underlying cause of the error, or nil if none.
// Note that cause is not serialized and sent over the wire.
func (e *Forbidden) Cause() error {
	return e.cause
}

// StackTrace returns the StackTrace for the error, or nil if none.
// Note that stack traces are not serialized and sent over the wire.
func (e *Forbidden) StackTrace() werror.StackTrace {
	return e.stack
}

// Message returns the message body for the error.
func (e *Forbidden) Message() string {
	return "PERMISSION_DENIED Discovery:Forbidden"
}

// Format implements fmt.Formatter, a requirement of werror.Werror.
func (e *Forbidden) Format(state fmt.State, verb rune) {
	werror.Format(e, e.safeParams(), state, verb)
}

// Code returns an enum describing error category.
func (e *Forbidden) Code() errors.ErrorCode {
	return errors.PermissionDenied
}

// Name returns an error name identifying error type.
func (e *Forbidden) Name() string {
	return "Discovery:Forbidden"
}

// InstanceID returns unique identifier of this particular error instance.
func (e *Forbidden) InstanceID() uuid.UUID {
	return e.errorInstanceID
}

// Parameters returns a set of named parameters detailing this particular error instance.
func (e *Forbidden) Parameters() map[string]interface{} {
	return map[string]interface{}{}
}

// safeParams returns a set of named safe parameters detailing this particular error instance.
func (e *Forbidden) safeParams() map[string]interface{} {
	return map[string]interface{}{"errorInstanceId": e.errorInstanceID, "errorName": e.Name()}
}

// SafeParams returns a set of named safe parameters detailing this particular error instance and
// any underlying causes.
func (e *Forbidden) SafeParams() map[string]interface{} {
	safeParams, _ := werror.ParamsFromError(e.cause)
	for k, v := range e.safeParams() {
		if _, exists := safeParams[k]; !exists {
			safeParams[k] = v
		}
	}
	return safeParams
}

// unsafeParams returns a set of named unsafe parameters detailing this particular error instance.
func (e *Forbidden) unsafeParams() map[string]interface{} {
	return map[string]interface{}{}
}

// UnsafeParams returns a set of named unsafe parameters detailing this particular error instance and
// any underlying causes.
func (e *Forbidden) UnsafeParams() map[string]interface{} {
	_, unsafeParams := werror.ParamsFromError(e.cause)
	for k, v := range e.unsafeParams() {
		if _, exists := unsafeParams[k]; !exists {
			unsafeParams[k] = v
		}
	}
	return unsafeParams
}

func (e Forbidden) MarshalJSON() ([]byte, error) {
	parameters, err := safejson.Marshal(e.forbidden)
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(errors.SerializableError{ErrorCode: errors.PermissionDenied, ErrorName: "Discovery:Forbidden", ErrorInstanceID: e.errorInstanceID, Parameters: json.RawMessage(parameters)})
}

func (e *Forbidden) UnmarshalJSON(data []byte) error {
	var serializableError errors.SerializableError
	if err := safejson.Unmarshal(data, &serializableError); err != nil {
		return err
	}
	var parameters forbidden
	if err := safejson.Unmarshal([]byte(serializableError.Parameters), &parameters); err != nil {
		return err
	}
	e.errorInstanceID = serializableError.ErrorInstanceID
	e.forbidden = parameters
	return nil
}

type siteNotFound struct{}

func (o siteNotFound) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *siteNotFound) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// NewSiteNotFound returns new instance of SiteNotFound error.
func NewSiteNotFound() *SiteNotFound {
	return &SiteNotFound{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), siteNotFound: siteNotFound{}}
}

// WrapWithSiteNotFound returns new instance of SiteNotFound error wrapping an existing error.
func WrapWithSiteNotFound(err error) *SiteNotFound {
	return &SiteNotFound{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), cause: err, siteNotFound: siteNotFound{}}
}

// SiteNotFound is an error type.
// The unit has no discoverable (public, non-hidden) site — either it has none at all, or its only site(s) are private/unlisted/hidden, which is deliberately indistinguishable to an anonymous caller.
type SiteNotFound struct {
	errorInstanceID uuid.UUID
	siteNotFound
	cause error
	stack werror.StackTrace
}

// IsSiteNotFound returns true if err is an instance of SiteNotFound.
func IsSiteNotFound(err error) bool {
	if err == nil {
		return false
	}
	_, ok := errors.GetConjureError(err).(*SiteNotFound)
	return ok
}

func (e *SiteNotFound) Error() string {
	return fmt.Sprintf("NOT_FOUND Discovery:SiteNotFound (%s)", e.errorInstanceID)
}

// Cause returns the underlying cause of the error, or nil if none.
// Note that cause is not serialized and sent over the wire.
func (e *SiteNotFound) Cause() error {
	return e.cause
}

// StackTrace returns the StackTrace for the error, or nil if none.
// Note that stack traces are not serialized and sent over the wire.
func (e *SiteNotFound) StackTrace() werror.StackTrace {
	return e.stack
}

// Message returns the message body for the error.
func (e *SiteNotFound) Message() string {
	return "NOT_FOUND Discovery:SiteNotFound"
}

// Format implements fmt.Formatter, a requirement of werror.Werror.
func (e *SiteNotFound) Format(state fmt.State, verb rune) {
	werror.Format(e, e.safeParams(), state, verb)
}

// Code returns an enum describing error category.
func (e *SiteNotFound) Code() errors.ErrorCode {
	return errors.NotFound
}

// Name returns an error name identifying error type.
func (e *SiteNotFound) Name() string {
	return "Discovery:SiteNotFound"
}

// InstanceID returns unique identifier of this particular error instance.
func (e *SiteNotFound) InstanceID() uuid.UUID {
	return e.errorInstanceID
}

// Parameters returns a set of named parameters detailing this particular error instance.
func (e *SiteNotFound) Parameters() map[string]interface{} {
	return map[string]interface{}{}
}

// safeParams returns a set of named safe parameters detailing this particular error instance.
func (e *SiteNotFound) safeParams() map[string]interface{} {
	return map[string]interface{}{"errorInstanceId": e.errorInstanceID, "errorName": e.Name()}
}

// SafeParams returns a set of named safe parameters detailing this particular error instance and
// any underlying causes.
func (e *SiteNotFound) SafeParams() map[string]interface{} {
	safeParams, _ := werror.ParamsFromError(e.cause)
	for k, v := range e.safeParams() {
		if _, exists := safeParams[k]; !exists {
			safeParams[k] = v
		}
	}
	return safeParams
}

// unsafeParams returns a set of named unsafe parameters detailing this particular error instance.
func (e *SiteNotFound) unsafeParams() map[string]interface{} {
	return map[string]interface{}{}
}

// UnsafeParams returns a set of named unsafe parameters detailing this particular error instance and
// any underlying causes.
func (e *SiteNotFound) UnsafeParams() map[string]interface{} {
	_, unsafeParams := werror.ParamsFromError(e.cause)
	for k, v := range e.unsafeParams() {
		if _, exists := unsafeParams[k]; !exists {
			unsafeParams[k] = v
		}
	}
	return unsafeParams
}

func (e SiteNotFound) MarshalJSON() ([]byte, error) {
	parameters, err := safejson.Marshal(e.siteNotFound)
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(errors.SerializableError{ErrorCode: errors.NotFound, ErrorName: "Discovery:SiteNotFound", ErrorInstanceID: e.errorInstanceID, Parameters: json.RawMessage(parameters)})
}

func (e *SiteNotFound) UnmarshalJSON(data []byte) error {
	var serializableError errors.SerializableError
	if err := safejson.Unmarshal(data, &serializableError); err != nil {
		return err
	}
	var parameters siteNotFound
	if err := safejson.Unmarshal([]byte(serializableError.Parameters), &parameters); err != nil {
		return err
	}
	e.errorInstanceID = serializableError.ErrorInstanceID
	e.siteNotFound = parameters
	return nil
}

func init() {
	conjureerrors.RegisterErrorType("Discovery:Forbidden", reflect.TypeOf(Forbidden{}))
	conjureerrors.RegisterErrorType("Discovery:SiteNotFound", reflect.TypeOf(SiteNotFound{}))
}
