// Code generated by conjure-go. DO NOT EDIT.

package discovery

import (
	"context"
	"fmt"
	"net/url"

	"github.com/olehmushka/open-faith-map/internal/conjure/internal/conjureerrors"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-client/httpclient"
	"github.com/palantir/pkg/bearertoken"
	werror "github.com/palantir/witchcraft-go-error"
)

// Anonymous public map/search (openfaithmap-web holds no session — D-AdminSurface). Never widens what internal/religion.SearchSites would already return publicly (the position-oracle fix: hidden sites excluded, others coordinate-snapped). See docs/modules/discovery.md.
type DiscoveryPublicServiceClient interface {
	Search(ctx context.Context, latArg *float64, lngArg *float64, radiusMArg *float64, traditionArg *string, languageArg *string, dayOfWeekArg *int, queryArg *string) (SearchResult, error)
}

type discoveryPublicServiceClient struct {
	client httpclient.Client
}

func NewDiscoveryPublicServiceClient(client httpclient.Client) DiscoveryPublicServiceClient {
	return &discoveryPublicServiceClient{client: client}
}

func (c *discoveryPublicServiceClient) Search(ctx context.Context, latArg *float64, lngArg *float64, radiusMArg *float64, traditionArg *string, languageArg *string, dayOfWeekArg *int, queryArg *string) (SearchResult, error) {
	var returnVal *SearchResult
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("Search"))
	requestParams = append(requestParams, httpclient.WithPathf("/discovery/v1/search"))
	queryParams := make(url.Values)
	if latArg != nil {
		queryParams.Set("lat", fmt.Sprint(*latArg))
	}
	if lngArg != nil {
		queryParams.Set("lng", fmt.Sprint(*lngArg))
	}
	if radiusMArg != nil {
		queryParams.Set("radiusM", fmt.Sprint(*radiusMArg))
	}
	if traditionArg != nil {
		queryParams.Set("tradition", fmt.Sprint(*traditionArg))
	}
	if languageArg != nil {
		queryParams.Set("language", fmt.Sprint(*languageArg))
	}
	if dayOfWeekArg != nil {
		queryParams.Set("dayOfWeek", fmt.Sprint(*dayOfWeekArg))
	}
	if queryArg != nil {
		queryParams.Set("query", fmt.Sprint(*queryArg))
	}
	requestParams = append(requestParams, httpclient.WithQueryValues(queryParams))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(SearchResult), werror.WrapWithContextParams(ctx, err, "search failed")
	}
	if returnVal == nil {
		return *new(SearchResult), werror.ErrorWithContextParams(ctx, "search response cannot be nil")
	}
	return *returnVal, nil
}

// Operator tooling only — forcing a manual cache rebuild for a region. Not part of the public product surface; the public map never calls this.
type DiscoveryServiceClient interface {
	Refresh(ctx context.Context, authHeader bearertoken.Token, requestArg RefreshRegionRequest) (RefreshResult, error)
}

type discoveryServiceClient struct {
	client httpclient.Client
}

func NewDiscoveryServiceClient(client httpclient.Client) DiscoveryServiceClient {
	return &discoveryServiceClient{client: client}
}

func (c *discoveryServiceClient) Refresh(ctx context.Context, authHeader bearertoken.Token, requestArg RefreshRegionRequest) (RefreshResult, error) {
	var returnVal *RefreshResult
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("Refresh"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/discovery/v1/refresh"))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(RefreshResult), werror.WrapWithContextParams(ctx, err, "refresh failed")
	}
	if returnVal == nil {
		return *new(RefreshResult), werror.ErrorWithContextParams(ctx, "refresh response cannot be nil")
	}
	return *returnVal, nil
}

// Operator tooling only — forcing a manual cache rebuild for a region. Not part of the public product surface; the public map never calls this.
type DiscoveryServiceClientWithAuth interface {
	Refresh(ctx context.Context, requestArg RefreshRegionRequest) (RefreshResult, error)
}

func NewDiscoveryServiceClientWithAuth(client DiscoveryServiceClient, authHeader bearertoken.Token) DiscoveryServiceClientWithAuth {
	return &discoveryServiceClientWithAuth{client: client, authHeader: authHeader}
}

type discoveryServiceClientWithAuth struct {
	client     DiscoveryServiceClient
	authHeader bearertoken.Token
}

func (c *discoveryServiceClientWithAuth) Refresh(ctx context.Context, requestArg RefreshRegionRequest) (RefreshResult, error) {
	return c.client.Refresh(ctx, c.authHeader, requestArg)
}

func NewDiscoveryServiceClientWithTokenProvider(client DiscoveryServiceClient, tokenProvider httpclient.TokenProvider) DiscoveryServiceClientWithAuth {
	return &discoveryServiceClientWithTokenProvider{client: client, tokenProvider: tokenProvider}
}

type discoveryServiceClientWithTokenProvider struct {
	client        DiscoveryServiceClient
	tokenProvider httpclient.TokenProvider
}

func (c *discoveryServiceClientWithTokenProvider) Refresh(ctx context.Context, requestArg RefreshRegionRequest) (RefreshResult, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(RefreshResult), err
	}
	return c.client.Refresh(ctx, bearertoken.Token(token), requestArg)
}
