// Code generated by conjure-go. DO NOT EDIT.

package core

import (
	"context"
	"fmt"
	"net/url"

	"github.com/olehmushka/open-faith-map/internal/conjure/internal/conjureerrors"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-client/httpclient"
	"github.com/palantir/pkg/bearertoken"
	werror "github.com/palantir/witchcraft-go-error"
)

// The admin app's session-gated reads over the in-process core (units, taxa, countries, org kinds/profiles, memberships, persons) plus its one gated write, createChildOrg. See file header for exactly which endpoints carry an authorization gate beyond the session itself.
type CoreServiceClient interface {
	Whoami(ctx context.Context, authHeader bearertoken.Token) (Whoami, error)
	GetUnit(ctx context.Context, authHeader bearertoken.Token, unitIdArg string) (Unit, error)
	// Free-text search over code/name, capped at limit (default/max 50).
	ListUnits(ctx context.Context, authHeader bearertoken.Token, queryArg *string, limitArg *int) (UnitPage, error)
	UnitAncestors(ctx context.Context, authHeader bearertoken.Token, unitIdArg string) (UnitRefPage, error)
	// Free-text search over code/name, capped at limit (default/max 50).
	ListTaxa(ctx context.Context, authHeader bearertoken.Token, queryArg *string, limitArg *int) (TaxonPage, error)
	GetTaxon(ctx context.Context, authHeader bearertoken.Token, taxonIdArg string) (Taxon, error)
	ListOrgKinds(ctx context.Context, authHeader bearertoken.Token) (OrgKindPage, error)
	GetOrgProfile(ctx context.Context, authHeader bearertoken.Token, unitIdArg string) (OrgProfile, error)
	// Gated — the caller must hold religionorg.manage over parentUnitId.
	CreateChildOrg(ctx context.Context, authHeader bearertoken.Token, requestArg CreateChildOrgRequest) (OrgProfile, error)
	ListCountries(ctx context.Context, authHeader bearertoken.Token) (CountryPage, error)
	ListMembershipsByUnit(ctx context.Context, authHeader bearertoken.Token, unitIdArg string) (MembershipPage, error)
	GetPerson(ctx context.Context, authHeader bearertoken.Token, personIdArg string) (Person, error)
	// Batched read — replaces the pre-cutover my-congregation page's per-member getPerson loop.
	GetPersons(ctx context.Context, authHeader bearertoken.Token, requestArg GetPersonsRequest) (PersonPage, error)
}

type coreServiceClient struct {
	client httpclient.Client
}

func NewCoreServiceClient(client httpclient.Client) CoreServiceClient {
	return &coreServiceClient{client: client}
}

func (c *coreServiceClient) Whoami(ctx context.Context, authHeader bearertoken.Token) (Whoami, error) {
	var returnVal *Whoami
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("Whoami"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/core/v1/whoami"))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(Whoami), werror.WrapWithContextParams(ctx, err, "whoami failed")
	}
	if returnVal == nil {
		return *new(Whoami), werror.ErrorWithContextParams(ctx, "whoami response cannot be nil")
	}
	return *returnVal, nil
}

func (c *coreServiceClient) GetUnit(ctx context.Context, authHeader bearertoken.Token, unitIdArg string) (Unit, error) {
	var returnVal *Unit
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("GetUnit"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/core/v1/units/%s", url.PathEscape(fmt.Sprint(unitIdArg))))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(Unit), werror.WrapWithContextParams(ctx, err, "getUnit failed")
	}
	if returnVal == nil {
		return *new(Unit), werror.ErrorWithContextParams(ctx, "getUnit response cannot be nil")
	}
	return *returnVal, nil
}

func (c *coreServiceClient) ListUnits(ctx context.Context, authHeader bearertoken.Token, queryArg *string, limitArg *int) (UnitPage, error) {
	var returnVal *UnitPage
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("ListUnits"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/core/v1/units"))
	queryParams := make(url.Values)
	if queryArg != nil {
		queryParams.Set("query", fmt.Sprint(*queryArg))
	}
	if limitArg != nil {
		queryParams.Set("limit", fmt.Sprint(*limitArg))
	}
	requestParams = append(requestParams, httpclient.WithQueryValues(queryParams))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(UnitPage), werror.WrapWithContextParams(ctx, err, "listUnits failed")
	}
	if returnVal == nil {
		return *new(UnitPage), werror.ErrorWithContextParams(ctx, "listUnits response cannot be nil")
	}
	return *returnVal, nil
}

func (c *coreServiceClient) UnitAncestors(ctx context.Context, authHeader bearertoken.Token, unitIdArg string) (UnitRefPage, error) {
	var returnVal *UnitRefPage
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("UnitAncestors"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/core/v1/units/%s/ancestors", url.PathEscape(fmt.Sprint(unitIdArg))))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(UnitRefPage), werror.WrapWithContextParams(ctx, err, "unitAncestors failed")
	}
	if returnVal == nil {
		return *new(UnitRefPage), werror.ErrorWithContextParams(ctx, "unitAncestors response cannot be nil")
	}
	return *returnVal, nil
}

func (c *coreServiceClient) ListTaxa(ctx context.Context, authHeader bearertoken.Token, queryArg *string, limitArg *int) (TaxonPage, error) {
	var returnVal *TaxonPage
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("ListTaxa"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/core/v1/taxa"))
	queryParams := make(url.Values)
	if queryArg != nil {
		queryParams.Set("query", fmt.Sprint(*queryArg))
	}
	if limitArg != nil {
		queryParams.Set("limit", fmt.Sprint(*limitArg))
	}
	requestParams = append(requestParams, httpclient.WithQueryValues(queryParams))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(TaxonPage), werror.WrapWithContextParams(ctx, err, "listTaxa failed")
	}
	if returnVal == nil {
		return *new(TaxonPage), werror.ErrorWithContextParams(ctx, "listTaxa response cannot be nil")
	}
	return *returnVal, nil
}

func (c *coreServiceClient) GetTaxon(ctx context.Context, authHeader bearertoken.Token, taxonIdArg string) (Taxon, error) {
	var returnVal *Taxon
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("GetTaxon"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/core/v1/taxa/%s", url.PathEscape(fmt.Sprint(taxonIdArg))))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(Taxon), werror.WrapWithContextParams(ctx, err, "getTaxon failed")
	}
	if returnVal == nil {
		return *new(Taxon), werror.ErrorWithContextParams(ctx, "getTaxon response cannot be nil")
	}
	return *returnVal, nil
}

func (c *coreServiceClient) ListOrgKinds(ctx context.Context, authHeader bearertoken.Token) (OrgKindPage, error) {
	var returnVal *OrgKindPage
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("ListOrgKinds"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/core/v1/org-kinds"))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(OrgKindPage), werror.WrapWithContextParams(ctx, err, "listOrgKinds failed")
	}
	if returnVal == nil {
		return *new(OrgKindPage), werror.ErrorWithContextParams(ctx, "listOrgKinds response cannot be nil")
	}
	return *returnVal, nil
}

func (c *coreServiceClient) GetOrgProfile(ctx context.Context, authHeader bearertoken.Token, unitIdArg string) (OrgProfile, error) {
	var returnVal *OrgProfile
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("GetOrgProfile"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/core/v1/units/%s/org-profile", url.PathEscape(fmt.Sprint(unitIdArg))))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(OrgProfile), werror.WrapWithContextParams(ctx, err, "getOrgProfile failed")
	}
	if returnVal == nil {
		return *new(OrgProfile), werror.ErrorWithContextParams(ctx, "getOrgProfile response cannot be nil")
	}
	return *returnVal, nil
}

func (c *coreServiceClient) CreateChildOrg(ctx context.Context, authHeader bearertoken.Token, requestArg CreateChildOrgRequest) (OrgProfile, error) {
	var returnVal *OrgProfile
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("CreateChildOrg"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/core/v1/units/children"))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(OrgProfile), werror.WrapWithContextParams(ctx, err, "createChildOrg failed")
	}
	if returnVal == nil {
		return *new(OrgProfile), werror.ErrorWithContextParams(ctx, "createChildOrg response cannot be nil")
	}
	return *returnVal, nil
}

func (c *coreServiceClient) ListCountries(ctx context.Context, authHeader bearertoken.Token) (CountryPage, error) {
	var returnVal *CountryPage
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("ListCountries"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/core/v1/countries"))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(CountryPage), werror.WrapWithContextParams(ctx, err, "listCountries failed")
	}
	if returnVal == nil {
		return *new(CountryPage), werror.ErrorWithContextParams(ctx, "listCountries response cannot be nil")
	}
	return *returnVal, nil
}

func (c *coreServiceClient) ListMembershipsByUnit(ctx context.Context, authHeader bearertoken.Token, unitIdArg string) (MembershipPage, error) {
	var returnVal *MembershipPage
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("ListMembershipsByUnit"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/core/v1/units/%s/memberships", url.PathEscape(fmt.Sprint(unitIdArg))))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(MembershipPage), werror.WrapWithContextParams(ctx, err, "listMembershipsByUnit failed")
	}
	if returnVal == nil {
		return *new(MembershipPage), werror.ErrorWithContextParams(ctx, "listMembershipsByUnit response cannot be nil")
	}
	return *returnVal, nil
}

func (c *coreServiceClient) GetPerson(ctx context.Context, authHeader bearertoken.Token, personIdArg string) (Person, error) {
	var returnVal *Person
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("GetPerson"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/core/v1/persons/%s", url.PathEscape(fmt.Sprint(personIdArg))))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(Person), werror.WrapWithContextParams(ctx, err, "getPerson failed")
	}
	if returnVal == nil {
		return *new(Person), werror.ErrorWithContextParams(ctx, "getPerson response cannot be nil")
	}
	return *returnVal, nil
}

func (c *coreServiceClient) GetPersons(ctx context.Context, authHeader bearertoken.Token, requestArg GetPersonsRequest) (PersonPage, error) {
	var returnVal *PersonPage
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("GetPersons"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/core/v1/persons/batch-get"))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(PersonPage), werror.WrapWithContextParams(ctx, err, "getPersons failed")
	}
	if returnVal == nil {
		return *new(PersonPage), werror.ErrorWithContextParams(ctx, "getPersons response cannot be nil")
	}
	return *returnVal, nil
}

// The admin app's session-gated reads over the in-process core (units, taxa, countries, org kinds/profiles, memberships, persons) plus its one gated write, createChildOrg. See file header for exactly which endpoints carry an authorization gate beyond the session itself.
type CoreServiceClientWithAuth interface {
	Whoami(ctx context.Context) (Whoami, error)
	GetUnit(ctx context.Context, unitIdArg string) (Unit, error)
	// Free-text search over code/name, capped at limit (default/max 50).
	ListUnits(ctx context.Context, queryArg *string, limitArg *int) (UnitPage, error)
	UnitAncestors(ctx context.Context, unitIdArg string) (UnitRefPage, error)
	// Free-text search over code/name, capped at limit (default/max 50).
	ListTaxa(ctx context.Context, queryArg *string, limitArg *int) (TaxonPage, error)
	GetTaxon(ctx context.Context, taxonIdArg string) (Taxon, error)
	ListOrgKinds(ctx context.Context) (OrgKindPage, error)
	GetOrgProfile(ctx context.Context, unitIdArg string) (OrgProfile, error)
	// Gated — the caller must hold religionorg.manage over parentUnitId.
	CreateChildOrg(ctx context.Context, requestArg CreateChildOrgRequest) (OrgProfile, error)
	ListCountries(ctx context.Context) (CountryPage, error)
	ListMembershipsByUnit(ctx context.Context, unitIdArg string) (MembershipPage, error)
	GetPerson(ctx context.Context, personIdArg string) (Person, error)
	// Batched read — replaces the pre-cutover my-congregation page's per-member getPerson loop.
	GetPersons(ctx context.Context, requestArg GetPersonsRequest) (PersonPage, error)
}

func NewCoreServiceClientWithAuth(client CoreServiceClient, authHeader bearertoken.Token) CoreServiceClientWithAuth {
	return &coreServiceClientWithAuth{client: client, authHeader: authHeader}
}

type coreServiceClientWithAuth struct {
	client     CoreServiceClient
	authHeader bearertoken.Token
}

func (c *coreServiceClientWithAuth) Whoami(ctx context.Context) (Whoami, error) {
	return c.client.Whoami(ctx, c.authHeader)
}

func (c *coreServiceClientWithAuth) GetUnit(ctx context.Context, unitIdArg string) (Unit, error) {
	return c.client.GetUnit(ctx, c.authHeader, unitIdArg)
}

func (c *coreServiceClientWithAuth) ListUnits(ctx context.Context, queryArg *string, limitArg *int) (UnitPage, error) {
	return c.client.ListUnits(ctx, c.authHeader, queryArg, limitArg)
}

func (c *coreServiceClientWithAuth) UnitAncestors(ctx context.Context, unitIdArg string) (UnitRefPage, error) {
	return c.client.UnitAncestors(ctx, c.authHeader, unitIdArg)
}

func (c *coreServiceClientWithAuth) ListTaxa(ctx context.Context, queryArg *string, limitArg *int) (TaxonPage, error) {
	return c.client.ListTaxa(ctx, c.authHeader, queryArg, limitArg)
}

func (c *coreServiceClientWithAuth) GetTaxon(ctx context.Context, taxonIdArg string) (Taxon, error) {
	return c.client.GetTaxon(ctx, c.authHeader, taxonIdArg)
}

func (c *coreServiceClientWithAuth) ListOrgKinds(ctx context.Context) (OrgKindPage, error) {
	return c.client.ListOrgKinds(ctx, c.authHeader)
}

func (c *coreServiceClientWithAuth) GetOrgProfile(ctx context.Context, unitIdArg string) (OrgProfile, error) {
	return c.client.GetOrgProfile(ctx, c.authHeader, unitIdArg)
}

func (c *coreServiceClientWithAuth) CreateChildOrg(ctx context.Context, requestArg CreateChildOrgRequest) (OrgProfile, error) {
	return c.client.CreateChildOrg(ctx, c.authHeader, requestArg)
}

func (c *coreServiceClientWithAuth) ListCountries(ctx context.Context) (CountryPage, error) {
	return c.client.ListCountries(ctx, c.authHeader)
}

func (c *coreServiceClientWithAuth) ListMembershipsByUnit(ctx context.Context, unitIdArg string) (MembershipPage, error) {
	return c.client.ListMembershipsByUnit(ctx, c.authHeader, unitIdArg)
}

func (c *coreServiceClientWithAuth) GetPerson(ctx context.Context, personIdArg string) (Person, error) {
	return c.client.GetPerson(ctx, c.authHeader, personIdArg)
}

func (c *coreServiceClientWithAuth) GetPersons(ctx context.Context, requestArg GetPersonsRequest) (PersonPage, error) {
	return c.client.GetPersons(ctx, c.authHeader, requestArg)
}

func NewCoreServiceClientWithTokenProvider(client CoreServiceClient, tokenProvider httpclient.TokenProvider) CoreServiceClientWithAuth {
	return &coreServiceClientWithTokenProvider{client: client, tokenProvider: tokenProvider}
}

type coreServiceClientWithTokenProvider struct {
	client        CoreServiceClient
	tokenProvider httpclient.TokenProvider
}

func (c *coreServiceClientWithTokenProvider) Whoami(ctx context.Context) (Whoami, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(Whoami), err
	}
	return c.client.Whoami(ctx, bearertoken.Token(token))
}

func (c *coreServiceClientWithTokenProvider) GetUnit(ctx context.Context, unitIdArg string) (Unit, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(Unit), err
	}
	return c.client.GetUnit(ctx, bearertoken.Token(token), unitIdArg)
}

func (c *coreServiceClientWithTokenProvider) ListUnits(ctx context.Context, queryArg *string, limitArg *int) (UnitPage, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(UnitPage), err
	}
	return c.client.ListUnits(ctx, bearertoken.Token(token), queryArg, limitArg)
}

func (c *coreServiceClientWithTokenProvider) UnitAncestors(ctx context.Context, unitIdArg string) (UnitRefPage, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(UnitRefPage), err
	}
	return c.client.UnitAncestors(ctx, bearertoken.Token(token), unitIdArg)
}

func (c *coreServiceClientWithTokenProvider) ListTaxa(ctx context.Context, queryArg *string, limitArg *int) (TaxonPage, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(TaxonPage), err
	}
	return c.client.ListTaxa(ctx, bearertoken.Token(token), queryArg, limitArg)
}

func (c *coreServiceClientWithTokenProvider) GetTaxon(ctx context.Context, taxonIdArg string) (Taxon, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(Taxon), err
	}
	return c.client.GetTaxon(ctx, bearertoken.Token(token), taxonIdArg)
}

func (c *coreServiceClientWithTokenProvider) ListOrgKinds(ctx context.Context) (OrgKindPage, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(OrgKindPage), err
	}
	return c.client.ListOrgKinds(ctx, bearertoken.Token(token))
}

func (c *coreServiceClientWithTokenProvider) GetOrgProfile(ctx context.Context, unitIdArg string) (OrgProfile, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(OrgProfile), err
	}
	return c.client.GetOrgProfile(ctx, bearertoken.Token(token), unitIdArg)
}

func (c *coreServiceClientWithTokenProvider) CreateChildOrg(ctx context.Context, requestArg CreateChildOrgRequest) (OrgProfile, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(OrgProfile), err
	}
	return c.client.CreateChildOrg(ctx, bearertoken.Token(token), requestArg)
}

func (c *coreServiceClientWithTokenProvider) ListCountries(ctx context.Context) (CountryPage, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(CountryPage), err
	}
	return c.client.ListCountries(ctx, bearertoken.Token(token))
}

func (c *coreServiceClientWithTokenProvider) ListMembershipsByUnit(ctx context.Context, unitIdArg string) (MembershipPage, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(MembershipPage), err
	}
	return c.client.ListMembershipsByUnit(ctx, bearertoken.Token(token), unitIdArg)
}

func (c *coreServiceClientWithTokenProvider) GetPerson(ctx context.Context, personIdArg string) (Person, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(Person), err
	}
	return c.client.GetPerson(ctx, bearertoken.Token(token), personIdArg)
}

func (c *coreServiceClientWithTokenProvider) GetPersons(ctx context.Context, requestArg GetPersonsRequest) (PersonPage, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(PersonPage), err
	}
	return c.client.GetPersons(ctx, bearertoken.Token(token), requestArg)
}

// The super-admin surface replacing the deleted oikumenea-console (D-SuperAdminFold): people search, role catalog, per-unit role-assignment grant/list/revoke, and the instance-admin plane's own grant/list/revoke. Every endpoint in this service is gated as a whole route group by internal/authz/transport.RequireInstanceAdmin, attached once at registration (cmd/openfaithmap-api/register_core.go) — not per-handler, so no future endpoint added here can be added without inheriting the check.
type CoreSuperAdminServiceClient interface {
	SearchPersons(ctx context.Context, authHeader bearertoken.Token, queryArg *string, limitArg *int) (PersonPage, error)
	ListRoles(ctx context.Context, authHeader bearertoken.Token) (RolePage, error)
	ListRoleAssignmentsByUnit(ctx context.Context, authHeader bearertoken.Token, unitIdArg string) (RoleAssignmentPage, error)
	GrantUnitRole(ctx context.Context, authHeader bearertoken.Token, requestArg GrantUnitRoleRequest) error
	RevokeRoleAssignment(ctx context.Context, authHeader bearertoken.Token, assignmentIdArg string) error
	ListInstanceAdmins(ctx context.Context, authHeader bearertoken.Token) (InstanceAdminPage, error)
	GrantInstanceAdmin(ctx context.Context, authHeader bearertoken.Token, requestArg GrantInstanceAdminRequest) (InstanceAdminGrant, error)
	RevokeInstanceAdmin(ctx context.Context, authHeader bearertoken.Token, personIdArg string) error
}

type coreSuperAdminServiceClient struct {
	client httpclient.Client
}

func NewCoreSuperAdminServiceClient(client httpclient.Client) CoreSuperAdminServiceClient {
	return &coreSuperAdminServiceClient{client: client}
}

func (c *coreSuperAdminServiceClient) SearchPersons(ctx context.Context, authHeader bearertoken.Token, queryArg *string, limitArg *int) (PersonPage, error) {
	var returnVal *PersonPage
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("SearchPersons"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/core/v1/super-admin/persons"))
	queryParams := make(url.Values)
	if queryArg != nil {
		queryParams.Set("query", fmt.Sprint(*queryArg))
	}
	if limitArg != nil {
		queryParams.Set("limit", fmt.Sprint(*limitArg))
	}
	requestParams = append(requestParams, httpclient.WithQueryValues(queryParams))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(PersonPage), werror.WrapWithContextParams(ctx, err, "searchPersons failed")
	}
	if returnVal == nil {
		return *new(PersonPage), werror.ErrorWithContextParams(ctx, "searchPersons response cannot be nil")
	}
	return *returnVal, nil
}

func (c *coreSuperAdminServiceClient) ListRoles(ctx context.Context, authHeader bearertoken.Token) (RolePage, error) {
	var returnVal *RolePage
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("ListRoles"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/core/v1/super-admin/roles"))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(RolePage), werror.WrapWithContextParams(ctx, err, "listRoles failed")
	}
	if returnVal == nil {
		return *new(RolePage), werror.ErrorWithContextParams(ctx, "listRoles response cannot be nil")
	}
	return *returnVal, nil
}

func (c *coreSuperAdminServiceClient) ListRoleAssignmentsByUnit(ctx context.Context, authHeader bearertoken.Token, unitIdArg string) (RoleAssignmentPage, error) {
	var returnVal *RoleAssignmentPage
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("ListRoleAssignmentsByUnit"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/core/v1/super-admin/units/%s/role-assignments", url.PathEscape(fmt.Sprint(unitIdArg))))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(RoleAssignmentPage), werror.WrapWithContextParams(ctx, err, "listRoleAssignmentsByUnit failed")
	}
	if returnVal == nil {
		return *new(RoleAssignmentPage), werror.ErrorWithContextParams(ctx, "listRoleAssignmentsByUnit response cannot be nil")
	}
	return *returnVal, nil
}

func (c *coreSuperAdminServiceClient) GrantUnitRole(ctx context.Context, authHeader bearertoken.Token, requestArg GrantUnitRoleRequest) error {
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("GrantUnitRole"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/core/v1/super-admin/role-assignments"))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return werror.WrapWithContextParams(ctx, err, "grantUnitRole failed")
	}
	return nil
}

func (c *coreSuperAdminServiceClient) RevokeRoleAssignment(ctx context.Context, authHeader bearertoken.Token, assignmentIdArg string) error {
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("RevokeRoleAssignment"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/core/v1/super-admin/role-assignments/%s", url.PathEscape(fmt.Sprint(assignmentIdArg))))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Delete(ctx, requestParams...); err != nil {
		return werror.WrapWithContextParams(ctx, err, "revokeRoleAssignment failed")
	}
	return nil
}

func (c *coreSuperAdminServiceClient) ListInstanceAdmins(ctx context.Context, authHeader bearertoken.Token) (InstanceAdminPage, error) {
	var returnVal *InstanceAdminPage
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("ListInstanceAdmins"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/core/v1/super-admin/instance-admins"))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(InstanceAdminPage), werror.WrapWithContextParams(ctx, err, "listInstanceAdmins failed")
	}
	if returnVal == nil {
		return *new(InstanceAdminPage), werror.ErrorWithContextParams(ctx, "listInstanceAdmins response cannot be nil")
	}
	return *returnVal, nil
}

func (c *coreSuperAdminServiceClient) GrantInstanceAdmin(ctx context.Context, authHeader bearertoken.Token, requestArg GrantInstanceAdminRequest) (InstanceAdminGrant, error) {
	var returnVal *InstanceAdminGrant
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("GrantInstanceAdmin"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/core/v1/super-admin/instance-admins"))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(InstanceAdminGrant), werror.WrapWithContextParams(ctx, err, "grantInstanceAdmin failed")
	}
	if returnVal == nil {
		return *new(InstanceAdminGrant), werror.ErrorWithContextParams(ctx, "grantInstanceAdmin response cannot be nil")
	}
	return *returnVal, nil
}

func (c *coreSuperAdminServiceClient) RevokeInstanceAdmin(ctx context.Context, authHeader bearertoken.Token, personIdArg string) error {
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("RevokeInstanceAdmin"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/core/v1/super-admin/instance-admins/%s", url.PathEscape(fmt.Sprint(personIdArg))))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Delete(ctx, requestParams...); err != nil {
		return werror.WrapWithContextParams(ctx, err, "revokeInstanceAdmin failed")
	}
	return nil
}

// The super-admin surface replacing the deleted oikumenea-console (D-SuperAdminFold): people search, role catalog, per-unit role-assignment grant/list/revoke, and the instance-admin plane's own grant/list/revoke. Every endpoint in this service is gated as a whole route group by internal/authz/transport.RequireInstanceAdmin, attached once at registration (cmd/openfaithmap-api/register_core.go) — not per-handler, so no future endpoint added here can be added without inheriting the check.
type CoreSuperAdminServiceClientWithAuth interface {
	SearchPersons(ctx context.Context, queryArg *string, limitArg *int) (PersonPage, error)
	ListRoles(ctx context.Context) (RolePage, error)
	ListRoleAssignmentsByUnit(ctx context.Context, unitIdArg string) (RoleAssignmentPage, error)
	GrantUnitRole(ctx context.Context, requestArg GrantUnitRoleRequest) error
	RevokeRoleAssignment(ctx context.Context, assignmentIdArg string) error
	ListInstanceAdmins(ctx context.Context) (InstanceAdminPage, error)
	GrantInstanceAdmin(ctx context.Context, requestArg GrantInstanceAdminRequest) (InstanceAdminGrant, error)
	RevokeInstanceAdmin(ctx context.Context, personIdArg string) error
}

func NewCoreSuperAdminServiceClientWithAuth(client CoreSuperAdminServiceClient, authHeader bearertoken.Token) CoreSuperAdminServiceClientWithAuth {
	return &coreSuperAdminServiceClientWithAuth{client: client, authHeader: authHeader}
}

type coreSuperAdminServiceClientWithAuth struct {
	client     CoreSuperAdminServiceClient
	authHeader bearertoken.Token
}

func (c *coreSuperAdminServiceClientWithAuth) SearchPersons(ctx context.Context, queryArg *string, limitArg *int) (PersonPage, error) {
	return c.client.SearchPersons(ctx, c.authHeader, queryArg, limitArg)
}

func (c *coreSuperAdminServiceClientWithAuth) ListRoles(ctx context.Context) (RolePage, error) {
	return c.client.ListRoles(ctx, c.authHeader)
}

func (c *coreSuperAdminServiceClientWithAuth) ListRoleAssignmentsByUnit(ctx context.Context, unitIdArg string) (RoleAssignmentPage, error) {
	return c.client.ListRoleAssignmentsByUnit(ctx, c.authHeader, unitIdArg)
}

func (c *coreSuperAdminServiceClientWithAuth) GrantUnitRole(ctx context.Context, requestArg GrantUnitRoleRequest) error {
	return c.client.GrantUnitRole(ctx, c.authHeader, requestArg)
}

func (c *coreSuperAdminServiceClientWithAuth) RevokeRoleAssignment(ctx context.Context, assignmentIdArg string) error {
	return c.client.RevokeRoleAssignment(ctx, c.authHeader, assignmentIdArg)
}

func (c *coreSuperAdminServiceClientWithAuth) ListInstanceAdmins(ctx context.Context) (InstanceAdminPage, error) {
	return c.client.ListInstanceAdmins(ctx, c.authHeader)
}

func (c *coreSuperAdminServiceClientWithAuth) GrantInstanceAdmin(ctx context.Context, requestArg GrantInstanceAdminRequest) (InstanceAdminGrant, error) {
	return c.client.GrantInstanceAdmin(ctx, c.authHeader, requestArg)
}

func (c *coreSuperAdminServiceClientWithAuth) RevokeInstanceAdmin(ctx context.Context, personIdArg string) error {
	return c.client.RevokeInstanceAdmin(ctx, c.authHeader, personIdArg)
}

func NewCoreSuperAdminServiceClientWithTokenProvider(client CoreSuperAdminServiceClient, tokenProvider httpclient.TokenProvider) CoreSuperAdminServiceClientWithAuth {
	return &coreSuperAdminServiceClientWithTokenProvider{client: client, tokenProvider: tokenProvider}
}

type coreSuperAdminServiceClientWithTokenProvider struct {
	client        CoreSuperAdminServiceClient
	tokenProvider httpclient.TokenProvider
}

func (c *coreSuperAdminServiceClientWithTokenProvider) SearchPersons(ctx context.Context, queryArg *string, limitArg *int) (PersonPage, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(PersonPage), err
	}
	return c.client.SearchPersons(ctx, bearertoken.Token(token), queryArg, limitArg)
}

func (c *coreSuperAdminServiceClientWithTokenProvider) ListRoles(ctx context.Context) (RolePage, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(RolePage), err
	}
	return c.client.ListRoles(ctx, bearertoken.Token(token))
}

func (c *coreSuperAdminServiceClientWithTokenProvider) ListRoleAssignmentsByUnit(ctx context.Context, unitIdArg string) (RoleAssignmentPage, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(RoleAssignmentPage), err
	}
	return c.client.ListRoleAssignmentsByUnit(ctx, bearertoken.Token(token), unitIdArg)
}

func (c *coreSuperAdminServiceClientWithTokenProvider) GrantUnitRole(ctx context.Context, requestArg GrantUnitRoleRequest) error {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return err
	}
	return c.client.GrantUnitRole(ctx, bearertoken.Token(token), requestArg)
}

func (c *coreSuperAdminServiceClientWithTokenProvider) RevokeRoleAssignment(ctx context.Context, assignmentIdArg string) error {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return err
	}
	return c.client.RevokeRoleAssignment(ctx, bearertoken.Token(token), assignmentIdArg)
}

func (c *coreSuperAdminServiceClientWithTokenProvider) ListInstanceAdmins(ctx context.Context) (InstanceAdminPage, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(InstanceAdminPage), err
	}
	return c.client.ListInstanceAdmins(ctx, bearertoken.Token(token))
}

func (c *coreSuperAdminServiceClientWithTokenProvider) GrantInstanceAdmin(ctx context.Context, requestArg GrantInstanceAdminRequest) (InstanceAdminGrant, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(InstanceAdminGrant), err
	}
	return c.client.GrantInstanceAdmin(ctx, bearertoken.Token(token), requestArg)
}

func (c *coreSuperAdminServiceClientWithTokenProvider) RevokeInstanceAdmin(ctx context.Context, personIdArg string) error {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return err
	}
	return c.client.RevokeInstanceAdmin(ctx, bearertoken.Token(token), personIdArg)
}
