// Code generated by conjure-go. DO NOT EDIT.

package core

import (
	"context"
	"net/http"
	"strconv"

	"github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/codecs"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/errors"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-server/httpserver"
	"github.com/palantir/pkg/bearertoken"
	werror "github.com/palantir/witchcraft-go-error"
	"github.com/palantir/witchcraft-go-server/v2/witchcraft/wresource"
	"github.com/palantir/witchcraft-go-server/v2/wrouter"
)

// The admin app's session-gated reads over the in-process core (units, taxa, countries, org kinds/profiles, memberships, persons) plus its one gated write, createChildOrg. See file header for exactly which endpoints carry an authorization gate beyond the session itself.
type CoreService interface {
	Whoami(ctx context.Context, authHeader bearertoken.Token) (Whoami, error)
	GetUnit(ctx context.Context, authHeader bearertoken.Token, unitIdArg string) (Unit, error)
	// Free-text search over code/name, capped at limit (default/max 50).
	ListUnits(ctx context.Context, authHeader bearertoken.Token, queryArg *string, limitArg *int) (UnitPage, error)
	UnitAncestors(ctx context.Context, authHeader bearertoken.Token, unitIdArg string) (UnitRefPage, error)
	// Free-text search over code/name, capped at limit (default/max 50).
	ListTaxa(ctx context.Context, authHeader bearertoken.Token, queryArg *string, limitArg *int) (TaxonPage, error)
	GetTaxon(ctx context.Context, authHeader bearertoken.Token, taxonIdArg string) (Taxon, error)
	ListOrgKinds(ctx context.Context, authHeader bearertoken.Token) (OrgKindPage, error)
	GetOrgProfile(ctx context.Context, authHeader bearertoken.Token, unitIdArg string) (OrgProfile, error)
	// Gated — the caller must hold religionorg.manage over parentUnitId.
	CreateChildOrg(ctx context.Context, authHeader bearertoken.Token, requestArg CreateChildOrgRequest) (OrgProfile, error)
	ListCountries(ctx context.Context, authHeader bearertoken.Token) (CountryPage, error)
	ListMembershipsByUnit(ctx context.Context, authHeader bearertoken.Token, unitIdArg string) (MembershipPage, error)
	GetPerson(ctx context.Context, authHeader bearertoken.Token, personIdArg string) (Person, error)
	// Batched read — replaces the pre-cutover my-congregation page's per-member getPerson loop.
	GetPersons(ctx context.Context, authHeader bearertoken.Token, requestArg GetPersonsRequest) (PersonPage, error)
}

// RegisterRoutesCoreService registers handlers for the CoreService endpoints with a witchcraft wrouter.
// This should typically be called in a witchcraft server's InitFunc.
// impl provides an implementation of each endpoint, which can assume the request parameters have been parsed
// in accordance with the Conjure specification.
func RegisterRoutesCoreService(router wrouter.Router, impl CoreService, routerParams ...wrouter.RouteParam) error {
	handler := coreServiceHandler{impl: impl}
	resource := wresource.New("coreservice", router)
	if err := resource.Get("Whoami", "/core/v1/whoami", httpserver.NewJSONHandler(handler.HandleWhoami, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add whoami route")
	}
	if err := resource.Get("GetUnit", "/core/v1/units/{unitId}", httpserver.NewJSONHandler(handler.HandleGetUnit, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getUnit route")
	}
	if err := resource.Get("ListUnits", "/core/v1/units", httpserver.NewJSONHandler(handler.HandleListUnits, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listUnits route")
	}
	if err := resource.Get("UnitAncestors", "/core/v1/units/{unitId}/ancestors", httpserver.NewJSONHandler(handler.HandleUnitAncestors, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add unitAncestors route")
	}
	if err := resource.Get("ListTaxa", "/core/v1/taxa", httpserver.NewJSONHandler(handler.HandleListTaxa, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listTaxa route")
	}
	if err := resource.Get("GetTaxon", "/core/v1/taxa/{taxonId}", httpserver.NewJSONHandler(handler.HandleGetTaxon, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getTaxon route")
	}
	if err := resource.Get("ListOrgKinds", "/core/v1/org-kinds", httpserver.NewJSONHandler(handler.HandleListOrgKinds, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listOrgKinds route")
	}
	if err := resource.Get("GetOrgProfile", "/core/v1/units/{unitId}/org-profile", httpserver.NewJSONHandler(handler.HandleGetOrgProfile, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getOrgProfile route")
	}
	if err := resource.Post("CreateChildOrg", "/core/v1/units/children", httpserver.NewJSONHandler(handler.HandleCreateChildOrg, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add createChildOrg route")
	}
	if err := resource.Get("ListCountries", "/core/v1/countries", httpserver.NewJSONHandler(handler.HandleListCountries, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listCountries route")
	}
	if err := resource.Get("ListMembershipsByUnit", "/core/v1/units/{unitId}/memberships", httpserver.NewJSONHandler(handler.HandleListMembershipsByUnit, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listMembershipsByUnit route")
	}
	if err := resource.Get("GetPerson", "/core/v1/persons/{personId}", httpserver.NewJSONHandler(handler.HandleGetPerson, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getPerson route")
	}
	if err := resource.Post("GetPersons", "/core/v1/persons/batch-get", httpserver.NewJSONHandler(handler.HandleGetPersons, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getPersons route")
	}
	return nil
}

type coreServiceHandler struct {
	impl CoreService
}

func (c *coreServiceHandler) HandleWhoami(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	respArg, err := c.impl.Whoami(req.Context(), bearertoken.Token(authHeader))
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *coreServiceHandler) HandleGetUnit(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	respArg, err := c.impl.GetUnit(req.Context(), bearertoken.Token(authHeader), unitIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *coreServiceHandler) HandleListUnits(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var queryArg *string
	if queryArgStr := req.URL.Query().Get("query"); queryArgStr != "" {
		queryArgInternal := queryArgStr
		queryArg = &queryArgInternal
	}
	var limitArg *int
	if limitArgStr := req.URL.Query().Get("limit"); limitArgStr != "" {
		limitArgInternal, err := strconv.Atoi(limitArgStr)
		if err != nil {
			return werror.WrapWithContextParams(req.Context(), errors.WrapWithInvalidArgument(err), "failed to parse \"limit\" as integer")
		}
		limitArg = &limitArgInternal
	}
	respArg, err := c.impl.ListUnits(req.Context(), bearertoken.Token(authHeader), queryArg, limitArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *coreServiceHandler) HandleUnitAncestors(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	respArg, err := c.impl.UnitAncestors(req.Context(), bearertoken.Token(authHeader), unitIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *coreServiceHandler) HandleListTaxa(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var queryArg *string
	if queryArgStr := req.URL.Query().Get("query"); queryArgStr != "" {
		queryArgInternal := queryArgStr
		queryArg = &queryArgInternal
	}
	var limitArg *int
	if limitArgStr := req.URL.Query().Get("limit"); limitArgStr != "" {
		limitArgInternal, err := strconv.Atoi(limitArgStr)
		if err != nil {
			return werror.WrapWithContextParams(req.Context(), errors.WrapWithInvalidArgument(err), "failed to parse \"limit\" as integer")
		}
		limitArg = &limitArgInternal
	}
	respArg, err := c.impl.ListTaxa(req.Context(), bearertoken.Token(authHeader), queryArg, limitArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *coreServiceHandler) HandleGetTaxon(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	taxonIdArg, ok := pathParams["taxonId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"taxonId\" not present")
	}
	respArg, err := c.impl.GetTaxon(req.Context(), bearertoken.Token(authHeader), taxonIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *coreServiceHandler) HandleListOrgKinds(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	respArg, err := c.impl.ListOrgKinds(req.Context(), bearertoken.Token(authHeader))
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *coreServiceHandler) HandleGetOrgProfile(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	respArg, err := c.impl.GetOrgProfile(req.Context(), bearertoken.Token(authHeader), unitIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *coreServiceHandler) HandleCreateChildOrg(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg CreateChildOrgRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := c.impl.CreateChildOrg(req.Context(), bearertoken.Token(authHeader), requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *coreServiceHandler) HandleListCountries(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	respArg, err := c.impl.ListCountries(req.Context(), bearertoken.Token(authHeader))
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *coreServiceHandler) HandleListMembershipsByUnit(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	respArg, err := c.impl.ListMembershipsByUnit(req.Context(), bearertoken.Token(authHeader), unitIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *coreServiceHandler) HandleGetPerson(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	personIdArg, ok := pathParams["personId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"personId\" not present")
	}
	respArg, err := c.impl.GetPerson(req.Context(), bearertoken.Token(authHeader), personIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *coreServiceHandler) HandleGetPersons(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg GetPersonsRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := c.impl.GetPersons(req.Context(), bearertoken.Token(authHeader), requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

// The super-admin surface replacing the deleted oikumenea-console (D-SuperAdminFold): people search, role catalog, per-unit role-assignment grant/list/revoke, and the instance-admin plane's own grant/list/revoke. Every endpoint in this service is gated as a whole route group by internal/authz/transport.RequireInstanceAdmin, attached once at registration (cmd/openfaithmap-api/register_core.go) — not per-handler, so no future endpoint added here can be added without inheriting the check.
type CoreSuperAdminService interface {
	SearchPersons(ctx context.Context, authHeader bearertoken.Token, queryArg *string, limitArg *int) (PersonPage, error)
	ListRoles(ctx context.Context, authHeader bearertoken.Token) (RolePage, error)
	ListRoleAssignmentsByUnit(ctx context.Context, authHeader bearertoken.Token, unitIdArg string) (RoleAssignmentPage, error)
	GrantUnitRole(ctx context.Context, authHeader bearertoken.Token, requestArg GrantUnitRoleRequest) error
	RevokeRoleAssignment(ctx context.Context, authHeader bearertoken.Token, assignmentIdArg string) error
	ListInstanceAdmins(ctx context.Context, authHeader bearertoken.Token) (InstanceAdminPage, error)
	GrantInstanceAdmin(ctx context.Context, authHeader bearertoken.Token, requestArg GrantInstanceAdminRequest) (InstanceAdminGrant, error)
	RevokeInstanceAdmin(ctx context.Context, authHeader bearertoken.Token, personIdArg string) error
}

// RegisterRoutesCoreSuperAdminService registers handlers for the CoreSuperAdminService endpoints with a witchcraft wrouter.
// This should typically be called in a witchcraft server's InitFunc.
// impl provides an implementation of each endpoint, which can assume the request parameters have been parsed
// in accordance with the Conjure specification.
func RegisterRoutesCoreSuperAdminService(router wrouter.Router, impl CoreSuperAdminService, routerParams ...wrouter.RouteParam) error {
	handler := coreSuperAdminServiceHandler{impl: impl}
	resource := wresource.New("coresuperadminservice", router)
	if err := resource.Get("SearchPersons", "/core/v1/super-admin/persons", httpserver.NewJSONHandler(handler.HandleSearchPersons, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add searchPersons route")
	}
	if err := resource.Get("ListRoles", "/core/v1/super-admin/roles", httpserver.NewJSONHandler(handler.HandleListRoles, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listRoles route")
	}
	if err := resource.Get("ListRoleAssignmentsByUnit", "/core/v1/super-admin/units/{unitId}/role-assignments", httpserver.NewJSONHandler(handler.HandleListRoleAssignmentsByUnit, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listRoleAssignmentsByUnit route")
	}
	if err := resource.Post("GrantUnitRole", "/core/v1/super-admin/role-assignments", httpserver.NewJSONHandler(handler.HandleGrantUnitRole, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add grantUnitRole route")
	}
	if err := resource.Delete("RevokeRoleAssignment", "/core/v1/super-admin/role-assignments/{assignmentId}", httpserver.NewJSONHandler(handler.HandleRevokeRoleAssignment, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add revokeRoleAssignment route")
	}
	if err := resource.Get("ListInstanceAdmins", "/core/v1/super-admin/instance-admins", httpserver.NewJSONHandler(handler.HandleListInstanceAdmins, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listInstanceAdmins route")
	}
	if err := resource.Post("GrantInstanceAdmin", "/core/v1/super-admin/instance-admins", httpserver.NewJSONHandler(handler.HandleGrantInstanceAdmin, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add grantInstanceAdmin route")
	}
	if err := resource.Delete("RevokeInstanceAdmin", "/core/v1/super-admin/instance-admins/{personId}", httpserver.NewJSONHandler(handler.HandleRevokeInstanceAdmin, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add revokeInstanceAdmin route")
	}
	return nil
}

type coreSuperAdminServiceHandler struct {
	impl CoreSuperAdminService
}

func (c *coreSuperAdminServiceHandler) HandleSearchPersons(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var queryArg *string
	if queryArgStr := req.URL.Query().Get("query"); queryArgStr != "" {
		queryArgInternal := queryArgStr
		queryArg = &queryArgInternal
	}
	var limitArg *int
	if limitArgStr := req.URL.Query().Get("limit"); limitArgStr != "" {
		limitArgInternal, err := strconv.Atoi(limitArgStr)
		if err != nil {
			return werror.WrapWithContextParams(req.Context(), errors.WrapWithInvalidArgument(err), "failed to parse \"limit\" as integer")
		}
		limitArg = &limitArgInternal
	}
	respArg, err := c.impl.SearchPersons(req.Context(), bearertoken.Token(authHeader), queryArg, limitArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *coreSuperAdminServiceHandler) HandleListRoles(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	respArg, err := c.impl.ListRoles(req.Context(), bearertoken.Token(authHeader))
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *coreSuperAdminServiceHandler) HandleListRoleAssignmentsByUnit(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	unitIdArg, ok := pathParams["unitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"unitId\" not present")
	}
	respArg, err := c.impl.ListRoleAssignmentsByUnit(req.Context(), bearertoken.Token(authHeader), unitIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *coreSuperAdminServiceHandler) HandleGrantUnitRole(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg GrantUnitRoleRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	if err := c.impl.GrantUnitRole(req.Context(), bearertoken.Token(authHeader), requestArg); err != nil {
		return err
	}
	rw.WriteHeader(http.StatusNoContent)
	return nil
}

func (c *coreSuperAdminServiceHandler) HandleRevokeRoleAssignment(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	assignmentIdArg, ok := pathParams["assignmentId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"assignmentId\" not present")
	}
	if err := c.impl.RevokeRoleAssignment(req.Context(), bearertoken.Token(authHeader), assignmentIdArg); err != nil {
		return err
	}
	rw.WriteHeader(http.StatusNoContent)
	return nil
}

func (c *coreSuperAdminServiceHandler) HandleListInstanceAdmins(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	respArg, err := c.impl.ListInstanceAdmins(req.Context(), bearertoken.Token(authHeader))
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *coreSuperAdminServiceHandler) HandleGrantInstanceAdmin(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg GrantInstanceAdminRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := c.impl.GrantInstanceAdmin(req.Context(), bearertoken.Token(authHeader), requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *coreSuperAdminServiceHandler) HandleRevokeInstanceAdmin(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	personIdArg, ok := pathParams["personId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"personId\" not present")
	}
	if err := c.impl.RevokeInstanceAdmin(req.Context(), bearertoken.Token(authHeader), personIdArg); err != nil {
		return err
	}
	rw.WriteHeader(http.StatusNoContent)
	return nil
}
