// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package contentsql

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteNavItems = `-- name: DeleteNavItems :exec

DELETE FROM openfaithmap.content_site_nav_items WHERE site_id = $1
`

// ---- nav items (M14.10) ----
func (q *Queries) DeleteNavItems(ctx context.Context, siteID string) error {
	_, err := q.db.Exec(ctx, deleteNavItems, siteID)
	return err
}

const deletePattern = `-- name: DeletePattern :execrows
UPDATE openfaithmap.content_patterns SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeletePattern(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePattern, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBlockTypeByCode = `-- name: GetBlockTypeByCode :one
SELECT id, code, name, json_schema, ui_schema, status, sort_order
FROM openfaithmap.content_block_types WHERE code = $1 AND deleted_at IS NULL
`

type GetBlockTypeByCodeRow struct {
	ID         string
	Code       string
	Name       string
	JsonSchema json.RawMessage
	UiSchema   json.RawMessage
	Status     string
	SortOrder  int32
}

func (q *Queries) GetBlockTypeByCode(ctx context.Context, code string) (GetBlockTypeByCodeRow, error) {
	row := q.db.QueryRow(ctx, getBlockTypeByCode, code)
	var i GetBlockTypeByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.JsonSchema,
		&i.UiSchema,
		&i.Status,
		&i.SortOrder,
	)
	return i, err
}

const getBlockTypeByID = `-- name: GetBlockTypeByID :one

SELECT id, code, name, json_schema, ui_schema, status, sort_order
FROM openfaithmap.content_block_types WHERE id = $1 AND deleted_at IS NULL
`

type GetBlockTypeByIDRow struct {
	ID         string
	Code       string
	Name       string
	JsonSchema json.RawMessage
	UiSchema   json.RawMessage
	Status     string
	SortOrder  int32
}

// ---- block-type catalog admin (M14.13, content.catalog.manage) ----
func (q *Queries) GetBlockTypeByID(ctx context.Context, id string) (GetBlockTypeByIDRow, error) {
	row := q.db.QueryRow(ctx, getBlockTypeByID, id)
	var i GetBlockTypeByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.JsonSchema,
		&i.UiSchema,
		&i.Status,
		&i.SortOrder,
	)
	return i, err
}

const getDocument = `-- name: GetDocument :one
SELECT id, site_id, kind, translation_group_id, locale, parent_document_id, slug, state, published_at,
	event_starts_at, event_ends_at, event_recurrence_rrule, created_at, updated_at, draft_revision_id, published_revision_id, publish_at, meta_title, meta_description
FROM openfaithmap.content_documents WHERE id = $1 AND deleted_at IS NULL
`

type GetDocumentRow struct {
	ID                   string
	SiteID               string
	Kind                 string
	TranslationGroupID   string
	Locale               string
	ParentDocumentID     pgtype.Text
	Slug                 string
	State                string
	PublishedAt          pgtype.Timestamptz
	EventStartsAt        pgtype.Timestamptz
	EventEndsAt          pgtype.Timestamptz
	EventRecurrenceRrule pgtype.Text
	CreatedAt            time.Time
	UpdatedAt            time.Time
	DraftRevisionID      pgtype.Text
	PublishedRevisionID  pgtype.Text
	PublishAt            pgtype.Timestamptz
	MetaTitle            pgtype.Text
	MetaDescription      pgtype.Text
}

func (q *Queries) GetDocument(ctx context.Context, id string) (GetDocumentRow, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i GetDocumentRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Kind,
		&i.TranslationGroupID,
		&i.Locale,
		&i.ParentDocumentID,
		&i.Slug,
		&i.State,
		&i.PublishedAt,
		&i.EventStartsAt,
		&i.EventEndsAt,
		&i.EventRecurrenceRrule,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DraftRevisionID,
		&i.PublishedRevisionID,
		&i.PublishAt,
		&i.MetaTitle,
		&i.MetaDescription,
	)
	return i, err
}

const getDocumentBySlug = `-- name: GetDocumentBySlug :one
SELECT id, site_id, kind, translation_group_id, locale, parent_document_id, slug, state, published_at,
	event_starts_at, event_ends_at, event_recurrence_rrule, created_at, updated_at, draft_revision_id, published_revision_id, publish_at, meta_title, meta_description
FROM openfaithmap.content_documents
WHERE site_id = $1 AND kind = $2 AND locale = $3
	AND slug = $4 AND deleted_at IS NULL
`

type GetDocumentBySlugParams struct {
	SiteID string
	Kind   string
	Locale string
	Slug   string
}

type GetDocumentBySlugRow struct {
	ID                   string
	SiteID               string
	Kind                 string
	TranslationGroupID   string
	Locale               string
	ParentDocumentID     pgtype.Text
	Slug                 string
	State                string
	PublishedAt          pgtype.Timestamptz
	EventStartsAt        pgtype.Timestamptz
	EventEndsAt          pgtype.Timestamptz
	EventRecurrenceRrule pgtype.Text
	CreatedAt            time.Time
	UpdatedAt            time.Time
	DraftRevisionID      pgtype.Text
	PublishedRevisionID  pgtype.Text
	PublishAt            pgtype.Timestamptz
	MetaTitle            pgtype.Text
	MetaDescription      pgtype.Text
}

func (q *Queries) GetDocumentBySlug(ctx context.Context, arg GetDocumentBySlugParams) (GetDocumentBySlugRow, error) {
	row := q.db.QueryRow(ctx, getDocumentBySlug,
		arg.SiteID,
		arg.Kind,
		arg.Locale,
		arg.Slug,
	)
	var i GetDocumentBySlugRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Kind,
		&i.TranslationGroupID,
		&i.Locale,
		&i.ParentDocumentID,
		&i.Slug,
		&i.State,
		&i.PublishedAt,
		&i.EventStartsAt,
		&i.EventEndsAt,
		&i.EventRecurrenceRrule,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DraftRevisionID,
		&i.PublishedRevisionID,
		&i.PublishAt,
		&i.MetaTitle,
		&i.MetaDescription,
	)
	return i, err
}

const getRevision = `-- name: GetRevision :one
SELECT id, document_id, revision_no, data, author_person_id, created_at, label
FROM openfaithmap.content_document_revisions WHERE id = $1
`

func (q *Queries) GetRevision(ctx context.Context, id string) (OpenfaithmapContentDocumentRevision, error) {
	row := q.db.QueryRow(ctx, getRevision, id)
	var i OpenfaithmapContentDocumentRevision
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.RevisionNo,
		&i.Data,
		&i.AuthorPersonID,
		&i.CreatedAt,
		&i.Label,
	)
	return i, err
}

const getSiteByID = `-- name: GetSiteByID :one
SELECT id, congregation_unit_rid, slug, theme, logo_url, social_links, created_at, updated_at
FROM openfaithmap.content_sites WHERE id = $1 AND deleted_at IS NULL
`

type GetSiteByIDRow struct {
	ID                  string
	CongregationUnitRid string
	Slug                string
	Theme               json.RawMessage
	LogoUrl             pgtype.Text
	SocialLinks         json.RawMessage
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) GetSiteByID(ctx context.Context, id string) (GetSiteByIDRow, error) {
	row := q.db.QueryRow(ctx, getSiteByID, id)
	var i GetSiteByIDRow
	err := row.Scan(
		&i.ID,
		&i.CongregationUnitRid,
		&i.Slug,
		&i.Theme,
		&i.LogoUrl,
		&i.SocialLinks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteBySlug = `-- name: GetSiteBySlug :one
SELECT id, congregation_unit_rid, slug, theme, logo_url, social_links, created_at, updated_at
FROM openfaithmap.content_sites WHERE slug = $1 AND deleted_at IS NULL
`

type GetSiteBySlugRow struct {
	ID                  string
	CongregationUnitRid string
	Slug                string
	Theme               json.RawMessage
	LogoUrl             pgtype.Text
	SocialLinks         json.RawMessage
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) GetSiteBySlug(ctx context.Context, slug string) (GetSiteBySlugRow, error) {
	row := q.db.QueryRow(ctx, getSiteBySlug, slug)
	var i GetSiteBySlugRow
	err := row.Scan(
		&i.ID,
		&i.CongregationUnitRid,
		&i.Slug,
		&i.Theme,
		&i.LogoUrl,
		&i.SocialLinks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteByUnit = `-- name: GetSiteByUnit :one
SELECT id, congregation_unit_rid, slug, theme, logo_url, social_links, created_at, updated_at
FROM openfaithmap.content_sites WHERE congregation_unit_rid = $1 AND deleted_at IS NULL
`

type GetSiteByUnitRow struct {
	ID                  string
	CongregationUnitRid string
	Slug                string
	Theme               json.RawMessage
	LogoUrl             pgtype.Text
	SocialLinks         json.RawMessage
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) GetSiteByUnit(ctx context.Context, congregationUnitRid string) (GetSiteByUnitRow, error) {
	row := q.db.QueryRow(ctx, getSiteByUnit, congregationUnitRid)
	var i GetSiteByUnitRow
	err := row.Scan(
		&i.ID,
		&i.CongregationUnitRid,
		&i.Slug,
		&i.Theme,
		&i.LogoUrl,
		&i.SocialLinks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBlockType = `-- name: InsertBlockType :one
INSERT INTO openfaithmap.content_block_types (code, name, json_schema, ui_schema, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code, name, json_schema, ui_schema, status, sort_order
`

type InsertBlockTypeParams struct {
	Code       string
	Name       string
	JsonSchema json.RawMessage
	UiSchema   json.RawMessage
	SortOrder  int32
}

type InsertBlockTypeRow struct {
	ID         string
	Code       string
	Name       string
	JsonSchema json.RawMessage
	UiSchema   json.RawMessage
	Status     string
	SortOrder  int32
}

func (q *Queries) InsertBlockType(ctx context.Context, arg InsertBlockTypeParams) (InsertBlockTypeRow, error) {
	row := q.db.QueryRow(ctx, insertBlockType,
		arg.Code,
		arg.Name,
		arg.JsonSchema,
		arg.UiSchema,
		arg.SortOrder,
	)
	var i InsertBlockTypeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.JsonSchema,
		&i.UiSchema,
		&i.Status,
		&i.SortOrder,
	)
	return i, err
}

const insertDocument = `-- name: InsertDocument :one
INSERT INTO openfaithmap.content_documents
	(site_id, kind, translation_group_id, locale, parent_document_id, slug,
	 event_starts_at, event_ends_at, event_recurrence_rrule)
VALUES ($1, $2, COALESCE($3::uuid, gen_random_uuid()),
	$4, $5, $6,
	$7, $8, $9)
RETURNING id, site_id, kind, translation_group_id, locale, parent_document_id, slug, state, published_at,
	event_starts_at, event_ends_at, event_recurrence_rrule, created_at, updated_at, draft_revision_id, published_revision_id, publish_at, meta_title, meta_description
`

type InsertDocumentParams struct {
	SiteID               string
	Kind                 string
	TranslationGroupID   pgtype.Text
	Locale               string
	ParentDocumentID     pgtype.Text
	Slug                 string
	EventStartsAt        pgtype.Timestamptz
	EventEndsAt          pgtype.Timestamptz
	EventRecurrenceRrule pgtype.Text
}

type InsertDocumentRow struct {
	ID                   string
	SiteID               string
	Kind                 string
	TranslationGroupID   string
	Locale               string
	ParentDocumentID     pgtype.Text
	Slug                 string
	State                string
	PublishedAt          pgtype.Timestamptz
	EventStartsAt        pgtype.Timestamptz
	EventEndsAt          pgtype.Timestamptz
	EventRecurrenceRrule pgtype.Text
	CreatedAt            time.Time
	UpdatedAt            time.Time
	DraftRevisionID      pgtype.Text
	PublishedRevisionID  pgtype.Text
	PublishAt            pgtype.Timestamptz
	MetaTitle            pgtype.Text
	MetaDescription      pgtype.Text
}

func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) (InsertDocumentRow, error) {
	row := q.db.QueryRow(ctx, insertDocument,
		arg.SiteID,
		arg.Kind,
		arg.TranslationGroupID,
		arg.Locale,
		arg.ParentDocumentID,
		arg.Slug,
		arg.EventStartsAt,
		arg.EventEndsAt,
		arg.EventRecurrenceRrule,
	)
	var i InsertDocumentRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Kind,
		&i.TranslationGroupID,
		&i.Locale,
		&i.ParentDocumentID,
		&i.Slug,
		&i.State,
		&i.PublishedAt,
		&i.EventStartsAt,
		&i.EventEndsAt,
		&i.EventRecurrenceRrule,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DraftRevisionID,
		&i.PublishedRevisionID,
		&i.PublishAt,
		&i.MetaTitle,
		&i.MetaDescription,
	)
	return i, err
}

const insertFormSubmission = `-- name: InsertFormSubmission :one

INSERT INTO openfaithmap.content_form_submissions (site_id, name, email, message)
VALUES ($1, $2, $3, $4)
RETURNING id, site_id, name, email, message, created_at
`

type InsertFormSubmissionParams struct {
	SiteID  string
	Name    pgtype.Text
	Email   pgtype.Text
	Message string
}

// ---- form submissions (M14.16, D-InAppInbox) ----
func (q *Queries) InsertFormSubmission(ctx context.Context, arg InsertFormSubmissionParams) (OpenfaithmapContentFormSubmission, error) {
	row := q.db.QueryRow(ctx, insertFormSubmission,
		arg.SiteID,
		arg.Name,
		arg.Email,
		arg.Message,
	)
	var i OpenfaithmapContentFormSubmission
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Name,
		&i.Email,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const insertNavItem = `-- name: InsertNavItem :one
INSERT INTO openfaithmap.content_site_nav_items (site_id, label, target_document_id, target_url, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, site_id, label, target_document_id, target_url, sort_order
`

type InsertNavItemParams struct {
	SiteID           string
	Label            string
	TargetDocumentID pgtype.Text
	TargetUrl        pgtype.Text
	SortOrder        int32
}

type InsertNavItemRow struct {
	ID               string
	SiteID           string
	Label            string
	TargetDocumentID pgtype.Text
	TargetUrl        pgtype.Text
	SortOrder        int32
}

func (q *Queries) InsertNavItem(ctx context.Context, arg InsertNavItemParams) (InsertNavItemRow, error) {
	row := q.db.QueryRow(ctx, insertNavItem,
		arg.SiteID,
		arg.Label,
		arg.TargetDocumentID,
		arg.TargetUrl,
		arg.SortOrder,
	)
	var i InsertNavItemRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Label,
		&i.TargetDocumentID,
		&i.TargetUrl,
		&i.SortOrder,
	)
	return i, err
}

const insertPattern = `-- name: InsertPattern :one

INSERT INTO openfaithmap.content_patterns (name, description, blocks, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, name, description, blocks, sort_order, created_at, updated_at
`

type InsertPatternParams struct {
	Name        string
	Description string
	Blocks      json.RawMessage
	SortOrder   int32
}

type InsertPatternRow struct {
	ID          string
	Name        string
	Description string
	Blocks      json.RawMessage
	SortOrder   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// ---- patterns (M14.13, D-SitePatterns) ----
func (q *Queries) InsertPattern(ctx context.Context, arg InsertPatternParams) (InsertPatternRow, error) {
	row := q.db.QueryRow(ctx, insertPattern,
		arg.Name,
		arg.Description,
		arg.Blocks,
		arg.SortOrder,
	)
	var i InsertPatternRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Blocks,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRevision = `-- name: InsertRevision :one

INSERT INTO openfaithmap.content_document_revisions (document_id, revision_no, data, author_person_id, label)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, document_id, revision_no, data, author_person_id, created_at, label
`

type InsertRevisionParams struct {
	DocumentID     string
	RevisionNo     int32
	Data           json.RawMessage
	AuthorPersonID pgtype.Text
	Label          pgtype.Text
}

// ---- revisions (M14.6) ----
func (q *Queries) InsertRevision(ctx context.Context, arg InsertRevisionParams) (OpenfaithmapContentDocumentRevision, error) {
	row := q.db.QueryRow(ctx, insertRevision,
		arg.DocumentID,
		arg.RevisionNo,
		arg.Data,
		arg.AuthorPersonID,
		arg.Label,
	)
	var i OpenfaithmapContentDocumentRevision
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.RevisionNo,
		&i.Data,
		&i.AuthorPersonID,
		&i.CreatedAt,
		&i.Label,
	)
	return i, err
}

const insertSite = `-- name: InsertSite :one
INSERT INTO openfaithmap.content_sites (congregation_unit_rid, slug)
VALUES ($1, $2)
RETURNING id, congregation_unit_rid, slug, theme, logo_url, social_links, created_at, updated_at
`

type InsertSiteParams struct {
	CongregationUnitRid string
	Slug                string
}

type InsertSiteRow struct {
	ID                  string
	CongregationUnitRid string
	Slug                string
	Theme               json.RawMessage
	LogoUrl             pgtype.Text
	SocialLinks         json.RawMessage
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) InsertSite(ctx context.Context, arg InsertSiteParams) (InsertSiteRow, error) {
	row := q.db.QueryRow(ctx, insertSite, arg.CongregationUnitRid, arg.Slug)
	var i InsertSiteRow
	err := row.Scan(
		&i.ID,
		&i.CongregationUnitRid,
		&i.Slug,
		&i.Theme,
		&i.LogoUrl,
		&i.SocialLinks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveBlockTypes = `-- name: ListActiveBlockTypes :many
SELECT id, code, name, json_schema, ui_schema, status, sort_order
FROM openfaithmap.content_block_types
WHERE status = 'ACTIVE' AND deleted_at IS NULL
ORDER BY sort_order ASC
`

type ListActiveBlockTypesRow struct {
	ID         string
	Code       string
	Name       string
	JsonSchema json.RawMessage
	UiSchema   json.RawMessage
	Status     string
	SortOrder  int32
}

func (q *Queries) ListActiveBlockTypes(ctx context.Context) ([]ListActiveBlockTypesRow, error) {
	rows, err := q.db.Query(ctx, listActiveBlockTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveBlockTypesRow
	for rows.Next() {
		var i ListActiveBlockTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.JsonSchema,
			&i.UiSchema,
			&i.Status,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllBlockTypes = `-- name: ListAllBlockTypes :many
SELECT id, code, name, json_schema, ui_schema, status, sort_order
FROM openfaithmap.content_block_types
WHERE deleted_at IS NULL
ORDER BY sort_order ASC
`

type ListAllBlockTypesRow struct {
	ID         string
	Code       string
	Name       string
	JsonSchema json.RawMessage
	UiSchema   json.RawMessage
	Status     string
	SortOrder  int32
}

// Every status, unlike ListActiveBlockTypes — the moderator catalog page needs to see/edit
// RETIRED types too.
func (q *Queries) ListAllBlockTypes(ctx context.Context) ([]ListAllBlockTypesRow, error) {
	rows, err := q.db.Query(ctx, listAllBlockTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllBlockTypesRow
	for rows.Next() {
		var i ListAllBlockTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.JsonSchema,
			&i.UiSchema,
			&i.Status,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckpointRevisions = `-- name: ListCheckpointRevisions :many
SELECT id, document_id, revision_no, data, author_person_id, created_at, label
FROM openfaithmap.content_document_revisions
WHERE document_id = $1 AND id != $2
ORDER BY revision_no DESC
`

type ListCheckpointRevisionsParams struct {
	DocumentID string
	ExcludeID  string
}

func (q *Queries) ListCheckpointRevisions(ctx context.Context, arg ListCheckpointRevisionsParams) ([]OpenfaithmapContentDocumentRevision, error) {
	rows, err := q.db.Query(ctx, listCheckpointRevisions, arg.DocumentID, arg.ExcludeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpenfaithmapContentDocumentRevision
	for rows.Next() {
		var i OpenfaithmapContentDocumentRevision
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.RevisionNo,
			&i.Data,
			&i.AuthorPersonID,
			&i.CreatedAt,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, site_id, kind, translation_group_id, locale, parent_document_id, slug, state, published_at,
	event_starts_at, event_ends_at, event_recurrence_rrule, created_at, updated_at, draft_revision_id, published_revision_id, publish_at, meta_title, meta_description
FROM openfaithmap.content_documents
WHERE site_id = $1 AND deleted_at IS NULL
	AND ($2::text IS NULL OR kind = $2::text)
	AND ($3::text IS NULL OR locale = $3::text)
	AND ($4::text IS NULL OR state = $4::text)
ORDER BY created_at DESC
`

type ListDocumentsParams struct {
	SiteID string
	Kind   pgtype.Text
	Locale pgtype.Text
	State  pgtype.Text
}

type ListDocumentsRow struct {
	ID                   string
	SiteID               string
	Kind                 string
	TranslationGroupID   string
	Locale               string
	ParentDocumentID     pgtype.Text
	Slug                 string
	State                string
	PublishedAt          pgtype.Timestamptz
	EventStartsAt        pgtype.Timestamptz
	EventEndsAt          pgtype.Timestamptz
	EventRecurrenceRrule pgtype.Text
	CreatedAt            time.Time
	UpdatedAt            time.Time
	DraftRevisionID      pgtype.Text
	PublishedRevisionID  pgtype.Text
	PublishAt            pgtype.Timestamptz
	MetaTitle            pgtype.Text
	MetaDescription      pgtype.Text
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]ListDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listDocuments,
		arg.SiteID,
		arg.Kind,
		arg.Locale,
		arg.State,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsRow
	for rows.Next() {
		var i ListDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Kind,
			&i.TranslationGroupID,
			&i.Locale,
			&i.ParentDocumentID,
			&i.Slug,
			&i.State,
			&i.PublishedAt,
			&i.EventStartsAt,
			&i.EventEndsAt,
			&i.EventRecurrenceRrule,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DraftRevisionID,
			&i.PublishedRevisionID,
			&i.PublishAt,
			&i.MetaTitle,
			&i.MetaDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByTranslationGroup = `-- name: ListDocumentsByTranslationGroup :many
SELECT id, site_id, kind, translation_group_id, locale, parent_document_id, slug, state, published_at,
	event_starts_at, event_ends_at, event_recurrence_rrule, created_at, updated_at, draft_revision_id, published_revision_id, publish_at, meta_title, meta_description
FROM openfaithmap.content_documents
WHERE translation_group_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

type ListDocumentsByTranslationGroupRow struct {
	ID                   string
	SiteID               string
	Kind                 string
	TranslationGroupID   string
	Locale               string
	ParentDocumentID     pgtype.Text
	Slug                 string
	State                string
	PublishedAt          pgtype.Timestamptz
	EventStartsAt        pgtype.Timestamptz
	EventEndsAt          pgtype.Timestamptz
	EventRecurrenceRrule pgtype.Text
	CreatedAt            time.Time
	UpdatedAt            time.Time
	DraftRevisionID      pgtype.Text
	PublishedRevisionID  pgtype.Text
	PublishAt            pgtype.Timestamptz
	MetaTitle            pgtype.Text
	MetaDescription      pgtype.Text
}

// M14.14: every document sharing one translation_group_id, any state, any site — deliberately not
// scoped by site_id, so CreateDocument's cross-site guard (application.Service) can tell "brand new
// group" apart from "this group belongs to a different site" by inspecting the returned rows'
// own site_id, rather than the query silently filtering a cross-site collision down to zero rows.
func (q *Queries) ListDocumentsByTranslationGroup(ctx context.Context, translationGroupID string) ([]ListDocumentsByTranslationGroupRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsByTranslationGroup, translationGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsByTranslationGroupRow
	for rows.Next() {
		var i ListDocumentsByTranslationGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Kind,
			&i.TranslationGroupID,
			&i.Locale,
			&i.ParentDocumentID,
			&i.Slug,
			&i.State,
			&i.PublishedAt,
			&i.EventStartsAt,
			&i.EventEndsAt,
			&i.EventRecurrenceRrule,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DraftRevisionID,
			&i.PublishedRevisionID,
			&i.PublishAt,
			&i.MetaTitle,
			&i.MetaDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFormSubmissionsBySite = `-- name: ListFormSubmissionsBySite :many
SELECT id, site_id, name, email, message, created_at
FROM openfaithmap.content_form_submissions
WHERE site_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFormSubmissionsBySite(ctx context.Context, siteID string) ([]OpenfaithmapContentFormSubmission, error) {
	rows, err := q.db.Query(ctx, listFormSubmissionsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpenfaithmapContentFormSubmission
	for rows.Next() {
		var i OpenfaithmapContentFormSubmission
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Name,
			&i.Email,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNavItems = `-- name: ListNavItems :many
SELECT id, site_id, label, target_document_id, target_url, sort_order
FROM openfaithmap.content_site_nav_items
WHERE site_id = $1
ORDER BY sort_order ASC
`

type ListNavItemsRow struct {
	ID               string
	SiteID           string
	Label            string
	TargetDocumentID pgtype.Text
	TargetUrl        pgtype.Text
	SortOrder        int32
}

func (q *Queries) ListNavItems(ctx context.Context, siteID string) ([]ListNavItemsRow, error) {
	rows, err := q.db.Query(ctx, listNavItems, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNavItemsRow
	for rows.Next() {
		var i ListNavItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Label,
			&i.TargetDocumentID,
			&i.TargetUrl,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatterns = `-- name: ListPatterns :many
SELECT id, name, description, blocks, sort_order, created_at, updated_at
FROM openfaithmap.content_patterns
WHERE deleted_at IS NULL
ORDER BY sort_order ASC
`

type ListPatternsRow struct {
	ID          string
	Name        string
	Description string
	Blocks      json.RawMessage
	SortOrder   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ListPatterns(ctx context.Context) ([]ListPatternsRow, error) {
	rows, err := q.db.Query(ctx, listPatterns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPatternsRow
	for rows.Next() {
		var i ListPatternsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Blocks,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicDocuments = `-- name: ListPublicDocuments :many
SELECT id, site_id, kind, translation_group_id, locale, parent_document_id, slug, state, published_at,
	event_starts_at, event_ends_at, event_recurrence_rrule, created_at, updated_at, draft_revision_id, published_revision_id, publish_at, meta_title, meta_description
FROM openfaithmap.content_documents
WHERE site_id = $1 AND deleted_at IS NULL
	AND (state IN ('PUBLISHED', 'UNLISTED') OR (state = 'SCHEDULED' AND publish_at <= now()))
	AND ($2::text IS NULL OR kind = $2::text)
	AND ($3::text IS NULL OR locale = $3::text)
ORDER BY CASE WHEN kind = 'EVENT' THEN event_starts_at END ASC NULLS LAST, created_at DESC
`

type ListPublicDocumentsParams struct {
	SiteID string
	Kind   pgtype.Text
	Locale pgtype.Text
}

type ListPublicDocumentsRow struct {
	ID                   string
	SiteID               string
	Kind                 string
	TranslationGroupID   string
	Locale               string
	ParentDocumentID     pgtype.Text
	Slug                 string
	State                string
	PublishedAt          pgtype.Timestamptz
	EventStartsAt        pgtype.Timestamptz
	EventEndsAt          pgtype.Timestamptz
	EventRecurrenceRrule pgtype.Text
	CreatedAt            time.Time
	UpdatedAt            time.Time
	DraftRevisionID      pgtype.Text
	PublishedRevisionID  pgtype.Text
	PublishAt            pgtype.Timestamptz
	MetaTitle            pgtype.Text
	MetaDescription      pgtype.Text
}

// M14.15/D-PublishOnRead: a SCHEDULED document whose publish_at has passed is publicly listed with
// no job ever having flipped its state — correctness lives entirely in this WHERE clause.
func (q *Queries) ListPublicDocuments(ctx context.Context, arg ListPublicDocumentsParams) ([]ListPublicDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listPublicDocuments, arg.SiteID, arg.Kind, arg.Locale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicDocumentsRow
	for rows.Next() {
		var i ListPublicDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Kind,
			&i.TranslationGroupID,
			&i.Locale,
			&i.ParentDocumentID,
			&i.Slug,
			&i.State,
			&i.PublishedAt,
			&i.EventStartsAt,
			&i.EventEndsAt,
			&i.EventRecurrenceRrule,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DraftRevisionID,
			&i.PublishedRevisionID,
			&i.PublishAt,
			&i.MetaTitle,
			&i.MetaDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextRevisionNo = `-- name: NextRevisionNo :one
SELECT COALESCE(MAX(revision_no), 0) + 1 FROM openfaithmap.content_document_revisions WHERE document_id = $1
`

func (q *Queries) NextRevisionNo(ctx context.Context, documentID string) (int32, error) {
	row := q.db.QueryRow(ctx, nextRevisionNo, documentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const pruneCheckpointRevisions = `-- name: PruneCheckpointRevisions :exec
DELETE FROM openfaithmap.content_document_revisions cdr
WHERE cdr.document_id = $1
  AND cdr.id != $2
  AND cdr.id != $3
  AND cdr.revision_no <= (
    SELECT r2.revision_no FROM openfaithmap.content_document_revisions r2
    WHERE r2.document_id = $1
    ORDER BY r2.revision_no DESC
    OFFSET $4 LIMIT 1
  )
`

type PruneCheckpointRevisionsParams struct {
	DocumentID      string
	KeepDraftID     string
	KeepPublishedID string
	KeepCount       int32
}

func (q *Queries) PruneCheckpointRevisions(ctx context.Context, arg PruneCheckpointRevisionsParams) error {
	_, err := q.db.Exec(ctx, pruneCheckpointRevisions,
		arg.DocumentID,
		arg.KeepDraftID,
		arg.KeepPublishedID,
		arg.KeepCount,
	)
	return err
}

const setDraftRevision = `-- name: SetDraftRevision :exec
UPDATE openfaithmap.content_documents SET draft_revision_id = $1 WHERE id = $2
`

type SetDraftRevisionParams struct {
	DraftRevisionID pgtype.Text
	ID              string
}

func (q *Queries) SetDraftRevision(ctx context.Context, arg SetDraftRevisionParams) error {
	_, err := q.db.Exec(ctx, setDraftRevision, arg.DraftRevisionID, arg.ID)
	return err
}

const setPublishedRevision = `-- name: SetPublishedRevision :exec
UPDATE openfaithmap.content_documents SET published_revision_id = $1 WHERE id = $2
`

type SetPublishedRevisionParams struct {
	PublishedRevisionID pgtype.Text
	ID                  string
}

func (q *Queries) SetPublishedRevision(ctx context.Context, arg SetPublishedRevisionParams) error {
	_, err := q.db.Exec(ctx, setPublishedRevision, arg.PublishedRevisionID, arg.ID)
	return err
}

const updateBlockType = `-- name: UpdateBlockType :one
UPDATE openfaithmap.content_block_types
SET name = COALESCE($1, name),
    status = COALESCE($2, status),
    sort_order = COALESCE($3, sort_order)
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, code, name, json_schema, ui_schema, status, sort_order
`

type UpdateBlockTypeParams struct {
	Name      pgtype.Text
	Status    pgtype.Text
	SortOrder pgtype.Int4
	ID        string
}

type UpdateBlockTypeRow struct {
	ID         string
	Code       string
	Name       string
	JsonSchema json.RawMessage
	UiSchema   json.RawMessage
	Status     string
	SortOrder  int32
}

// json_schema/ui_schema are deliberately not settable here (owner decision, M14.13): locked after
// creation, so a runtime catalog edit can never silently break already-saved blocks or the admin
// form for an existing type.
func (q *Queries) UpdateBlockType(ctx context.Context, arg UpdateBlockTypeParams) (UpdateBlockTypeRow, error) {
	row := q.db.QueryRow(ctx, updateBlockType,
		arg.Name,
		arg.Status,
		arg.SortOrder,
		arg.ID,
	)
	var i UpdateBlockTypeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.JsonSchema,
		&i.UiSchema,
		&i.Status,
		&i.SortOrder,
	)
	return i, err
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE openfaithmap.content_documents
SET slug = COALESCE($1, slug),
    parent_document_id = CASE
      WHEN $2::bool THEN NULL
      WHEN $3::uuid IS NOT NULL THEN $3::uuid
      ELSE parent_document_id
    END,
    meta_title = COALESCE($4, meta_title),
    meta_description = COALESCE($5, meta_description)
WHERE id = $6 AND deleted_at IS NULL
RETURNING id, site_id, kind, translation_group_id, locale, parent_document_id, slug, state, published_at,
	event_starts_at, event_ends_at, event_recurrence_rrule, created_at, updated_at, draft_revision_id, published_revision_id, publish_at, meta_title, meta_description
`

type UpdateDocumentParams struct {
	Slug             pgtype.Text
	ClearParent      bool
	ParentDocumentID pgtype.Text
	MetaTitle        pgtype.Text
	MetaDescription  pgtype.Text
	ID               string
}

type UpdateDocumentRow struct {
	ID                   string
	SiteID               string
	Kind                 string
	TranslationGroupID   string
	Locale               string
	ParentDocumentID     pgtype.Text
	Slug                 string
	State                string
	PublishedAt          pgtype.Timestamptz
	EventStartsAt        pgtype.Timestamptz
	EventEndsAt          pgtype.Timestamptz
	EventRecurrenceRrule pgtype.Text
	CreatedAt            time.Time
	UpdatedAt            time.Time
	DraftRevisionID      pgtype.Text
	PublishedRevisionID  pgtype.Text
	PublishAt            pgtype.Timestamptz
	MetaTitle            pgtype.Text
	MetaDescription      pgtype.Text
}

// meta_title/meta_description: nil (narg unset) leaves the column unchanged; an empty string is a
// real value (clears the override back to the renderer's derived fallback), so this is COALESCE on
// the arg itself, same as slug — never on the empty string.
func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (UpdateDocumentRow, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.Slug,
		arg.ClearParent,
		arg.ParentDocumentID,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.ID,
	)
	var i UpdateDocumentRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Kind,
		&i.TranslationGroupID,
		&i.Locale,
		&i.ParentDocumentID,
		&i.Slug,
		&i.State,
		&i.PublishedAt,
		&i.EventStartsAt,
		&i.EventEndsAt,
		&i.EventRecurrenceRrule,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DraftRevisionID,
		&i.PublishedRevisionID,
		&i.PublishAt,
		&i.MetaTitle,
		&i.MetaDescription,
	)
	return i, err
}

const updateDocumentState = `-- name: UpdateDocumentState :one
UPDATE openfaithmap.content_documents
SET state = $1, publish_at = $2,
    published_at = CASE WHEN $3::bool THEN now() ELSE published_at END
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, site_id, kind, translation_group_id, locale, parent_document_id, slug, state, published_at,
	event_starts_at, event_ends_at, event_recurrence_rrule, created_at, updated_at, draft_revision_id, published_revision_id, publish_at, meta_title, meta_description
`

type UpdateDocumentStateParams struct {
	State        string
	PublishAt    pgtype.Timestamptz
	FirstPublish bool
	ID           string
}

type UpdateDocumentStateRow struct {
	ID                   string
	SiteID               string
	Kind                 string
	TranslationGroupID   string
	Locale               string
	ParentDocumentID     pgtype.Text
	Slug                 string
	State                string
	PublishedAt          pgtype.Timestamptz
	EventStartsAt        pgtype.Timestamptz
	EventEndsAt          pgtype.Timestamptz
	EventRecurrenceRrule pgtype.Text
	CreatedAt            time.Time
	UpdatedAt            time.Time
	DraftRevisionID      pgtype.Text
	PublishedRevisionID  pgtype.Text
	PublishAt            pgtype.Timestamptz
	MetaTitle            pgtype.Text
	MetaDescription      pgtype.Text
}

// publish_at is set unconditionally (not COALESCE): every transition other than SCHEDULE passes
// NULL, so leaving SCHEDULED by any path clears a stale future date (M14.15).
func (q *Queries) UpdateDocumentState(ctx context.Context, arg UpdateDocumentStateParams) (UpdateDocumentStateRow, error) {
	row := q.db.QueryRow(ctx, updateDocumentState,
		arg.State,
		arg.PublishAt,
		arg.FirstPublish,
		arg.ID,
	)
	var i UpdateDocumentStateRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Kind,
		&i.TranslationGroupID,
		&i.Locale,
		&i.ParentDocumentID,
		&i.Slug,
		&i.State,
		&i.PublishedAt,
		&i.EventStartsAt,
		&i.EventEndsAt,
		&i.EventRecurrenceRrule,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DraftRevisionID,
		&i.PublishedRevisionID,
		&i.PublishAt,
		&i.MetaTitle,
		&i.MetaDescription,
	)
	return i, err
}

const updatePattern = `-- name: UpdatePattern :one
UPDATE openfaithmap.content_patterns
SET name = COALESCE($1, name),
    description = COALESCE($2, description),
    blocks = COALESCE($3::jsonb, blocks),
    sort_order = COALESCE($4, sort_order)
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, name, description, blocks, sort_order, created_at, updated_at
`

type UpdatePatternParams struct {
	Name        pgtype.Text
	Description pgtype.Text
	Blocks      []byte
	SortOrder   pgtype.Int4
	ID          string
}

type UpdatePatternRow struct {
	ID          string
	Name        string
	Description string
	Blocks      json.RawMessage
	SortOrder   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) UpdatePattern(ctx context.Context, arg UpdatePatternParams) (UpdatePatternRow, error) {
	row := q.db.QueryRow(ctx, updatePattern,
		arg.Name,
		arg.Description,
		arg.Blocks,
		arg.SortOrder,
		arg.ID,
	)
	var i UpdatePatternRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Blocks,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRevisionData = `-- name: UpdateRevisionData :one
UPDATE openfaithmap.content_document_revisions SET data = $1
WHERE id = $2
RETURNING id, document_id, revision_no, data, author_person_id, created_at, label
`

type UpdateRevisionDataParams struct {
	Data json.RawMessage
	ID   string
}

func (q *Queries) UpdateRevisionData(ctx context.Context, arg UpdateRevisionDataParams) (OpenfaithmapContentDocumentRevision, error) {
	row := q.db.QueryRow(ctx, updateRevisionData, arg.Data, arg.ID)
	var i OpenfaithmapContentDocumentRevision
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.RevisionNo,
		&i.Data,
		&i.AuthorPersonID,
		&i.CreatedAt,
		&i.Label,
	)
	return i, err
}

const updateSiteChrome = `-- name: UpdateSiteChrome :one
UPDATE openfaithmap.content_sites SET logo_url = $1, social_links = $2
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, congregation_unit_rid, slug, theme, logo_url, social_links, created_at, updated_at
`

type UpdateSiteChromeParams struct {
	LogoUrl     pgtype.Text
	SocialLinks json.RawMessage
	ID          string
}

type UpdateSiteChromeRow struct {
	ID                  string
	CongregationUnitRid string
	Slug                string
	Theme               json.RawMessage
	LogoUrl             pgtype.Text
	SocialLinks         json.RawMessage
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

// M14.11: logo_url/social_links are content_sites' own site-level settings (never a content
// document) — everything else the header/footer needs (congregation name, address, service
// schedule) is composed at read time from religion_sites/religion_service_schedules, never stored
// here.
func (q *Queries) UpdateSiteChrome(ctx context.Context, arg UpdateSiteChromeParams) (UpdateSiteChromeRow, error) {
	row := q.db.QueryRow(ctx, updateSiteChrome, arg.LogoUrl, arg.SocialLinks, arg.ID)
	var i UpdateSiteChromeRow
	err := row.Scan(
		&i.ID,
		&i.CongregationUnitRid,
		&i.Slug,
		&i.Theme,
		&i.LogoUrl,
		&i.SocialLinks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSiteTheme = `-- name: UpdateSiteTheme :one
UPDATE openfaithmap.content_sites SET theme = $1
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, congregation_unit_rid, slug, theme, logo_url, social_links, created_at, updated_at
`

type UpdateSiteThemeParams struct {
	Theme json.RawMessage
	ID    string
}

type UpdateSiteThemeRow struct {
	ID                  string
	CongregationUnitRid string
	Slug                string
	Theme               json.RawMessage
	LogoUrl             pgtype.Text
	SocialLinks         json.RawMessage
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) UpdateSiteTheme(ctx context.Context, arg UpdateSiteThemeParams) (UpdateSiteThemeRow, error) {
	row := q.db.QueryRow(ctx, updateSiteTheme, arg.Theme, arg.ID)
	var i UpdateSiteThemeRow
	err := row.Scan(
		&i.ID,
		&i.CongregationUnitRid,
		&i.Slug,
		&i.Theme,
		&i.LogoUrl,
		&i.SocialLinks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
