// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package contentsql

import (
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type OpenfaithmapAuthzInstanceAdmin struct {
	ID        string
	PersonID  string
	GrantedBy pgtype.Text
	GrantedAt time.Time
	RevokedAt pgtype.Timestamptz
	RevokedBy pgtype.Text
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OpenfaithmapAuthzRole struct {
	ID          string
	Code        string
	Name        string
	Description pgtype.Text
	IsBase      bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   pgtype.Timestamptz
}

type OpenfaithmapAuthzRoleAssignment struct {
	ID              string
	SubjectPersonID string
	RoleID          string
	TargetUnitID    string
	Scope           string
	GraphID         pgtype.Text
	GrantedBy       pgtype.Text
	GrantedAt       time.Time
	RevokedAt       pgtype.Timestamptz
	RevokedBy       pgtype.Text
	ExpiresAt       pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type OpenfaithmapAuthzRolePermission struct {
	RoleID         string
	PermissionCode string
}

type OpenfaithmapCongregationimportCandidate struct {
	ID                             string
	ImportRunID                    pgtype.Text
	SourceCode                     string
	SourceRecordID                 string
	Name                           string
	TaxonHint                      pgtype.Text
	TaxonID                        pgtype.Text
	JurisdictionHint               pgtype.Text
	SuggestedJurisdictionUnitID    pgtype.Text
	CountryID                      pgtype.Text
	AdminArea1                     pgtype.Text
	Locality                       pgtype.Text
	Street                         pgtype.Text
	HouseNumber                    pgtype.Text
	PostalCode                     pgtype.Text
	Latitude                       pgtype.Float8
	Longitude                      pgtype.Float8
	GeocodePrecision               pgtype.Text
	RawPayload                     json.RawMessage
	Status                         string
	PossibleDuplicateOfCandidateID pgtype.Text
	PossibleDuplicateOfUnitID      pgtype.Text
	RejectionReason                pgtype.Text
	ReviewedByPersonRid            pgtype.Text
	ReviewedAt                     pgtype.Timestamptz
	CreatedUnitID                  pgtype.Text
	CreatedAt                      time.Time
	UpdatedAt                      time.Time
}

type OpenfaithmapCongregationimportCongregationStatus struct {
	CongregationUnitRid string
	SourceCode          string
	ImportCandidateID   pgtype.Text
	VerifiedByPersonRid string
	VerifiedAt          time.Time
	ClaimedByPersonRid  pgtype.Text
	ClaimedAt           pgtype.Timestamptz
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type OpenfaithmapCongregationimportConnectorCitation struct {
	ConnectorCode            string
	RobotsTxtUrl             pgtype.Text
	RobotsCheckedAt          pgtype.Timestamptz
	RobotsCheckedByPersonRid pgtype.Text
	TermsUrl                 pgtype.Text
	TermsCheckedAt           pgtype.Timestamptz
	UserAgent                string
	RateLimitNotes           pgtype.Text
	CitationNotes            string
	CreatedAt                time.Time
	UpdatedAt                time.Time
}

type OpenfaithmapCongregationimportJurisdictionAlias struct {
	ID                 string
	SourceCode         pgtype.Text
	AliasText          string
	JurisdictionUnitID string
	CreatedByPersonRid string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type OpenfaithmapCongregationimportJurisdictionUnit struct {
	ID               string
	SourceCode       string
	ExternalID       string
	ParentExternalID pgtype.Text
	Name             string
	OrgKindID        string
	Status           string
	CreatedUnitID    pgtype.Text
	FailureReason    pgtype.Text
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type OpenfaithmapCongregationimportRun struct {
	ID                     string
	SourceCode             string
	Status                 string
	TriggeredByPersonRid   string
	CursorAtStart          pgtype.Text
	CursorAtEnd            pgtype.Text
	RecordsFetched         int32
	CandidatesCreated      int32
	CandidatesUpdated      int32
	CandidatesAutoRejected int32
	Parameters             []byte
	Error                  pgtype.Text
	StartedAt              time.Time
	FinishedAt             pgtype.Timestamptz
}

type OpenfaithmapCongregationimportTaxonAlias struct {
	ID                 string
	SourceCode         pgtype.Text
	AliasText          string
	TaxonID            string
	CreatedByPersonRid string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

// Superseded by content_document_revisions as of M14.6 — no longer read or written. Left in place rather than dropped (data already migrated forward); a candidate for a future cleanup migration.
type OpenfaithmapContentBlock struct {
	ID          string
	DocumentID  string
	BlockTypeID string
	Position    int32
	Data        json.RawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   pgtype.Timestamptz
}

type OpenfaithmapContentBlockType struct {
	ID         string
	Code       string
	Name       string
	JsonSchema json.RawMessage
	Status     string
	SortOrder  int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  pgtype.Timestamptz
	UiSchema   json.RawMessage
}

type OpenfaithmapContentDocument struct {
	ID                   string
	SiteID               string
	Kind                 string
	TranslationGroupID   string
	Locale               string
	ParentDocumentID     pgtype.Text
	Slug                 string
	State                string
	PublishedAt          pgtype.Timestamptz
	EventStartsAt        pgtype.Timestamptz
	EventEndsAt          pgtype.Timestamptz
	EventRecurrenceRrule pgtype.Text
	CreatedAt            time.Time
	UpdatedAt            time.Time
	DeletedAt            pgtype.Timestamptz
	DraftRevisionID      pgtype.Text
	PublishedRevisionID  pgtype.Text
	PublishAt            pgtype.Timestamptz
	MetaTitle            pgtype.Text
	MetaDescription      pgtype.Text
}

type OpenfaithmapContentDocumentRevision struct {
	ID             string
	DocumentID     string
	RevisionNo     int32
	Data           json.RawMessage
	AuthorPersonID pgtype.Text
	CreatedAt      time.Time
	Label          pgtype.Text
}

type OpenfaithmapContentFormSubmission struct {
	ID        string
	SiteID    string
	Name      pgtype.Text
	Email     pgtype.Text
	Message   string
	CreatedAt time.Time
}

type OpenfaithmapContentPattern struct {
	ID          string
	Name        string
	Description string
	Blocks      json.RawMessage
	SortOrder   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   pgtype.Timestamptz
}

type OpenfaithmapContentSite struct {
	ID                  string
	CongregationUnitRid string
	Slug                string
	Theme               json.RawMessage
	CreatedAt           time.Time
	UpdatedAt           time.Time
	DeletedAt           pgtype.Timestamptz
	LogoUrl             pgtype.Text
	SocialLinks         json.RawMessage
}

type OpenfaithmapContentSiteNavItem struct {
	ID               string
	SiteID           string
	Label            string
	TargetDocumentID pgtype.Text
	TargetUrl        pgtype.Text
	SortOrder        int32
	CreatedAt        time.Time
}

type OpenfaithmapDirectoryClosureStatus struct {
	GraphID       string
	LastCheckedAt time.Time
	MissingCount  int32
	ExtraCount    int32
	InDrift       bool
	Sample        []byte
	UpdatedAt     time.Time
}

type OpenfaithmapDirectoryGraph struct {
	ID                 string
	Code               string
	Name               string
	IsDefault          bool
	IsAuthorityBearing bool
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          pgtype.Timestamptz
}

type OpenfaithmapDirectoryUnit struct {
	ID        string
	Code      pgtype.Text
	Name      string
	Level     pgtype.Int2
	State     string
	Metadata  json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt pgtype.Timestamptz
}

type OpenfaithmapDirectoryUnitClosure struct {
	GraphID      string
	AncestorID   string
	DescendantID string
	Depth        int32
}

type OpenfaithmapDirectoryUnitEdge struct {
	ID        string
	GraphID   string
	ParentID  string
	ChildID   string
	ValidFrom time.Time
	ValidTo   pgtype.Timestamptz
	CreatedAt time.Time
	CreatedBy pgtype.Text
}

type OpenfaithmapDirectoryUnitMoveJob struct {
	ID                  string
	GraphID             string
	UnitID              string
	OldParentUnitID     string
	NewParentUnitID     string
	Status              string
	PerformedByPersonID string
	Error               pgtype.Text
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type OpenfaithmapDiscoverySiteCache struct {
	ID                  string
	ReligionSiteRid     string
	CongregationUnitRid string
	ContentSiteID       pgtype.Text
	Latitude            pgtype.Numeric
	Longitude           pgtype.Numeric
	TraditionTaxonID    pgtype.Text
	ServiceLanguages    []string
	ServiceDays         []int16
	RefreshedAt         time.Time
	Name                string
	AddressLine         pgtype.Text
	TraditionTaxonCode  pgtype.Text
	TraditionTaxonName  pgtype.Text
	Attributes          json.RawMessage
}

type OpenfaithmapIdentityAccount struct {
	ID            string
	PersonID      string
	Email         pgtype.Text
	Status        string
	PasswordHash  pgtype.Text
	MfaEnrolledAt pgtype.Timestamptz
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     pgtype.Timestamptz
}

type OpenfaithmapIdentityApiKey struct {
	ID              string
	PersonID        string
	Label           string
	TokenHash       string
	PermissionCodes []string
	CreatedAt       time.Time
	LastUsedAt      pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
	RevokedBy       pgtype.Text
}

type OpenfaithmapIdentityAuditLog struct {
	ID            string
	ActorPersonID pgtype.Text
	Action        string
	TargetKind    string
	TargetID      string
	Before        []byte
	After         []byte
	CreatedAt     time.Time
}

type OpenfaithmapIdentityExternalIdentity struct {
	ID        string
	AccountID string
	Issuer    string
	Subject   string
	CreatedAt time.Time
}

type OpenfaithmapIdentityInvite struct {
	ID         string
	PersonID   string
	AccountID  string
	Email      string
	TokenHash  string
	Status     string
	InvitedBy  string
	ExpiresAt  time.Time
	CreatedAt  time.Time
	AcceptedAt pgtype.Timestamptz
}

type OpenfaithmapIdentityPerson struct {
	ID            string
	Code          pgtype.Text
	DisplayName   string
	Title         pgtype.Text
	Given         pgtype.Text
	Given2        pgtype.Text
	Surname       pgtype.Text
	SurnamePrefix pgtype.Text
	Surname2      pgtype.Text
	Generation    pgtype.Text
	Credentials   pgtype.Text
	Preferred     pgtype.Text
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     pgtype.Timestamptz
	SearchText    pgtype.Text
}

type OpenfaithmapIdentitySession struct {
	ID          string
	AccountID   string
	Issuer      string
	DeviceLabel pgtype.Text
	CreatedAt   time.Time
	LastSeenAt  time.Time
	RevokedAt   pgtype.Timestamptz
}

type OpenfaithmapJurisdictionReparentingJob struct {
	ID                    string
	RegistrationRequestID pgtype.Text
	CongregationUnitID    string
	OldParentUnitID       string
	NewParentUnitID       string
	Status                string
	PerformedByPersonID   string
	Error                 pgtype.Text
	CreatedAt             time.Time
	UpdatedAt             time.Time
}

type OpenfaithmapLocationLocation struct {
	ID               string
	Geom             interface{}
	Mgrs             pgtype.Text
	SourceCoordinate json.RawMessage
	CountryID        string
	AdminArea1       pgtype.Text
	AdminArea2       pgtype.Text
	Locality         pgtype.Text
	Street           pgtype.Text
	HouseNumber      pgtype.Text
	PostalCode       pgtype.Text
	RawAddress       pgtype.Text
	TypeID           pgtype.Text
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        pgtype.Timestamptz
}

type OpenfaithmapLocationLocationType struct {
	ID        string
	Code      string
	Name      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt pgtype.Timestamptz
}

type OpenfaithmapMembershipMembership struct {
	ID            string
	PersonID      string
	UnitID        string
	PositionID    pgtype.Text
	Status        string
	EffectiveFrom time.Time
	EffectiveTo   pgtype.Timestamptz
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     pgtype.Timestamptz
}

type OpenfaithmapMembershipPosition struct {
	ID        string
	UnitID    string
	Code      string
	Title     string
	Status    string
	SortOrder pgtype.Int4
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt pgtype.Timestamptz
}

type OpenfaithmapModerationAction struct {
	ID               string
	ReportID         pgtype.Text
	ActionKind       string
	TargetKind       string
	TargetRef        string
	ActorPersonID    string
	Reason           string
	ReversesActionID pgtype.Text
	CreatedAt        time.Time
}

type OpenfaithmapModerationAppeal struct {
	ID                        string
	ActionID                  string
	CongregationAdminPersonID string
	Statement                 string
	AssignedModeratorPersonID pgtype.Text
	Status                    string
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
}

type OpenfaithmapModerationReport struct {
	ID               string
	TargetKind       string
	TargetRef        string
	ReasonCode       string
	Detail           pgtype.Text
	ReporterPersonID pgtype.Text
	QueueScope       string
	Status           string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        pgtype.Timestamptz
}

type OpenfaithmapRefdataCountry struct {
	ID        string
	Code      string
	Name      string
	SortOrder pgtype.Int4
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OpenfaithmapRefdataCountryName struct {
	Code   string
	Locale string
	Name   string
}

type OpenfaithmapRegistrationRequest struct {
	ID                  string
	SubmittedByPersonID string
	TaxonID             string
	CongregationName    string
	CountryID           string
	AdminArea1          pgtype.Text
	Locality            pgtype.Text
	Street              pgtype.Text
	HouseNumber         pgtype.Text
	PostalCode          pgtype.Text
	Latitude            float64
	Longitude           float64
	Status              string
	RejectionReason     pgtype.Text
	DecidedByPersonID   pgtype.Text
	DecidedAt           pgtype.Timestamptz
	CreatedUnitID       pgtype.Text
	JurisdictionUnitID  pgtype.Text
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type OpenfaithmapReligionAlias struct {
	ID        string
	UnitID    string
	AliasText string
	AliasType string
	Locale    pgtype.Text
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt pgtype.Timestamptz
}

type OpenfaithmapReligionClassification struct {
	ID          string
	Code        string
	Name        string
	Description pgtype.Text
	Status      string
	SortOrder   pgtype.Int4
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   pgtype.Timestamptz
}

type OpenfaithmapReligionOrgClassification struct {
	ID         string
	UnitID     string
	TaxonID    string
	IsPrimary  bool
	Source     pgtype.Text
	Confidence pgtype.Text
	ValidFrom  time.Time
	ValidTo    pgtype.Timestamptz
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  pgtype.Timestamptz
}

type OpenfaithmapReligionOrgKind struct {
	ID         string
	ReligionID pgtype.Text
	Code       string
	Name       string
	Ordinal    pgtype.Int4
	Status     string
	SortOrder  pgtype.Int4
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  pgtype.Timestamptz
}

type OpenfaithmapReligionOrgPolicy struct {
	ID                string
	UnitID            string
	PolicyKindID      string
	Reason            pgtype.Text
	DecidedByPersonID pgtype.Text
	DecidedAt         pgtype.Timestamptz
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DeletedAt         pgtype.Timestamptz
}

type OpenfaithmapReligionOrgProfile struct {
	UnitID    string
	OrgKindID pgtype.Text
	ShortCode pgtype.Text
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt pgtype.Timestamptz
}

type OpenfaithmapReligionPolicyKind struct {
	ID          string
	Code        string
	Name        string
	Description pgtype.Text
	Status      string
	SortOrder   pgtype.Int4
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   pgtype.Timestamptz
}

type OpenfaithmapReligionServiceSchedule struct {
	ID            string
	SiteID        string
	ServiceTypeID string
	DayOfWeek     pgtype.Int2
	Rrule         pgtype.Text
	StartTime     pgtype.Time
	EndTime       pgtype.Time
	Timezone      string
	Language      pgtype.Text
	Mode          string
	MeetingUrl    pgtype.Text
	Description   pgtype.Text
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     pgtype.Timestamptz
}

type OpenfaithmapReligionServiceType struct {
	ID               string
	TraditionTaxonID pgtype.Text
	Code             string
	Name             string
	Status           string
	SortOrder        pgtype.Int4
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        pgtype.Timestamptz
}

type OpenfaithmapReligionSite struct {
	ID              string
	OrgUnitID       string
	LocationID      string
	SiteTypeID      string
	Visibility      string
	PublicPrecision string
	IsPrimary       bool
	ValidFrom       time.Time
	ValidTo         pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       pgtype.Timestamptz
	Attributes      json.RawMessage
}

type OpenfaithmapReligionSiteType struct {
	ID               string
	TraditionTaxonID pgtype.Text
	Code             string
	Name             string
	Status           string
	SortOrder        pgtype.Int4
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        pgtype.Timestamptz
}

type OpenfaithmapReligionTaxa struct {
	ID            string
	ParentID      pgtype.Text
	RankID        string
	ReligionID    pgtype.Text
	Code          string
	Name          string
	Description   pgtype.Text
	WikidataID    pgtype.Text
	Icon          pgtype.Text
	SortOrder     pgtype.Int4
	Source        pgtype.Text
	SourceVersion pgtype.Text
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     pgtype.Timestamptz
}

type OpenfaithmapReligionTaxaClosure struct {
	AncestorID   string
	DescendantID string
	Depth        int32
}

type OpenfaithmapReligionTaxonClassification struct {
	TaxonID          string
	ClassificationID string
	CreatedAt        time.Time
}

type OpenfaithmapReligionTaxonRank struct {
	ID        string
	Code      string
	Name      string
	Ordinal   int32
	Status    string
	SortOrder pgtype.Int4
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt pgtype.Timestamptz
}

type OpenfaithmapVouchingEdge struct {
	ID                  string
	GuarantorPersonRid  string
	ClaimantPersonRid   string
	CongregationUnitRid string
	Statement           pgtype.Text
	CreatedAt           time.Time
}

type OpenfaithmapVouchingGuarantorStatus struct {
	GuarantorPersonRid string
	Status             string
	RevokedAt          pgtype.Timestamptz
	RevokedReason      pgtype.Text
	RevokedByPersonRid pgtype.Text
	UpdatedAt          time.Time
}
