// Code generated by conjure-go. DO NOT EDIT.

package religion

import (
	"context"
	"fmt"
	"net/url"

	"github.com/olehmushka/open-faith-map/internal/conjure/internal/conjureerrors"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-client/httpclient"
	"github.com/palantir/pkg/bearertoken"
	werror "github.com/palantir/witchcraft-go-error"
)

// Authenticated congregation-admin/registration-operator surface over religion_sites — the physical/online presence a discovery search or a congregation's own admin form reads. site.manage-gated, target-scoped to each unit. See docs/modules/religion.md.
type ReligionServiceClient interface {
	// The unit's primary site, exact/uncoarsened (an owner's own private view, unlike discovery's public-precision-filtered projection). Throws SiteNotFound if the unit has no site yet.
	GetSite(ctx context.Context, authHeader bearertoken.Token, unitIdArg string) (Site, error)
	// Overwrites the unit's primary site's attributes wholesale (the admin form always submits the complete SiteAttributes shape, never a partial patch). Throws SiteNotFound if the unit has no site yet.
	UpdateSiteAttributes(ctx context.Context, authHeader bearertoken.Token, unitIdArg string, requestArg UpdateSiteAttributesRequest) (Site, error)
}

type religionServiceClient struct {
	client httpclient.Client
}

func NewReligionServiceClient(client httpclient.Client) ReligionServiceClient {
	return &religionServiceClient{client: client}
}

func (c *religionServiceClient) GetSite(ctx context.Context, authHeader bearertoken.Token, unitIdArg string) (Site, error) {
	var returnVal *Site
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("GetSite"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/religion/v1/units/%s/site", url.PathEscape(fmt.Sprint(unitIdArg))))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(Site), werror.WrapWithContextParams(ctx, err, "getSite failed")
	}
	if returnVal == nil {
		return *new(Site), werror.ErrorWithContextParams(ctx, "getSite response cannot be nil")
	}
	return *returnVal, nil
}

func (c *religionServiceClient) UpdateSiteAttributes(ctx context.Context, authHeader bearertoken.Token, unitIdArg string, requestArg UpdateSiteAttributesRequest) (Site, error) {
	var returnVal *Site
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("UpdateSiteAttributes"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/religion/v1/units/%s/site/attributes", url.PathEscape(fmt.Sprint(unitIdArg))))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Put(ctx, requestParams...); err != nil {
		return *new(Site), werror.WrapWithContextParams(ctx, err, "updateSiteAttributes failed")
	}
	if returnVal == nil {
		return *new(Site), werror.ErrorWithContextParams(ctx, "updateSiteAttributes response cannot be nil")
	}
	return *returnVal, nil
}

// Authenticated congregation-admin/registration-operator surface over religion_sites — the physical/online presence a discovery search or a congregation's own admin form reads. site.manage-gated, target-scoped to each unit. See docs/modules/religion.md.
type ReligionServiceClientWithAuth interface {
	// The unit's primary site, exact/uncoarsened (an owner's own private view, unlike discovery's public-precision-filtered projection). Throws SiteNotFound if the unit has no site yet.
	GetSite(ctx context.Context, unitIdArg string) (Site, error)
	// Overwrites the unit's primary site's attributes wholesale (the admin form always submits the complete SiteAttributes shape, never a partial patch). Throws SiteNotFound if the unit has no site yet.
	UpdateSiteAttributes(ctx context.Context, unitIdArg string, requestArg UpdateSiteAttributesRequest) (Site, error)
}

func NewReligionServiceClientWithAuth(client ReligionServiceClient, authHeader bearertoken.Token) ReligionServiceClientWithAuth {
	return &religionServiceClientWithAuth{client: client, authHeader: authHeader}
}

type religionServiceClientWithAuth struct {
	client     ReligionServiceClient
	authHeader bearertoken.Token
}

func (c *religionServiceClientWithAuth) GetSite(ctx context.Context, unitIdArg string) (Site, error) {
	return c.client.GetSite(ctx, c.authHeader, unitIdArg)
}

func (c *religionServiceClientWithAuth) UpdateSiteAttributes(ctx context.Context, unitIdArg string, requestArg UpdateSiteAttributesRequest) (Site, error) {
	return c.client.UpdateSiteAttributes(ctx, c.authHeader, unitIdArg, requestArg)
}

func NewReligionServiceClientWithTokenProvider(client ReligionServiceClient, tokenProvider httpclient.TokenProvider) ReligionServiceClientWithAuth {
	return &religionServiceClientWithTokenProvider{client: client, tokenProvider: tokenProvider}
}

type religionServiceClientWithTokenProvider struct {
	client        ReligionServiceClient
	tokenProvider httpclient.TokenProvider
}

func (c *religionServiceClientWithTokenProvider) GetSite(ctx context.Context, unitIdArg string) (Site, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(Site), err
	}
	return c.client.GetSite(ctx, bearertoken.Token(token), unitIdArg)
}

func (c *religionServiceClientWithTokenProvider) UpdateSiteAttributes(ctx context.Context, unitIdArg string, requestArg UpdateSiteAttributesRequest) (Site, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(Site), err
	}
	return c.client.UpdateSiteAttributes(ctx, bearertoken.Token(token), unitIdArg, requestArg)
}
