-- 0014_core_refdata — M10.1 (D-StaticRefData). Country reference data as two static seed
-- tables, replacing both go-oikumenea's geo_countries (which itself just wraps an ISO-3166-1
-- alpha-2 seed with no locale names of its own) and hermenea's country mapper + weekly cron
-- entirely. Extracted directly from the live running stack's oikumenea.geo_countries /
-- oikumenea.i18n_translations (entity_type='country') rather than reconstructed from a
-- migration file, because go-oikumenea's own migrations do not seed locale names for
-- countries at all (confirmed by grep: no 'country'-entity_type INSERT anywhere in
-- ../go-oikumenea/migrations/*.sql) — the per-locale names only exist because hermenea's
-- 'geo-countries-iso3166' source wrote them at runtime, on this instance, after M2.2's import.
--
-- Fidelity constraint (D-StaticRefData's amendment): matchCountry
-- (internal/congregationimport/application/countrymatch.go) does exact-string comparison
-- against every locale name, and osm's CountryHint is built to match these exact strings —
-- so the values below are a direct, unedited extraction, not retyped by hand.

CREATE TABLE openfaithmap.refdata_countries (
  id         uuid PRIMARY KEY DEFAULT openfaithmap.new_id(7,1,1),  -- refdata / object / country
  code       char(2) NOT NULL UNIQUE,  -- ISO-3166-1 alpha-2, the canonical external reference
  name       text NOT NULL,             -- English name (matches the source's default/eng column)
  sort_order integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT refdata_countries_rid_shape
    CHECK (openfaithmap.rid_service(id)=7 AND openfaithmap.rid_kind(id)=1 AND openfaithmap.rid_type(id)=1)
);
CREATE TRIGGER refdata_countries_set_updated_at
  BEFORE UPDATE ON openfaithmap.refdata_countries
  FOR EACH ROW EXECUTE FUNCTION openfaithmap.set_updated_at();

-- refdata_country_names: flat (code, locale, name) — no RID, a lookup table over
-- refdata_countries.code, not a reified entity. Four locales: en/es/pt/uk.
CREATE TABLE openfaithmap.refdata_country_names (
  code   char(2) NOT NULL REFERENCES openfaithmap.refdata_countries(code) ON DELETE CASCADE,
  locale text NOT NULL CHECK (locale IN ('eng','spa','por','ukr')),
  name   text NOT NULL,
  PRIMARY KEY (code, locale)
);
CREATE INDEX refdata_country_names_locale_idx ON openfaithmap.refdata_country_names (locale);

INSERT INTO openfaithmap.refdata_countries (code, name, sort_order) VALUES
  ('AD', 'Andorra', 0),
  ('AE', 'United Arab Emirates', 10),
  ('AF', 'Afghanistan', 20),
  ('AG', 'Antigua and Barbuda', 30),
  ('AI', 'Anguilla', 40),
  ('AL', 'Albania', 50),
  ('AM', 'Armenia', 60),
  ('AO', 'Angola', 70),
  ('AQ', 'Antarctica', 80),
  ('AR', 'Argentina', 90),
  ('AS', 'American Samoa', 100),
  ('AT', 'Austria', 110),
  ('AU', 'Australia', 120),
  ('AW', 'Aruba', 130),
  ('AX', 'Åland Islands', 140),
  ('AZ', 'Azerbaijan', 150),
  ('BA', 'Bosnia and Herzegovina', 160),
  ('BB', 'Barbados', 170),
  ('BD', 'Bangladesh', 180),
  ('BE', 'Belgium', 190),
  ('BF', 'Burkina Faso', 200),
  ('BG', 'Bulgaria', 210),
  ('BH', 'Bahrain', 220),
  ('BI', 'Burundi', 230),
  ('BJ', 'Benin', 240),
  ('BL', 'Saint Barthélemy', 250),
  ('BM', 'Bermuda', 260),
  ('BN', 'Brunei Darussalam', 270),
  ('BO', 'Bolivia', 280),
  ('BQ', 'Bonaire, Sint Eustatius and Saba', 290),
  ('BR', 'Brazil', 300),
  ('BS', 'Bahamas', 310),
  ('BT', 'Bhutan', 320),
  ('BV', 'Bouvet Island', 330),
  ('BW', 'Botswana', 340),
  ('BY', 'Belarus', 350),
  ('BZ', 'Belize', 360),
  ('CA', 'Canada', 370),
  ('CC', 'Cocos (Keeling) Islands', 380),
  ('CD', 'Congo, The Democratic Republic of the', 390),
  ('CF', 'Central African Republic', 400),
  ('CG', 'Congo', 410),
  ('CH', 'Switzerland', 420),
  ('CI', 'Côte d''Ivoire', 430),
  ('CK', 'Cook Islands', 440),
  ('CL', 'Chile', 450),
  ('CM', 'Cameroon', 460),
  ('CN', 'China', 470),
  ('CO', 'Colombia', 480),
  ('CR', 'Costa Rica', 490),
  ('CU', 'Cuba', 500),
  ('CV', 'Cabo Verde', 510),
  ('CW', 'Curaçao', 520),
  ('CX', 'Christmas Island', 530),
  ('CY', 'Cyprus', 540),
  ('CZ', 'Czechia', 550),
  ('DE', 'Germany', 560),
  ('DJ', 'Djibouti', 570),
  ('DK', 'Denmark', 580),
  ('DM', 'Dominica', 590),
  ('DO', 'Dominican Republic', 600),
  ('DZ', 'Algeria', 610),
  ('EC', 'Ecuador', 620),
  ('EE', 'Estonia', 630),
  ('EG', 'Egypt', 640),
  ('EH', 'Western Sahara', 650),
  ('ER', 'Eritrea', 660),
  ('ES', 'Spain', 670),
  ('ET', 'Ethiopia', 680),
  ('FI', 'Finland', 690),
  ('FJ', 'Fiji', 700),
  ('FK', 'Falkland Islands (Malvinas)', 710),
  ('FM', 'Micronesia, Federated States of', 720),
  ('FO', 'Faroe Islands', 730),
  ('FR', 'France', 740),
  ('GA', 'Gabon', 750),
  ('GB', 'United Kingdom', 760),
  ('GD', 'Grenada', 770),
  ('GE', 'Georgia', 780),
  ('GF', 'French Guiana', 790),
  ('GG', 'Guernsey', 800),
  ('GH', 'Ghana', 810),
  ('GI', 'Gibraltar', 820),
  ('GL', 'Greenland', 830),
  ('GM', 'Gambia', 840),
  ('GN', 'Guinea', 850),
  ('GP', 'Guadeloupe', 860),
  ('GQ', 'Equatorial Guinea', 870),
  ('GR', 'Greece', 880),
  ('GS', 'South Georgia and the South Sandwich Islands', 890),
  ('GT', 'Guatemala', 900),
  ('GU', 'Guam', 910),
  ('GW', 'Guinea-Bissau', 920),
  ('GY', 'Guyana', 930),
  ('HK', 'Hong Kong', 940),
  ('HM', 'Heard Island and McDonald Islands', 950),
  ('HN', 'Honduras', 960),
  ('HR', 'Croatia', 970),
  ('HT', 'Haiti', 980),
  ('HU', 'Hungary', 990),
  ('ID', 'Indonesia', 1000),
  ('IE', 'Ireland', 1010),
  ('IL', 'Israel', 1020),
  ('IM', 'Isle of Man', 1030),
  ('IN', 'India', 1040),
  ('IO', 'British Indian Ocean Territory', 1050),
  ('IQ', 'Iraq', 1060),
  ('IR', 'Iran', 1070),
  ('IS', 'Iceland', 1080),
  ('IT', 'Italy', 1090),
  ('JE', 'Jersey', 1100),
  ('JM', 'Jamaica', 1110),
  ('JO', 'Jordan', 1120),
  ('JP', 'Japan', 1130),
  ('KE', 'Kenya', 1140),
  ('KG', 'Kyrgyzstan', 1150),
  ('KH', 'Cambodia', 1160),
  ('KI', 'Kiribati', 1170),
  ('KM', 'Comoros', 1180),
  ('KN', 'Saint Kitts and Nevis', 1190),
  ('KP', 'North Korea', 1200),
  ('KR', 'Korea, Republic of', 1210),
  ('KW', 'Kuwait', 1220),
  ('KY', 'Cayman Islands', 1230),
  ('KZ', 'Kazakhstan', 1240),
  ('LA', 'Laos', 1250),
  ('LB', 'Lebanon', 1260),
  ('LC', 'Saint Lucia', 1270),
  ('LI', 'Liechtenstein', 1280),
  ('LK', 'Sri Lanka', 1290),
  ('LR', 'Liberia', 1300),
  ('LS', 'Lesotho', 1310),
  ('LT', 'Lithuania', 1320),
  ('LU', 'Luxembourg', 1330),
  ('LV', 'Latvia', 1340),
  ('LY', 'Libya', 1350),
  ('MA', 'Morocco', 1360),
  ('MC', 'Monaco', 1370),
  ('MD', 'Moldova, Republic of', 1380),
  ('ME', 'Montenegro', 1390),
  ('MF', 'Saint Martin (French part)', 1400),
  ('MG', 'Madagascar', 1410),
  ('MH', 'Marshall Islands', 1420),
  ('MK', 'North Macedonia', 1430),
  ('ML', 'Mali', 1440),
  ('MM', 'Myanmar', 1450),
  ('MN', 'Mongolia', 1460),
  ('MO', 'Macao', 1470),
  ('MP', 'Northern Mariana Islands', 1480),
  ('MQ', 'Martinique', 1490),
  ('MR', 'Mauritania', 1500),
  ('MS', 'Montserrat', 1510),
  ('MT', 'Malta', 1520),
  ('MU', 'Mauritius', 1530),
  ('MV', 'Maldives', 1540),
  ('MW', 'Malawi', 1550),
  ('MX', 'Mexico', 1560),
  ('MY', 'Malaysia', 1570),
  ('MZ', 'Mozambique', 1580),
  ('NA', 'Namibia', 1590),
  ('NC', 'New Caledonia', 1600),
  ('NE', 'Niger', 1610),
  ('NF', 'Norfolk Island', 1620),
  ('NG', 'Nigeria', 1630),
  ('NI', 'Nicaragua', 1640),
  ('NL', 'Netherlands', 1650),
  ('NO', 'Norway', 1660),
  ('NP', 'Nepal', 1670),
  ('NR', 'Nauru', 1680),
  ('NU', 'Niue', 1690),
  ('NZ', 'New Zealand', 1700),
  ('OM', 'Oman', 1710),
  ('PA', 'Panama', 1720),
  ('PE', 'Peru', 1730),
  ('PF', 'French Polynesia', 1740),
  ('PG', 'Papua New Guinea', 1750),
  ('PH', 'Philippines', 1760),
  ('PK', 'Pakistan', 1770),
  ('PL', 'Poland', 1780),
  ('PM', 'Saint Pierre and Miquelon', 1790),
  ('PN', 'Pitcairn', 1800),
  ('PR', 'Puerto Rico', 1810),
  ('PS', 'Palestine, State of', 1820),
  ('PT', 'Portugal', 1830),
  ('PW', 'Palau', 1840),
  ('PY', 'Paraguay', 1850),
  ('QA', 'Qatar', 1860),
  ('RE', 'Réunion', 1870),
  ('RO', 'Romania', 1880),
  ('RS', 'Serbia', 1890),
  ('RU', 'Russian Federation', 1900),
  ('RW', 'Rwanda', 1910),
  ('SA', 'Saudi Arabia', 1920),
  ('SB', 'Solomon Islands', 1930),
  ('SC', 'Seychelles', 1940),
  ('SD', 'Sudan', 1950),
  ('SE', 'Sweden', 1960),
  ('SG', 'Singapore', 1970),
  ('SH', 'Saint Helena, Ascension and Tristan da Cunha', 1980),
  ('SI', 'Slovenia', 1990),
  ('SJ', 'Svalbard and Jan Mayen', 2000),
  ('SK', 'Slovakia', 2010),
  ('SL', 'Sierra Leone', 2020),
  ('SM', 'San Marino', 2030),
  ('SN', 'Senegal', 2040),
  ('SO', 'Somalia', 2050),
  ('SR', 'Suriname', 2060),
  ('SS', 'South Sudan', 2070),
  ('ST', 'Sao Tome and Principe', 2080),
  ('SV', 'El Salvador', 2090),
  ('SX', 'Sint Maarten (Dutch part)', 2100),
  ('SY', 'Syria', 2110),
  ('SZ', 'Eswatini', 2120),
  ('TC', 'Turks and Caicos Islands', 2130),
  ('TD', 'Chad', 2140),
  ('TF', 'French Southern Territories', 2150),
  ('TG', 'Togo', 2160),
  ('TH', 'Thailand', 2170),
  ('TJ', 'Tajikistan', 2180),
  ('TK', 'Tokelau', 2190),
  ('TL', 'Timor-Leste', 2200),
  ('TM', 'Turkmenistan', 2210),
  ('TN', 'Tunisia', 2220),
  ('TO', 'Tonga', 2230),
  ('TR', 'Türkiye', 2240),
  ('TT', 'Trinidad and Tobago', 2250),
  ('TV', 'Tuvalu', 2260),
  ('TW', 'Taiwan', 2270),
  ('TZ', 'Tanzania', 2280),
  ('UA', 'Ukraine', 2290),
  ('UG', 'Uganda', 2300),
  ('UM', 'United States Minor Outlying Islands', 2310),
  ('US', 'United States', 2320),
  ('UY', 'Uruguay', 2330),
  ('UZ', 'Uzbekistan', 2340),
  ('VA', 'Holy See (Vatican City State)', 2350),
  ('VC', 'Saint Vincent and the Grenadines', 2360),
  ('VE', 'Venezuela', 2370),
  ('VG', 'Virgin Islands, British', 2380),
  ('VI', 'Virgin Islands, U.S.', 2390),
  ('VN', 'Vietnam', 2400),
  ('VU', 'Vanuatu', 2410),
  ('WF', 'Wallis and Futuna', 2420),
  ('WS', 'Samoa', 2430),
  ('YE', 'Yemen', 2440),
  ('YT', 'Mayotte', 2450),
  ('ZA', 'South Africa', 2460),
  ('ZM', 'Zambia', 2470),
  ('ZW', 'Zimbabwe', 2480),
  ('XK', 'Kosovo', NULL);

INSERT INTO openfaithmap.refdata_country_names (code, locale, name) VALUES
  ('AD', 'eng', 'Andorra'),
  ('AD', 'por', 'Andorra'),
  ('AD', 'spa', 'Andorra'),
  ('AD', 'ukr', 'Андорра'),
  ('AE', 'eng', 'United Arab Emirates'),
  ('AE', 'por', 'Emirados Árabes Unidos'),
  ('AE', 'spa', 'Emiratos Árabes Unidos'),
  ('AE', 'ukr', 'Обʼєднані Арабські Емірати'),
  ('AF', 'eng', 'Afghanistan'),
  ('AF', 'por', 'Afeganistão'),
  ('AF', 'spa', 'Afganistán'),
  ('AF', 'ukr', 'Афганістан'),
  ('AG', 'eng', 'Antigua & Barbuda'),
  ('AG', 'por', 'Antígua e Barbuda'),
  ('AG', 'spa', 'Antigua y Barbuda'),
  ('AG', 'ukr', 'Антигуа і Барбуда'),
  ('AI', 'eng', 'Anguilla'),
  ('AI', 'por', 'Anguila'),
  ('AI', 'spa', 'Anguila'),
  ('AI', 'ukr', 'Ангілья'),
  ('AL', 'eng', 'Albania'),
  ('AL', 'por', 'Albânia'),
  ('AL', 'spa', 'Albania'),
  ('AL', 'ukr', 'Албанія'),
  ('AM', 'eng', 'Armenia'),
  ('AM', 'por', 'Armênia'),
  ('AM', 'spa', 'Armenia'),
  ('AM', 'ukr', 'Вірменія'),
  ('AO', 'eng', 'Angola'),
  ('AO', 'por', 'Angola'),
  ('AO', 'spa', 'Angola'),
  ('AO', 'ukr', 'Ангола'),
  ('AQ', 'eng', 'Antarctica'),
  ('AQ', 'por', 'Antártida'),
  ('AQ', 'spa', 'Antártida'),
  ('AQ', 'ukr', 'Антарктика'),
  ('AR', 'eng', 'Argentina'),
  ('AR', 'por', 'Argentina'),
  ('AR', 'spa', 'Argentina'),
  ('AR', 'ukr', 'Аргентина'),
  ('AS', 'eng', 'American Samoa'),
  ('AS', 'por', 'Samoa Americana'),
  ('AS', 'spa', 'Samoa Americana'),
  ('AS', 'ukr', 'Американське Самоа'),
  ('AT', 'eng', 'Austria'),
  ('AT', 'por', 'Áustria'),
  ('AT', 'spa', 'Austria'),
  ('AT', 'ukr', 'Австрія'),
  ('AU', 'eng', 'Australia'),
  ('AU', 'por', 'Austrália'),
  ('AU', 'spa', 'Australia'),
  ('AU', 'ukr', 'Австралія'),
  ('AW', 'eng', 'Aruba'),
  ('AW', 'por', 'Aruba'),
  ('AW', 'spa', 'Aruba'),
  ('AW', 'ukr', 'Аруба'),
  ('AX', 'eng', 'Åland Islands'),
  ('AX', 'por', 'Ilhas Aland'),
  ('AX', 'spa', 'Islas Åland'),
  ('AX', 'ukr', 'Аландські Острови'),
  ('AZ', 'eng', 'Azerbaijan'),
  ('AZ', 'por', 'Azerbaijão'),
  ('AZ', 'spa', 'Azerbaiyán'),
  ('AZ', 'ukr', 'Азербайджан'),
  ('BA', 'eng', 'Bosnia & Herzegovina'),
  ('BA', 'por', 'Bósnia e Herzegovina'),
  ('BA', 'spa', 'Bosnia-Herzegovina'),
  ('BA', 'ukr', 'Боснія і Герцеговина'),
  ('BB', 'eng', 'Barbados'),
  ('BB', 'por', 'Barbados'),
  ('BB', 'spa', 'Barbados'),
  ('BB', 'ukr', 'Барбадос'),
  ('BD', 'eng', 'Bangladesh'),
  ('BD', 'por', 'Bangladesh'),
  ('BD', 'spa', 'Bangladés'),
  ('BD', 'ukr', 'Бангладеш'),
  ('BE', 'eng', 'Belgium'),
  ('BE', 'por', 'Bélgica'),
  ('BE', 'spa', 'Bélgica'),
  ('BE', 'ukr', 'Бельгія'),
  ('BF', 'eng', 'Burkina Faso'),
  ('BF', 'por', 'Burquina Faso'),
  ('BF', 'spa', 'Burkina Faso'),
  ('BF', 'ukr', 'Буркіна-Фасо'),
  ('BG', 'eng', 'Bulgaria'),
  ('BG', 'por', 'Bulgária'),
  ('BG', 'spa', 'Bulgaria'),
  ('BG', 'ukr', 'Болгарія'),
  ('BH', 'eng', 'Bahrain'),
  ('BH', 'por', 'Barein'),
  ('BH', 'spa', 'Baréin'),
  ('BH', 'ukr', 'Бахрейн'),
  ('BI', 'eng', 'Burundi'),
  ('BI', 'por', 'Burundi'),
  ('BI', 'spa', 'Burundi'),
  ('BI', 'ukr', 'Бурунді'),
  ('BJ', 'eng', 'Benin'),
  ('BJ', 'por', 'Benin'),
  ('BJ', 'spa', 'Benín'),
  ('BJ', 'ukr', 'Бенін'),
  ('BL', 'eng', 'St. Barthélemy'),
  ('BL', 'por', 'São Bartolomeu'),
  ('BL', 'spa', 'San Bartolomé'),
  ('BL', 'ukr', 'Сен-Бартелемі'),
  ('BM', 'eng', 'Bermuda'),
  ('BM', 'por', 'Bermudas'),
  ('BM', 'spa', 'Bermudas'),
  ('BM', 'ukr', 'Бермудські Острови'),
  ('BN', 'eng', 'Brunei'),
  ('BN', 'por', 'Brunei'),
  ('BN', 'spa', 'Brunéi'),
  ('BN', 'ukr', 'Бруней'),
  ('BO', 'eng', 'Bolivia'),
  ('BO', 'por', 'Bolívia'),
  ('BO', 'spa', 'Bolivia'),
  ('BO', 'ukr', 'Болівія'),
  ('BQ', 'eng', 'Caribbean Netherlands'),
  ('BQ', 'por', 'Países Baixos Caribenhos'),
  ('BQ', 'spa', 'Caribe neerlandés'),
  ('BQ', 'ukr', 'Карибські Нідерланди'),
  ('BR', 'eng', 'Brazil'),
  ('BR', 'por', 'Brasil'),
  ('BR', 'spa', 'Brasil'),
  ('BR', 'ukr', 'Бразилія'),
  ('BS', 'eng', 'Bahamas'),
  ('BS', 'por', 'Bahamas'),
  ('BS', 'spa', 'Bahamas'),
  ('BS', 'ukr', 'Багамські Острови'),
  ('BT', 'eng', 'Bhutan'),
  ('BT', 'por', 'Butão'),
  ('BT', 'spa', 'Bután'),
  ('BT', 'ukr', 'Бутан'),
  ('BV', 'eng', 'Bouvet Island'),
  ('BV', 'por', 'Ilha Bouvet'),
  ('BV', 'spa', 'Isla Bouvet'),
  ('BV', 'ukr', 'Острів Буве'),
  ('BW', 'eng', 'Botswana'),
  ('BW', 'por', 'Botsuana'),
  ('BW', 'spa', 'Botsuana'),
  ('BW', 'ukr', 'Ботсвана'),
  ('BY', 'eng', 'Belarus'),
  ('BY', 'por', 'Bielorrússia'),
  ('BY', 'spa', 'Bielorrusia'),
  ('BY', 'ukr', 'Білорусь'),
  ('BZ', 'eng', 'Belize'),
  ('BZ', 'por', 'Belize'),
  ('BZ', 'spa', 'Belice'),
  ('BZ', 'ukr', 'Беліз'),
  ('CA', 'eng', 'Canada'),
  ('CA', 'por', 'Canadá'),
  ('CA', 'spa', 'Canadá'),
  ('CA', 'ukr', 'Канада'),
  ('CC', 'eng', 'Cocos (Keeling) Islands'),
  ('CC', 'por', 'Ilhas Cocos (Keeling)'),
  ('CC', 'spa', 'Islas Cocos'),
  ('CC', 'ukr', 'Кокосові (Кілінг) Острови'),
  ('CD', 'eng', 'Congo - Kinshasa'),
  ('CD', 'por', 'Congo - Kinshasa'),
  ('CD', 'spa', 'República Democrática del Congo'),
  ('CD', 'ukr', 'Конго – Кіншаса'),
  ('CF', 'eng', 'Central African Republic'),
  ('CF', 'por', 'República Centro-Africana'),
  ('CF', 'spa', 'República Centroafricana'),
  ('CF', 'ukr', 'Центральноафриканська Республіка'),
  ('CG', 'eng', 'Congo - Brazzaville'),
  ('CG', 'por', 'República do Congo'),
  ('CG', 'spa', 'República del Congo'),
  ('CG', 'ukr', 'Конго – Браззавіль'),
  ('CH', 'eng', 'Switzerland'),
  ('CH', 'por', 'Suíça'),
  ('CH', 'spa', 'Suiza'),
  ('CH', 'ukr', 'Швейцарія'),
  ('CI', 'eng', 'Côte d’Ivoire'),
  ('CI', 'por', 'Costa do Marfim'),
  ('CI', 'spa', 'Costa de Marfil'),
  ('CI', 'ukr', 'Кот-дʼІвуар'),
  ('CK', 'eng', 'Cook Islands'),
  ('CK', 'por', 'Ilhas Cook'),
  ('CK', 'spa', 'Islas Cook'),
  ('CK', 'ukr', 'Острови Кука'),
  ('CL', 'eng', 'Chile'),
  ('CL', 'por', 'Chile'),
  ('CL', 'spa', 'Chile'),
  ('CL', 'ukr', 'Чилі'),
  ('CM', 'eng', 'Cameroon'),
  ('CM', 'por', 'Camarões'),
  ('CM', 'spa', 'Camerún'),
  ('CM', 'ukr', 'Камерун'),
  ('CN', 'eng', 'China'),
  ('CN', 'por', 'China'),
  ('CN', 'spa', 'China'),
  ('CN', 'ukr', 'Китай'),
  ('CO', 'eng', 'Colombia'),
  ('CO', 'por', 'Colômbia'),
  ('CO', 'spa', 'Colombia'),
  ('CO', 'ukr', 'Колумбія'),
  ('CR', 'eng', 'Costa Rica'),
  ('CR', 'por', 'Costa Rica'),
  ('CR', 'spa', 'Costa Rica'),
  ('CR', 'ukr', 'Коста-Рика'),
  ('CU', 'eng', 'Cuba'),
  ('CU', 'por', 'Cuba'),
  ('CU', 'spa', 'Cuba'),
  ('CU', 'ukr', 'Куба'),
  ('CV', 'eng', 'Cape Verde'),
  ('CV', 'por', 'Cabo Verde'),
  ('CV', 'spa', 'Cabo Verde'),
  ('CV', 'ukr', 'Кабо-Верде'),
  ('CW', 'eng', 'Curaçao'),
  ('CW', 'por', 'Curaçao'),
  ('CW', 'spa', 'Curazao'),
  ('CW', 'ukr', 'Кюрасао'),
  ('CX', 'eng', 'Christmas Island'),
  ('CX', 'por', 'Ilha Christmas'),
  ('CX', 'spa', 'Isla de Navidad'),
  ('CX', 'ukr', 'Острів Різдва'),
  ('CY', 'eng', 'Cyprus'),
  ('CY', 'por', 'Chipre'),
  ('CY', 'spa', 'Chipre'),
  ('CY', 'ukr', 'Кіпр'),
  ('CZ', 'eng', 'Czechia'),
  ('CZ', 'por', 'Tchéquia'),
  ('CZ', 'spa', 'Chequia'),
  ('CZ', 'ukr', 'Чехія'),
  ('DE', 'eng', 'Germany'),
  ('DE', 'por', 'Alemanha'),
  ('DE', 'spa', 'Alemania'),
  ('DE', 'ukr', 'Німеччина'),
  ('DJ', 'eng', 'Djibouti'),
  ('DJ', 'por', 'Djibuti'),
  ('DJ', 'spa', 'Yibuti'),
  ('DJ', 'ukr', 'Джибуті'),
  ('DK', 'eng', 'Denmark'),
  ('DK', 'por', 'Dinamarca'),
  ('DK', 'spa', 'Dinamarca'),
  ('DK', 'ukr', 'Данія'),
  ('DM', 'eng', 'Dominica'),
  ('DM', 'por', 'Dominica'),
  ('DM', 'spa', 'Dominica'),
  ('DM', 'ukr', 'Домініка'),
  ('DO', 'eng', 'Dominican Republic'),
  ('DO', 'por', 'República Dominicana'),
  ('DO', 'spa', 'República Dominicana'),
  ('DO', 'ukr', 'Домініканська Республіка'),
  ('DZ', 'eng', 'Algeria'),
  ('DZ', 'por', 'Argélia'),
  ('DZ', 'spa', 'Argelia'),
  ('DZ', 'ukr', 'Алжир'),
  ('EC', 'eng', 'Ecuador'),
  ('EC', 'por', 'Equador'),
  ('EC', 'spa', 'Ecuador'),
  ('EC', 'ukr', 'Еквадор'),
  ('EE', 'eng', 'Estonia'),
  ('EE', 'por', 'Estônia'),
  ('EE', 'spa', 'Estonia'),
  ('EE', 'ukr', 'Естонія'),
  ('EG', 'eng', 'Egypt'),
  ('EG', 'por', 'Egito'),
  ('EG', 'spa', 'Egipto'),
  ('EG', 'ukr', 'Єгипет'),
  ('EH', 'eng', 'Western Sahara'),
  ('EH', 'por', 'Saara Ocidental'),
  ('EH', 'spa', 'Sáhara Occidental'),
  ('EH', 'ukr', 'Західна Сахара'),
  ('ER', 'eng', 'Eritrea'),
  ('ER', 'por', 'Eritreia'),
  ('ER', 'spa', 'Eritrea'),
  ('ER', 'ukr', 'Еритрея'),
  ('ES', 'eng', 'Spain'),
  ('ES', 'por', 'Espanha'),
  ('ES', 'spa', 'España'),
  ('ES', 'ukr', 'Іспанія'),
  ('ET', 'eng', 'Ethiopia'),
  ('ET', 'por', 'Etiópia'),
  ('ET', 'spa', 'Etiopía'),
  ('ET', 'ukr', 'Ефіопія'),
  ('FI', 'eng', 'Finland'),
  ('FI', 'por', 'Finlândia'),
  ('FI', 'spa', 'Finlandia'),
  ('FI', 'ukr', 'Фінляндія'),
  ('FJ', 'eng', 'Fiji'),
  ('FJ', 'por', 'Fiji'),
  ('FJ', 'spa', 'Fiyi'),
  ('FJ', 'ukr', 'Фіджі'),
  ('FK', 'eng', 'Falkland Islands'),
  ('FK', 'por', 'Ilhas Malvinas'),
  ('FK', 'spa', 'Islas Malvinas'),
  ('FK', 'ukr', 'Фолклендські Острови'),
  ('FM', 'eng', 'Micronesia'),
  ('FM', 'por', 'Micronésia'),
  ('FM', 'spa', 'Micronesia'),
  ('FM', 'ukr', 'Мікронезія'),
  ('FO', 'eng', 'Faroe Islands'),
  ('FO', 'por', 'Ilhas Faroé'),
  ('FO', 'spa', 'Islas Feroe'),
  ('FO', 'ukr', 'Фарерські Острови'),
  ('FR', 'eng', 'France'),
  ('FR', 'por', 'França'),
  ('FR', 'spa', 'Francia'),
  ('FR', 'ukr', 'Франція'),
  ('GA', 'eng', 'Gabon'),
  ('GA', 'por', 'Gabão'),
  ('GA', 'spa', 'Gabón'),
  ('GA', 'ukr', 'Габон'),
  ('GB', 'eng', 'United Kingdom'),
  ('GB', 'por', 'Reino Unido'),
  ('GB', 'spa', 'Reino Unido'),
  ('GB', 'ukr', 'Велика Британія'),
  ('GD', 'eng', 'Grenada'),
  ('GD', 'por', 'Granada'),
  ('GD', 'spa', 'Granada'),
  ('GD', 'ukr', 'Гренада'),
  ('GE', 'eng', 'Georgia'),
  ('GE', 'por', 'Geórgia'),
  ('GE', 'spa', 'Georgia'),
  ('GE', 'ukr', 'Грузія'),
  ('GF', 'eng', 'French Guiana'),
  ('GF', 'por', 'Guiana Francesa'),
  ('GF', 'spa', 'Guayana Francesa'),
  ('GF', 'ukr', 'Французька Гвіана'),
  ('GG', 'eng', 'Guernsey'),
  ('GG', 'por', 'Guernsey'),
  ('GG', 'spa', 'Guernesey'),
  ('GG', 'ukr', 'Гернсі'),
  ('GH', 'eng', 'Ghana'),
  ('GH', 'por', 'Gana'),
  ('GH', 'spa', 'Ghana'),
  ('GH', 'ukr', 'Гана'),
  ('GI', 'eng', 'Gibraltar'),
  ('GI', 'por', 'Gibraltar'),
  ('GI', 'spa', 'Gibraltar'),
  ('GI', 'ukr', 'Гібралтар'),
  ('GL', 'eng', 'Greenland'),
  ('GL', 'por', 'Groenlândia'),
  ('GL', 'spa', 'Groenlandia'),
  ('GL', 'ukr', 'Гренландія'),
  ('GM', 'eng', 'Gambia'),
  ('GM', 'por', 'Gâmbia'),
  ('GM', 'spa', 'Gambia'),
  ('GM', 'ukr', 'Гамбія'),
  ('GN', 'eng', 'Guinea'),
  ('GN', 'por', 'Guiné'),
  ('GN', 'spa', 'Guinea'),
  ('GN', 'ukr', 'Гвінея'),
  ('GP', 'eng', 'Guadeloupe'),
  ('GP', 'por', 'Guadalupe'),
  ('GP', 'spa', 'Guadalupe'),
  ('GP', 'ukr', 'Гваделупа'),
  ('GQ', 'eng', 'Equatorial Guinea'),
  ('GQ', 'por', 'Guiné Equatorial'),
  ('GQ', 'spa', 'Guinea Ecuatorial'),
  ('GQ', 'ukr', 'Екваторіальна Гвінея'),
  ('GR', 'eng', 'Greece'),
  ('GR', 'por', 'Grécia'),
  ('GR', 'spa', 'Grecia'),
  ('GR', 'ukr', 'Греція'),
  ('GS', 'eng', 'South Georgia & South Sandwich Islands'),
  ('GS', 'por', 'Ilhas Geórgia do Sul e Sandwich do Sul'),
  ('GS', 'spa', 'Islas Georgia del Sur y Sándwich del Sur'),
  ('GS', 'ukr', 'Південна Джорджія та Південні Сандвічеві Острови'),
  ('GT', 'eng', 'Guatemala'),
  ('GT', 'por', 'Guatemala'),
  ('GT', 'spa', 'Guatemala'),
  ('GT', 'ukr', 'Гватемала'),
  ('GU', 'eng', 'Guam'),
  ('GU', 'por', 'Guam'),
  ('GU', 'spa', 'Guam'),
  ('GU', 'ukr', 'Гуам'),
  ('GW', 'eng', 'Guinea-Bissau'),
  ('GW', 'por', 'Guiné-Bissau'),
  ('GW', 'spa', 'Guinea-Bisáu'),
  ('GW', 'ukr', 'Гвінея-Бісау'),
  ('GY', 'eng', 'Guyana'),
  ('GY', 'por', 'Guiana'),
  ('GY', 'spa', 'Guyana'),
  ('GY', 'ukr', 'Гаяна'),
  ('HK', 'eng', 'Hong Kong SAR China'),
  ('HK', 'por', 'Hong Kong, RAE da China'),
  ('HK', 'spa', 'RAE de Hong Kong (China)'),
  ('HK', 'ukr', 'Гонконг, ОАР Китаю'),
  ('HM', 'eng', 'Heard & McDonald Islands'),
  ('HM', 'por', 'Ilhas Heard e McDonald'),
  ('HM', 'spa', 'Islas Heard y McDonald'),
  ('HM', 'ukr', 'Острови Герд і Макдоналд'),
  ('HN', 'eng', 'Honduras'),
  ('HN', 'por', 'Honduras'),
  ('HN', 'spa', 'Honduras'),
  ('HN', 'ukr', 'Гондурас'),
  ('HR', 'eng', 'Croatia'),
  ('HR', 'por', 'Croácia'),
  ('HR', 'spa', 'Croacia'),
  ('HR', 'ukr', 'Хорватія'),
  ('HT', 'eng', 'Haiti'),
  ('HT', 'por', 'Haiti'),
  ('HT', 'spa', 'Haití'),
  ('HT', 'ukr', 'Гаїті'),
  ('HU', 'eng', 'Hungary'),
  ('HU', 'por', 'Hungria'),
  ('HU', 'spa', 'Hungría'),
  ('HU', 'ukr', 'Угорщина'),
  ('ID', 'eng', 'Indonesia'),
  ('ID', 'por', 'Indonésia'),
  ('ID', 'spa', 'Indonesia'),
  ('ID', 'ukr', 'Індонезія'),
  ('IE', 'eng', 'Ireland'),
  ('IE', 'por', 'Irlanda'),
  ('IE', 'spa', 'Irlanda'),
  ('IE', 'ukr', 'Ірландія'),
  ('IL', 'eng', 'Israel'),
  ('IL', 'por', 'Israel'),
  ('IL', 'spa', 'Israel'),
  ('IL', 'ukr', 'Ізраїль'),
  ('IM', 'eng', 'Isle of Man'),
  ('IM', 'por', 'Ilha de Man'),
  ('IM', 'spa', 'Isla de Man'),
  ('IM', 'ukr', 'Острів Мен'),
  ('IN', 'eng', 'India'),
  ('IN', 'por', 'Índia'),
  ('IN', 'spa', 'India'),
  ('IN', 'ukr', 'Індія'),
  ('IO', 'eng', 'British Indian Ocean Territory'),
  ('IO', 'por', 'Território Britânico do Oceano Índico'),
  ('IO', 'spa', 'Territorio Británico del Océano Índico'),
  ('IO', 'ukr', 'Британська територія в Індійському океані'),
  ('IQ', 'eng', 'Iraq'),
  ('IQ', 'por', 'Iraque'),
  ('IQ', 'spa', 'Irak'),
  ('IQ', 'ukr', 'Ірак'),
  ('IR', 'eng', 'Iran'),
  ('IR', 'por', 'Irã'),
  ('IR', 'spa', 'Irán'),
  ('IR', 'ukr', 'Іран'),
  ('IS', 'eng', 'Iceland'),
  ('IS', 'por', 'Islândia'),
  ('IS', 'spa', 'Islandia'),
  ('IS', 'ukr', 'Ісландія'),
  ('IT', 'eng', 'Italy'),
  ('IT', 'por', 'Itália'),
  ('IT', 'spa', 'Italia'),
  ('IT', 'ukr', 'Італія'),
  ('JE', 'eng', 'Jersey'),
  ('JE', 'por', 'Jersey'),
  ('JE', 'spa', 'Jersey'),
  ('JE', 'ukr', 'Джерсі'),
  ('JM', 'eng', 'Jamaica'),
  ('JM', 'por', 'Jamaica'),
  ('JM', 'spa', 'Jamaica'),
  ('JM', 'ukr', 'Ямайка'),
  ('JO', 'eng', 'Jordan'),
  ('JO', 'por', 'Jordânia'),
  ('JO', 'spa', 'Jordania'),
  ('JO', 'ukr', 'Йорданія'),
  ('JP', 'eng', 'Japan'),
  ('JP', 'por', 'Japão'),
  ('JP', 'spa', 'Japón'),
  ('JP', 'ukr', 'Японія'),
  ('KE', 'eng', 'Kenya'),
  ('KE', 'por', 'Quênia'),
  ('KE', 'spa', 'Kenia'),
  ('KE', 'ukr', 'Кенія'),
  ('KG', 'eng', 'Kyrgyzstan'),
  ('KG', 'por', 'Quirguistão'),
  ('KG', 'spa', 'Kirguistán'),
  ('KG', 'ukr', 'Киргизстан'),
  ('KH', 'eng', 'Cambodia'),
  ('KH', 'por', 'Camboja'),
  ('KH', 'spa', 'Camboya'),
  ('KH', 'ukr', 'Камбоджа'),
  ('KI', 'eng', 'Kiribati'),
  ('KI', 'por', 'Quiribati'),
  ('KI', 'spa', 'Kiribati'),
  ('KI', 'ukr', 'Кірибаті'),
  ('KM', 'eng', 'Comoros'),
  ('KM', 'por', 'Comores'),
  ('KM', 'spa', 'Comoras'),
  ('KM', 'ukr', 'Комори'),
  ('KN', 'eng', 'St. Kitts & Nevis'),
  ('KN', 'por', 'São Cristóvão e Névis'),
  ('KN', 'spa', 'San Cristóbal y Nieves'),
  ('KN', 'ukr', 'Сент-Кітс і Невіс'),
  ('KP', 'eng', 'North Korea'),
  ('KP', 'por', 'Coreia do Norte'),
  ('KP', 'spa', 'Corea del Norte'),
  ('KP', 'ukr', 'Північна Корея'),
  ('KR', 'eng', 'South Korea'),
  ('KR', 'por', 'Coreia do Sul'),
  ('KR', 'spa', 'Corea del Sur'),
  ('KR', 'ukr', 'Південна Корея'),
  ('KW', 'eng', 'Kuwait'),
  ('KW', 'por', 'Kuwait'),
  ('KW', 'spa', 'Kuwait'),
  ('KW', 'ukr', 'Кувейт'),
  ('KY', 'eng', 'Cayman Islands'),
  ('KY', 'por', 'Ilhas Cayman'),
  ('KY', 'spa', 'Islas Caimán'),
  ('KY', 'ukr', 'Кайманові Острови'),
  ('KZ', 'eng', 'Kazakhstan'),
  ('KZ', 'por', 'Cazaquistão'),
  ('KZ', 'spa', 'Kazajistán'),
  ('KZ', 'ukr', 'Казахстан'),
  ('LA', 'eng', 'Laos'),
  ('LA', 'por', 'Laos'),
  ('LA', 'spa', 'Laos'),
  ('LA', 'ukr', 'Лаос'),
  ('LB', 'eng', 'Lebanon'),
  ('LB', 'por', 'Líbano'),
  ('LB', 'spa', 'Líbano'),
  ('LB', 'ukr', 'Ліван'),
  ('LC', 'eng', 'St. Lucia'),
  ('LC', 'por', 'Santa Lúcia'),
  ('LC', 'spa', 'Santa Lucía'),
  ('LC', 'ukr', 'Сент-Люсія'),
  ('LI', 'eng', 'Liechtenstein'),
  ('LI', 'por', 'Liechtenstein'),
  ('LI', 'spa', 'Liechtenstein'),
  ('LI', 'ukr', 'Ліхтенштейн'),
  ('LK', 'eng', 'Sri Lanka'),
  ('LK', 'por', 'Sri Lanka'),
  ('LK', 'spa', 'Sri Lanka'),
  ('LK', 'ukr', 'Шрі-Ланка'),
  ('LR', 'eng', 'Liberia'),
  ('LR', 'por', 'Libéria'),
  ('LR', 'spa', 'Liberia'),
  ('LR', 'ukr', 'Ліберія'),
  ('LS', 'eng', 'Lesotho'),
  ('LS', 'por', 'Lesoto'),
  ('LS', 'spa', 'Lesoto'),
  ('LS', 'ukr', 'Лесото'),
  ('LT', 'eng', 'Lithuania'),
  ('LT', 'por', 'Lituânia'),
  ('LT', 'spa', 'Lituania'),
  ('LT', 'ukr', 'Литва'),
  ('LU', 'eng', 'Luxembourg'),
  ('LU', 'por', 'Luxemburgo'),
  ('LU', 'spa', 'Luxemburgo'),
  ('LU', 'ukr', 'Люксембург'),
  ('LV', 'eng', 'Latvia'),
  ('LV', 'por', 'Letônia'),
  ('LV', 'spa', 'Letonia'),
  ('LV', 'ukr', 'Латвія'),
  ('LY', 'eng', 'Libya'),
  ('LY', 'por', 'Líbia'),
  ('LY', 'spa', 'Libia'),
  ('LY', 'ukr', 'Лівія'),
  ('MA', 'eng', 'Morocco'),
  ('MA', 'por', 'Marrocos'),
  ('MA', 'spa', 'Marruecos'),
  ('MA', 'ukr', 'Марокко'),
  ('MC', 'eng', 'Monaco'),
  ('MC', 'por', 'Mônaco'),
  ('MC', 'spa', 'Mónaco'),
  ('MC', 'ukr', 'Монако'),
  ('MD', 'eng', 'Moldova'),
  ('MD', 'por', 'Moldávia'),
  ('MD', 'spa', 'Moldavia'),
  ('MD', 'ukr', 'Молдова'),
  ('ME', 'eng', 'Montenegro'),
  ('ME', 'por', 'Montenegro'),
  ('ME', 'spa', 'Montenegro'),
  ('ME', 'ukr', 'Чорногорія'),
  ('MF', 'eng', 'St. Martin'),
  ('MF', 'por', 'São Martinho'),
  ('MF', 'spa', 'San Martín'),
  ('MF', 'ukr', 'Сен-Мартен'),
  ('MG', 'eng', 'Madagascar'),
  ('MG', 'por', 'Madagascar'),
  ('MG', 'spa', 'Madagascar'),
  ('MG', 'ukr', 'Мадагаскар'),
  ('MH', 'eng', 'Marshall Islands'),
  ('MH', 'por', 'Ilhas Marshall'),
  ('MH', 'spa', 'Islas Marshall'),
  ('MH', 'ukr', 'Маршаллові Острови'),
  ('MK', 'eng', 'North Macedonia'),
  ('MK', 'por', 'Macedônia do Norte'),
  ('MK', 'spa', 'Macedonia del Norte'),
  ('MK', 'ukr', 'Північна Македонія'),
  ('ML', 'eng', 'Mali'),
  ('ML', 'por', 'Mali'),
  ('ML', 'spa', 'Mali'),
  ('ML', 'ukr', 'Малі'),
  ('MM', 'eng', 'Myanmar (Burma)'),
  ('MM', 'por', 'Mianmar (Birmânia)'),
  ('MM', 'spa', 'Myanmar (Birmania)'),
  ('MM', 'ukr', 'Мʼянма (Бірма)'),
  ('MN', 'eng', 'Mongolia'),
  ('MN', 'por', 'Mongólia'),
  ('MN', 'spa', 'Mongolia'),
  ('MN', 'ukr', 'Монголія'),
  ('MO', 'eng', 'Macao SAR China'),
  ('MO', 'por', 'Macau, RAE da China'),
  ('MO', 'spa', 'RAE de Macao (China)'),
  ('MO', 'ukr', 'Макао, ОАР Китаю'),
  ('MP', 'eng', 'Northern Mariana Islands'),
  ('MP', 'por', 'Ilhas Marianas do Norte'),
  ('MP', 'spa', 'Islas Marianas del Norte'),
  ('MP', 'ukr', 'Північні Маріанські Острови'),
  ('MQ', 'eng', 'Martinique'),
  ('MQ', 'por', 'Martinica'),
  ('MQ', 'spa', 'Martinica'),
  ('MQ', 'ukr', 'Мартиніка'),
  ('MR', 'eng', 'Mauritania'),
  ('MR', 'por', 'Mauritânia'),
  ('MR', 'spa', 'Mauritania'),
  ('MR', 'ukr', 'Мавританія'),
  ('MS', 'eng', 'Montserrat'),
  ('MS', 'por', 'Montserrat'),
  ('MS', 'spa', 'Montserrat'),
  ('MS', 'ukr', 'Монтсеррат'),
  ('MT', 'eng', 'Malta'),
  ('MT', 'por', 'Malta'),
  ('MT', 'spa', 'Malta'),
  ('MT', 'ukr', 'Мальта'),
  ('MU', 'eng', 'Mauritius'),
  ('MU', 'por', 'Maurício'),
  ('MU', 'spa', 'Mauricio'),
  ('MU', 'ukr', 'Маврикій'),
  ('MV', 'eng', 'Maldives'),
  ('MV', 'por', 'Maldivas'),
  ('MV', 'spa', 'Maldivas'),
  ('MV', 'ukr', 'Мальдіви'),
  ('MW', 'eng', 'Malawi'),
  ('MW', 'por', 'Malaui'),
  ('MW', 'spa', 'Malaui'),
  ('MW', 'ukr', 'Малаві'),
  ('MX', 'eng', 'Mexico'),
  ('MX', 'por', 'México'),
  ('MX', 'spa', 'México'),
  ('MX', 'ukr', 'Мексика'),
  ('MY', 'eng', 'Malaysia'),
  ('MY', 'por', 'Malásia'),
  ('MY', 'spa', 'Malasia'),
  ('MY', 'ukr', 'Малайзія'),
  ('MZ', 'eng', 'Mozambique'),
  ('MZ', 'por', 'Moçambique'),
  ('MZ', 'spa', 'Mozambique'),
  ('MZ', 'ukr', 'Мозамбік'),
  ('NA', 'eng', 'Namibia'),
  ('NA', 'por', 'Namíbia'),
  ('NA', 'spa', 'Namibia'),
  ('NA', 'ukr', 'Намібія'),
  ('NC', 'eng', 'New Caledonia'),
  ('NC', 'por', 'Nova Caledônia'),
  ('NC', 'spa', 'Nueva Caledonia'),
  ('NC', 'ukr', 'Нова Каледонія'),
  ('NE', 'eng', 'Niger'),
  ('NE', 'por', 'Níger'),
  ('NE', 'spa', 'Níger'),
  ('NE', 'ukr', 'Нігер'),
  ('NF', 'eng', 'Norfolk Island'),
  ('NF', 'por', 'Ilha Norfolk'),
  ('NF', 'spa', 'Isla Norfolk'),
  ('NF', 'ukr', 'Острів Норфолк'),
  ('NG', 'eng', 'Nigeria'),
  ('NG', 'por', 'Nigéria'),
  ('NG', 'spa', 'Nigeria'),
  ('NG', 'ukr', 'Нігерія'),
  ('NI', 'eng', 'Nicaragua'),
  ('NI', 'por', 'Nicarágua'),
  ('NI', 'spa', 'Nicaragua'),
  ('NI', 'ukr', 'Нікарагуа'),
  ('NL', 'eng', 'Netherlands'),
  ('NL', 'por', 'Países Baixos'),
  ('NL', 'spa', 'Países Bajos'),
  ('NL', 'ukr', 'Нідерланди'),
  ('NO', 'eng', 'Norway'),
  ('NO', 'por', 'Noruega'),
  ('NO', 'spa', 'Noruega'),
  ('NO', 'ukr', 'Норвегія'),
  ('NP', 'eng', 'Nepal'),
  ('NP', 'por', 'Nepal'),
  ('NP', 'spa', 'Nepal'),
  ('NP', 'ukr', 'Непал'),
  ('NR', 'eng', 'Nauru'),
  ('NR', 'por', 'Nauru'),
  ('NR', 'spa', 'Nauru'),
  ('NR', 'ukr', 'Науру'),
  ('NU', 'eng', 'Niue'),
  ('NU', 'por', 'Niue'),
  ('NU', 'spa', 'Niue'),
  ('NU', 'ukr', 'Ніуе'),
  ('NZ', 'eng', 'New Zealand'),
  ('NZ', 'por', 'Nova Zelândia'),
  ('NZ', 'spa', 'Nueva Zelanda'),
  ('NZ', 'ukr', 'Нова Зеландія'),
  ('OM', 'eng', 'Oman'),
  ('OM', 'por', 'Omã'),
  ('OM', 'spa', 'Omán'),
  ('OM', 'ukr', 'Оман'),
  ('PA', 'eng', 'Panama'),
  ('PA', 'por', 'Panamá'),
  ('PA', 'spa', 'Panamá'),
  ('PA', 'ukr', 'Панама'),
  ('PE', 'eng', 'Peru'),
  ('PE', 'por', 'Peru'),
  ('PE', 'spa', 'Perú'),
  ('PE', 'ukr', 'Перу'),
  ('PF', 'eng', 'French Polynesia'),
  ('PF', 'por', 'Polinésia Francesa'),
  ('PF', 'spa', 'Polinesia Francesa'),
  ('PF', 'ukr', 'Французька Полінезія'),
  ('PG', 'eng', 'Papua New Guinea'),
  ('PG', 'por', 'Papua-Nova Guiné'),
  ('PG', 'spa', 'Papúa Nueva Guinea'),
  ('PG', 'ukr', 'Папуа-Нова Гвінея'),
  ('PH', 'eng', 'Philippines'),
  ('PH', 'por', 'Filipinas'),
  ('PH', 'spa', 'Filipinas'),
  ('PH', 'ukr', 'Філіппіни'),
  ('PK', 'eng', 'Pakistan'),
  ('PK', 'por', 'Paquistão'),
  ('PK', 'spa', 'Pakistán'),
  ('PK', 'ukr', 'Пакистан'),
  ('PL', 'eng', 'Poland'),
  ('PL', 'por', 'Polônia'),
  ('PL', 'spa', 'Polonia'),
  ('PL', 'ukr', 'Польща'),
  ('PM', 'eng', 'St. Pierre & Miquelon'),
  ('PM', 'por', 'São Pedro e Miquelão'),
  ('PM', 'spa', 'San Pedro y Miquelón'),
  ('PM', 'ukr', 'Сен-Пʼєр і Мікелон'),
  ('PN', 'eng', 'Pitcairn Islands'),
  ('PN', 'por', 'Ilhas Pitcairn'),
  ('PN', 'spa', 'Islas Pitcairn'),
  ('PN', 'ukr', 'Острови Піткерн'),
  ('PR', 'eng', 'Puerto Rico'),
  ('PR', 'por', 'Porto Rico'),
  ('PR', 'spa', 'Puerto Rico'),
  ('PR', 'ukr', 'Пуерто-Рико'),
  ('PS', 'eng', 'Palestinian Territories'),
  ('PS', 'por', 'Territórios palestinos'),
  ('PS', 'spa', 'Territorios Palestinos'),
  ('PS', 'ukr', 'Палестинські території'),
  ('PT', 'eng', 'Portugal'),
  ('PT', 'por', 'Portugal'),
  ('PT', 'spa', 'Portugal'),
  ('PT', 'ukr', 'Португалія'),
  ('PW', 'eng', 'Palau'),
  ('PW', 'por', 'Palau'),
  ('PW', 'spa', 'Palaos'),
  ('PW', 'ukr', 'Палау'),
  ('PY', 'eng', 'Paraguay'),
  ('PY', 'por', 'Paraguai'),
  ('PY', 'spa', 'Paraguay'),
  ('PY', 'ukr', 'Парагвай'),
  ('QA', 'eng', 'Qatar'),
  ('QA', 'por', 'Catar'),
  ('QA', 'spa', 'Catar'),
  ('QA', 'ukr', 'Катар'),
  ('RE', 'eng', 'Réunion'),
  ('RE', 'por', 'Reunião'),
  ('RE', 'spa', 'Reunión'),
  ('RE', 'ukr', 'Реюньйон'),
  ('RO', 'eng', 'Romania'),
  ('RO', 'por', 'Romênia'),
  ('RO', 'spa', 'Rumania'),
  ('RO', 'ukr', 'Румунія'),
  ('RS', 'eng', 'Serbia'),
  ('RS', 'por', 'Sérvia'),
  ('RS', 'spa', 'Serbia'),
  ('RS', 'ukr', 'Сербія'),
  ('RU', 'eng', 'Russia'),
  ('RU', 'por', 'Rússia'),
  ('RU', 'spa', 'Rusia'),
  ('RU', 'ukr', 'Росія'),
  ('RW', 'eng', 'Rwanda'),
  ('RW', 'por', 'Ruanda'),
  ('RW', 'spa', 'Ruanda'),
  ('RW', 'ukr', 'Руанда'),
  ('SA', 'eng', 'Saudi Arabia'),
  ('SA', 'por', 'Arábia Saudita'),
  ('SA', 'spa', 'Arabia Saudita'),
  ('SA', 'ukr', 'Саудівська Аравія'),
  ('SB', 'eng', 'Solomon Islands'),
  ('SB', 'por', 'Ilhas Salomão'),
  ('SB', 'spa', 'Islas Salomón'),
  ('SB', 'ukr', 'Соломонові Острови'),
  ('SC', 'eng', 'Seychelles'),
  ('SC', 'por', 'Seicheles'),
  ('SC', 'spa', 'Seychelles'),
  ('SC', 'ukr', 'Сейшельські Острови'),
  ('SD', 'eng', 'Sudan'),
  ('SD', 'por', 'Sudão'),
  ('SD', 'spa', 'Sudán'),
  ('SD', 'ukr', 'Судан'),
  ('SE', 'eng', 'Sweden'),
  ('SE', 'por', 'Suécia'),
  ('SE', 'spa', 'Suecia'),
  ('SE', 'ukr', 'Швеція'),
  ('SG', 'eng', 'Singapore'),
  ('SG', 'por', 'Singapura'),
  ('SG', 'spa', 'Singapur'),
  ('SG', 'ukr', 'Сінгапур'),
  ('SH', 'eng', 'St. Helena'),
  ('SH', 'por', 'Santa Helena'),
  ('SH', 'spa', 'Santa Elena'),
  ('SH', 'ukr', 'Острів Святої Єлени'),
  ('SI', 'eng', 'Slovenia'),
  ('SI', 'por', 'Eslovênia'),
  ('SI', 'spa', 'Eslovenia'),
  ('SI', 'ukr', 'Словенія'),
  ('SJ', 'eng', 'Svalbard & Jan Mayen'),
  ('SJ', 'por', 'Svalbard e Jan Mayen'),
  ('SJ', 'spa', 'Svalbard y Jan Mayen'),
  ('SJ', 'ukr', 'Шпіцберген та Ян-Маєн'),
  ('SK', 'eng', 'Slovakia'),
  ('SK', 'por', 'Eslováquia'),
  ('SK', 'spa', 'Eslovaquia'),
  ('SK', 'ukr', 'Словаччина'),
  ('SL', 'eng', 'Sierra Leone'),
  ('SL', 'por', 'Serra Leoa'),
  ('SL', 'spa', 'Sierra Leona'),
  ('SL', 'ukr', 'Сьєрра-Леоне'),
  ('SM', 'eng', 'San Marino'),
  ('SM', 'por', 'San Marino'),
  ('SM', 'spa', 'San Marino'),
  ('SM', 'ukr', 'Сан-Марино'),
  ('SN', 'eng', 'Senegal'),
  ('SN', 'por', 'Senegal'),
  ('SN', 'spa', 'Senegal'),
  ('SN', 'ukr', 'Сенегал'),
  ('SO', 'eng', 'Somalia'),
  ('SO', 'por', 'Somália'),
  ('SO', 'spa', 'Somalia'),
  ('SO', 'ukr', 'Сомалі'),
  ('SR', 'eng', 'Suriname'),
  ('SR', 'por', 'Suriname'),
  ('SR', 'spa', 'Surinam'),
  ('SR', 'ukr', 'Суринам'),
  ('SS', 'eng', 'South Sudan'),
  ('SS', 'por', 'Sudão do Sul'),
  ('SS', 'spa', 'Sudán del Sur'),
  ('SS', 'ukr', 'Південний Судан'),
  ('ST', 'eng', 'São Tomé & Príncipe'),
  ('ST', 'por', 'São Tomé e Príncipe'),
  ('ST', 'spa', 'Santo Tomé y Príncipe'),
  ('ST', 'ukr', 'Сан-Томе і Принсіпі'),
  ('SV', 'eng', 'El Salvador'),
  ('SV', 'por', 'El Salvador'),
  ('SV', 'spa', 'El Salvador'),
  ('SV', 'ukr', 'Сальвадор'),
  ('SX', 'eng', 'Sint Maarten'),
  ('SX', 'por', 'Sint Maarten'),
  ('SX', 'spa', 'Sint Maarten'),
  ('SX', 'ukr', 'Сінт-Мартен'),
  ('SY', 'eng', 'Syria'),
  ('SY', 'por', 'Síria'),
  ('SY', 'spa', 'Siria'),
  ('SY', 'ukr', 'Сирія'),
  ('SZ', 'eng', 'Eswatini'),
  ('SZ', 'por', 'Essuatíni'),
  ('SZ', 'spa', 'Esuatini'),
  ('SZ', 'ukr', 'Есватіні'),
  ('TC', 'eng', 'Turks & Caicos Islands'),
  ('TC', 'por', 'Ilhas Turcas e Caicos'),
  ('TC', 'spa', 'Islas Turcas y Caicos'),
  ('TC', 'ukr', 'Острови Теркс і Кайкос'),
  ('TD', 'eng', 'Chad'),
  ('TD', 'por', 'Chade'),
  ('TD', 'spa', 'Chad'),
  ('TD', 'ukr', 'Чад'),
  ('TF', 'eng', 'French Southern Territories'),
  ('TF', 'por', 'Territórios Franceses do Sul'),
  ('TF', 'spa', 'Territorios Australes Franceses'),
  ('TF', 'ukr', 'Французькі Південні Території'),
  ('TG', 'eng', 'Togo'),
  ('TG', 'por', 'Togo'),
  ('TG', 'spa', 'Togo'),
  ('TG', 'ukr', 'Того'),
  ('TH', 'eng', 'Thailand'),
  ('TH', 'por', 'Tailândia'),
  ('TH', 'spa', 'Tailandia'),
  ('TH', 'ukr', 'Таїланд'),
  ('TJ', 'eng', 'Tajikistan'),
  ('TJ', 'por', 'Tadjiquistão'),
  ('TJ', 'spa', 'Tayikistán'),
  ('TJ', 'ukr', 'Таджикистан'),
  ('TK', 'eng', 'Tokelau'),
  ('TK', 'por', 'Tokelau'),
  ('TK', 'spa', 'Tokelau'),
  ('TK', 'ukr', 'Токелау'),
  ('TL', 'eng', 'Timor-Leste'),
  ('TL', 'por', 'Timor-Leste'),
  ('TL', 'spa', 'Timor Oriental'),
  ('TL', 'ukr', 'Тимор-Лешті'),
  ('TM', 'eng', 'Turkmenistan'),
  ('TM', 'por', 'Turcomenistão'),
  ('TM', 'spa', 'Turkmenistán'),
  ('TM', 'ukr', 'Туркменістан'),
  ('TN', 'eng', 'Tunisia'),
  ('TN', 'por', 'Tunísia'),
  ('TN', 'spa', 'Túnez'),
  ('TN', 'ukr', 'Туніс'),
  ('TO', 'eng', 'Tonga'),
  ('TO', 'por', 'Tonga'),
  ('TO', 'spa', 'Tonga'),
  ('TO', 'ukr', 'Тонга'),
  ('TR', 'eng', 'Türkiye'),
  ('TR', 'por', 'Turquia'),
  ('TR', 'spa', 'Turquía'),
  ('TR', 'ukr', 'Туреччина'),
  ('TT', 'eng', 'Trinidad & Tobago'),
  ('TT', 'por', 'Trinidad e Tobago'),
  ('TT', 'spa', 'Trinidad y Tobago'),
  ('TT', 'ukr', 'Тринідад і Тобаго'),
  ('TV', 'eng', 'Tuvalu'),
  ('TV', 'por', 'Tuvalu'),
  ('TV', 'spa', 'Tuvalu'),
  ('TV', 'ukr', 'Тувалу'),
  ('TW', 'eng', 'Taiwan'),
  ('TW', 'por', 'Taiwan'),
  ('TW', 'spa', 'Taiwán'),
  ('TW', 'ukr', 'Тайвань'),
  ('TZ', 'eng', 'Tanzania'),
  ('TZ', 'por', 'Tanzânia'),
  ('TZ', 'spa', 'Tanzania'),
  ('TZ', 'ukr', 'Танзанія'),
  ('UA', 'eng', 'Ukraine'),
  ('UA', 'por', 'Ucrânia'),
  ('UA', 'spa', 'Ucrania'),
  ('UA', 'ukr', 'Україна'),
  ('UG', 'eng', 'Uganda'),
  ('UG', 'por', 'Uganda'),
  ('UG', 'spa', 'Uganda'),
  ('UG', 'ukr', 'Уганда'),
  ('UM', 'eng', 'U.S. Outlying Islands'),
  ('UM', 'por', 'Ilhas Menores Distantes dos EUA'),
  ('UM', 'spa', 'Islas Ultramarinas de EE.UU.'),
  ('UM', 'ukr', 'Віддалені острови США'),
  ('US', 'eng', 'United States'),
  ('US', 'por', 'Estados Unidos'),
  ('US', 'spa', 'Estados Unidos'),
  ('US', 'ukr', 'Сполучені Штати'),
  ('UY', 'eng', 'Uruguay'),
  ('UY', 'por', 'Uruguai'),
  ('UY', 'spa', 'Uruguay'),
  ('UY', 'ukr', 'Уругвай'),
  ('UZ', 'eng', 'Uzbekistan'),
  ('UZ', 'por', 'Uzbequistão'),
  ('UZ', 'spa', 'Uzbekistán'),
  ('UZ', 'ukr', 'Узбекистан'),
  ('VA', 'eng', 'Vatican City'),
  ('VA', 'por', 'Cidade do Vaticano'),
  ('VA', 'spa', 'Ciudad del Vaticano'),
  ('VA', 'ukr', 'Ватикан'),
  ('VC', 'eng', 'St. Vincent & Grenadines'),
  ('VC', 'por', 'São Vicente e Granadinas'),
  ('VC', 'spa', 'San Vicente y las Granadinas'),
  ('VC', 'ukr', 'Сент-Вінсент і Гренадіни'),
  ('VE', 'eng', 'Venezuela'),
  ('VE', 'por', 'Venezuela'),
  ('VE', 'spa', 'Venezuela'),
  ('VE', 'ukr', 'Венесуела'),
  ('VG', 'eng', 'British Virgin Islands'),
  ('VG', 'por', 'Ilhas Virgens Britânicas'),
  ('VG', 'spa', 'Islas Vírgenes Británicas'),
  ('VG', 'ukr', 'Британські Віргінські острови'),
  ('VI', 'eng', 'U.S. Virgin Islands'),
  ('VI', 'por', 'Ilhas Virgens Americanas'),
  ('VI', 'spa', 'Islas Vírgenes de EE. UU.'),
  ('VI', 'ukr', 'Віргінські Острови (США)'),
  ('VN', 'eng', 'Vietnam'),
  ('VN', 'por', 'Vietnã'),
  ('VN', 'spa', 'Vietnam'),
  ('VN', 'ukr', 'Вʼєтнам'),
  ('VU', 'eng', 'Vanuatu'),
  ('VU', 'por', 'Vanuatu'),
  ('VU', 'spa', 'Vanuatu'),
  ('VU', 'ukr', 'Вануату'),
  ('WF', 'eng', 'Wallis & Futuna'),
  ('WF', 'por', 'Wallis e Futuna'),
  ('WF', 'spa', 'Wallis y Futuna'),
  ('WF', 'ukr', 'Уолліс і Футуна'),
  ('WS', 'eng', 'Samoa'),
  ('WS', 'por', 'Samoa'),
  ('WS', 'spa', 'Samoa'),
  ('WS', 'ukr', 'Самоа'),
  ('XK', 'eng', 'Kosovo'),
  ('XK', 'por', 'Kosovo'),
  ('XK', 'spa', 'Kosovo'),
  ('XK', 'ukr', 'Косово'),
  ('YE', 'eng', 'Yemen'),
  ('YE', 'por', 'Iêmen'),
  ('YE', 'spa', 'Yemen'),
  ('YE', 'ukr', 'Ємен'),
  ('YT', 'eng', 'Mayotte'),
  ('YT', 'por', 'Mayotte'),
  ('YT', 'spa', 'Mayotte'),
  ('YT', 'ukr', 'Майотта'),
  ('ZA', 'eng', 'South Africa'),
  ('ZA', 'por', 'África do Sul'),
  ('ZA', 'spa', 'Sudáfrica'),
  ('ZA', 'ukr', 'Південно-Африканська Республіка'),
  ('ZM', 'eng', 'Zambia'),
  ('ZM', 'por', 'Zâmbia'),
  ('ZM', 'spa', 'Zambia'),
  ('ZM', 'ukr', 'Замбія'),
  ('ZW', 'eng', 'Zimbabwe'),
  ('ZW', 'por', 'Zimbábue'),
  ('ZW', 'spa', 'Zimbabue'),
  ('ZW', 'ukr', 'Зімбабве');

-- Now that refdata_countries exists, close the FK location_locations.country_id deferred
-- (0012_core_location.sql).
ALTER TABLE openfaithmap.location_locations
  ADD CONSTRAINT location_locations_country_fk
    FOREIGN KEY (country_id) REFERENCES openfaithmap.refdata_countries(id) ON DELETE RESTRICT;
