// Code generated by conjure-go. DO NOT EDIT.

package content

import (
	"strings"
)

type BlockTypeStatus struct {
	val BlockTypeStatus_Value
}

type BlockTypeStatus_Value string

const (
	BlockTypeStatus_ACTIVE  BlockTypeStatus_Value = "ACTIVE"
	BlockTypeStatus_RETIRED BlockTypeStatus_Value = "RETIRED"
	BlockTypeStatus_UNKNOWN BlockTypeStatus_Value = "UNKNOWN"
)

// BlockTypeStatus_Values returns all known variants of BlockTypeStatus.
func BlockTypeStatus_Values() []BlockTypeStatus_Value {
	return []BlockTypeStatus_Value{BlockTypeStatus_ACTIVE, BlockTypeStatus_RETIRED}
}

func New_BlockTypeStatus(value BlockTypeStatus_Value) BlockTypeStatus {
	return BlockTypeStatus{val: value}
}

// IsUnknown returns false for all known variants of BlockTypeStatus and true otherwise.
func (e BlockTypeStatus) IsUnknown() bool {
	switch e.val {
	case BlockTypeStatus_ACTIVE, BlockTypeStatus_RETIRED:
		return false
	}
	return true
}

func (e BlockTypeStatus) Value() BlockTypeStatus_Value {
	if e.IsUnknown() {
		return BlockTypeStatus_UNKNOWN
	}
	return e.val
}

func (e BlockTypeStatus) String() string {
	return string(e.val)
}

func (e BlockTypeStatus) MarshalText() ([]byte, error) {
	return []byte(e.val), nil
}

func (e *BlockTypeStatus) UnmarshalText(data []byte) error {
	switch v := strings.ToUpper(string(data)); v {
	default:
		*e = New_BlockTypeStatus(BlockTypeStatus_Value(v))
	case "ACTIVE":
		*e = New_BlockTypeStatus(BlockTypeStatus_ACTIVE)
	case "RETIRED":
		*e = New_BlockTypeStatus(BlockTypeStatus_RETIRED)
	}
	return nil
}

type DocumentKind struct {
	val DocumentKind_Value
}

type DocumentKind_Value string

const (
	DocumentKind_PAGE    DocumentKind_Value = "PAGE"
	DocumentKind_POST    DocumentKind_Value = "POST"
	DocumentKind_EVENT   DocumentKind_Value = "EVENT"
	DocumentKind_UNKNOWN DocumentKind_Value = "UNKNOWN"
)

// DocumentKind_Values returns all known variants of DocumentKind.
func DocumentKind_Values() []DocumentKind_Value {
	return []DocumentKind_Value{DocumentKind_PAGE, DocumentKind_POST, DocumentKind_EVENT}
}

func New_DocumentKind(value DocumentKind_Value) DocumentKind {
	return DocumentKind{val: value}
}

// IsUnknown returns false for all known variants of DocumentKind and true otherwise.
func (e DocumentKind) IsUnknown() bool {
	switch e.val {
	case DocumentKind_PAGE, DocumentKind_POST, DocumentKind_EVENT:
		return false
	}
	return true
}

func (e DocumentKind) Value() DocumentKind_Value {
	if e.IsUnknown() {
		return DocumentKind_UNKNOWN
	}
	return e.val
}

func (e DocumentKind) String() string {
	return string(e.val)
}

func (e DocumentKind) MarshalText() ([]byte, error) {
	return []byte(e.val), nil
}

func (e *DocumentKind) UnmarshalText(data []byte) error {
	switch v := strings.ToUpper(string(data)); v {
	default:
		*e = New_DocumentKind(DocumentKind_Value(v))
	case "PAGE":
		*e = New_DocumentKind(DocumentKind_PAGE)
	case "POST":
		*e = New_DocumentKind(DocumentKind_POST)
	case "EVENT":
		*e = New_DocumentKind(DocumentKind_EVENT)
	}
	return nil
}

type DocumentState struct {
	val DocumentState_Value
}

type DocumentState_Value string

const (
	DocumentState_DRAFT     DocumentState_Value = "DRAFT"
	DocumentState_PUBLISHED DocumentState_Value = "PUBLISHED"
	DocumentState_UNLISTED  DocumentState_Value = "UNLISTED"
	DocumentState_SCHEDULED DocumentState_Value = "SCHEDULED"
	DocumentState_UNKNOWN   DocumentState_Value = "UNKNOWN"
)

// DocumentState_Values returns all known variants of DocumentState.
func DocumentState_Values() []DocumentState_Value {
	return []DocumentState_Value{DocumentState_DRAFT, DocumentState_PUBLISHED, DocumentState_UNLISTED, DocumentState_SCHEDULED}
}

func New_DocumentState(value DocumentState_Value) DocumentState {
	return DocumentState{val: value}
}

// IsUnknown returns false for all known variants of DocumentState and true otherwise.
func (e DocumentState) IsUnknown() bool {
	switch e.val {
	case DocumentState_DRAFT, DocumentState_PUBLISHED, DocumentState_UNLISTED, DocumentState_SCHEDULED:
		return false
	}
	return true
}

func (e DocumentState) Value() DocumentState_Value {
	if e.IsUnknown() {
		return DocumentState_UNKNOWN
	}
	return e.val
}

func (e DocumentState) String() string {
	return string(e.val)
}

func (e DocumentState) MarshalText() ([]byte, error) {
	return []byte(e.val), nil
}

func (e *DocumentState) UnmarshalText(data []byte) error {
	switch v := strings.ToUpper(string(data)); v {
	default:
		*e = New_DocumentState(DocumentState_Value(v))
	case "DRAFT":
		*e = New_DocumentState(DocumentState_DRAFT)
	case "PUBLISHED":
		*e = New_DocumentState(DocumentState_PUBLISHED)
	case "UNLISTED":
		*e = New_DocumentState(DocumentState_UNLISTED)
	case "SCHEDULED":
		*e = New_DocumentState(DocumentState_SCHEDULED)
	}
	return nil
}

type DocumentTransitionAction struct {
	val DocumentTransitionAction_Value
}

type DocumentTransitionAction_Value string

const (
	DocumentTransitionAction_PUBLISH         DocumentTransitionAction_Value = "PUBLISH"
	DocumentTransitionAction_UNLIST          DocumentTransitionAction_Value = "UNLIST"
	DocumentTransitionAction_REVERT_TO_DRAFT DocumentTransitionAction_Value = "REVERT_TO_DRAFT"
	DocumentTransitionAction_SCHEDULE        DocumentTransitionAction_Value = "SCHEDULE"
	DocumentTransitionAction_UNKNOWN         DocumentTransitionAction_Value = "UNKNOWN"
)

// DocumentTransitionAction_Values returns all known variants of DocumentTransitionAction.
func DocumentTransitionAction_Values() []DocumentTransitionAction_Value {
	return []DocumentTransitionAction_Value{DocumentTransitionAction_PUBLISH, DocumentTransitionAction_UNLIST, DocumentTransitionAction_REVERT_TO_DRAFT, DocumentTransitionAction_SCHEDULE}
}

func New_DocumentTransitionAction(value DocumentTransitionAction_Value) DocumentTransitionAction {
	return DocumentTransitionAction{val: value}
}

// IsUnknown returns false for all known variants of DocumentTransitionAction and true otherwise.
func (e DocumentTransitionAction) IsUnknown() bool {
	switch e.val {
	case DocumentTransitionAction_PUBLISH, DocumentTransitionAction_UNLIST, DocumentTransitionAction_REVERT_TO_DRAFT, DocumentTransitionAction_SCHEDULE:
		return false
	}
	return true
}

func (e DocumentTransitionAction) Value() DocumentTransitionAction_Value {
	if e.IsUnknown() {
		return DocumentTransitionAction_UNKNOWN
	}
	return e.val
}

func (e DocumentTransitionAction) String() string {
	return string(e.val)
}

func (e DocumentTransitionAction) MarshalText() ([]byte, error) {
	return []byte(e.val), nil
}

func (e *DocumentTransitionAction) UnmarshalText(data []byte) error {
	switch v := strings.ToUpper(string(data)); v {
	default:
		*e = New_DocumentTransitionAction(DocumentTransitionAction_Value(v))
	case "PUBLISH":
		*e = New_DocumentTransitionAction(DocumentTransitionAction_PUBLISH)
	case "UNLIST":
		*e = New_DocumentTransitionAction(DocumentTransitionAction_UNLIST)
	case "REVERT_TO_DRAFT":
		*e = New_DocumentTransitionAction(DocumentTransitionAction_REVERT_TO_DRAFT)
	case "SCHEDULE":
		*e = New_DocumentTransitionAction(DocumentTransitionAction_SCHEDULE)
	}
	return nil
}
