// Code generated by conjure-go. DO NOT EDIT.

package content

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/olehmushka/open-faith-map/internal/conjure/internal/conjureerrors"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/errors"
	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
	"github.com/palantir/pkg/uuid"
	werror "github.com/palantir/witchcraft-go-error"
)

type blockDataInvalid struct {
	BlockTypeCode string `json:"blockTypeCode"`
	Position      int    `json:"position"`
}

func (o blockDataInvalid) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *blockDataInvalid) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// NewBlockDataInvalid returns new instance of BlockDataInvalid error.
func NewBlockDataInvalid(blockTypeCodeArg string, positionArg int) *BlockDataInvalid {
	return &BlockDataInvalid{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), blockDataInvalid: blockDataInvalid{BlockTypeCode: blockTypeCodeArg, Position: positionArg}}
}

// WrapWithBlockDataInvalid returns new instance of BlockDataInvalid error wrapping an existing error.
func WrapWithBlockDataInvalid(err error, blockTypeCodeArg string, positionArg int) *BlockDataInvalid {
	return &BlockDataInvalid{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), cause: err, blockDataInvalid: blockDataInvalid{BlockTypeCode: blockTypeCodeArg, Position: positionArg}}
}

// BlockDataInvalid is an error type.
// block.data failed json_schema validation for its block type.
type BlockDataInvalid struct {
	errorInstanceID uuid.UUID
	blockDataInvalid
	cause error
	stack werror.StackTrace
}

// IsBlockDataInvalid returns true if err is an instance of BlockDataInvalid.
func IsBlockDataInvalid(err error) bool {
	if err == nil {
		return false
	}
	_, ok := errors.GetConjureError(err).(*BlockDataInvalid)
	return ok
}

func (e *BlockDataInvalid) Error() string {
	return fmt.Sprintf("INVALID_ARGUMENT Content:BlockDataInvalid (%s)", e.errorInstanceID)
}

// Cause returns the underlying cause of the error, or nil if none.
// Note that cause is not serialized and sent over the wire.
func (e *BlockDataInvalid) Cause() error {
	return e.cause
}

// StackTrace returns the StackTrace for the error, or nil if none.
// Note that stack traces are not serialized and sent over the wire.
func (e *BlockDataInvalid) StackTrace() werror.StackTrace {
	return e.stack
}

// Message returns the message body for the error.
func (e *BlockDataInvalid) Message() string {
	return "INVALID_ARGUMENT Content:BlockDataInvalid"
}

// Format implements fmt.Formatter, a requirement of werror.Werror.
func (e *BlockDataInvalid) Format(state fmt.State, verb rune) {
	werror.Format(e, e.safeParams(), state, verb)
}

// Code returns an enum describing error category.
func (e *BlockDataInvalid) Code() errors.ErrorCode {
	return errors.InvalidArgument
}

// Name returns an error name identifying error type.
func (e *BlockDataInvalid) Name() string {
	return "Content:BlockDataInvalid"
}

// InstanceID returns unique identifier of this particular error instance.
func (e *BlockDataInvalid) InstanceID() uuid.UUID {
	return e.errorInstanceID
}

// Parameters returns a set of named parameters detailing this particular error instance.
func (e *BlockDataInvalid) Parameters() map[string]interface{} {
	return map[string]interface{}{"blockTypeCode": e.BlockTypeCode, "position": e.Position}
}

// safeParams returns a set of named safe parameters detailing this particular error instance.
func (e *BlockDataInvalid) safeParams() map[string]interface{} {
	return map[string]interface{}{"blockTypeCode": e.BlockTypeCode, "position": e.Position, "errorInstanceId": e.errorInstanceID, "errorName": e.Name()}
}

// SafeParams returns a set of named safe parameters detailing this particular error instance and
// any underlying causes.
func (e *BlockDataInvalid) SafeParams() map[string]interface{} {
	safeParams, _ := werror.ParamsFromError(e.cause)
	for k, v := range e.safeParams() {
		if _, exists := safeParams[k]; !exists {
			safeParams[k] = v
		}
	}
	return safeParams
}

// unsafeParams returns a set of named unsafe parameters detailing this particular error instance.
func (e *BlockDataInvalid) unsafeParams() map[string]interface{} {
	return map[string]interface{}{}
}

// UnsafeParams returns a set of named unsafe parameters detailing this particular error instance and
// any underlying causes.
func (e *BlockDataInvalid) UnsafeParams() map[string]interface{} {
	_, unsafeParams := werror.ParamsFromError(e.cause)
	for k, v := range e.unsafeParams() {
		if _, exists := unsafeParams[k]; !exists {
			unsafeParams[k] = v
		}
	}
	return unsafeParams
}

func (e BlockDataInvalid) MarshalJSON() ([]byte, error) {
	parameters, err := safejson.Marshal(e.blockDataInvalid)
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(errors.SerializableError{ErrorCode: errors.InvalidArgument, ErrorName: "Content:BlockDataInvalid", ErrorInstanceID: e.errorInstanceID, Parameters: json.RawMessage(parameters)})
}

func (e *BlockDataInvalid) UnmarshalJSON(data []byte) error {
	var serializableError errors.SerializableError
	if err := safejson.Unmarshal(data, &serializableError); err != nil {
		return err
	}
	var parameters blockDataInvalid
	if err := safejson.Unmarshal([]byte(serializableError.Parameters), &parameters); err != nil {
		return err
	}
	e.errorInstanceID = serializableError.ErrorInstanceID
	e.blockDataInvalid = parameters
	return nil
}

type blockTypeNotFound struct {
	BlockTypeCode string `json:"blockTypeCode"`
}

func (o blockTypeNotFound) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *blockTypeNotFound) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// NewBlockTypeNotFound returns new instance of BlockTypeNotFound error.
func NewBlockTypeNotFound(blockTypeCodeArg string) *BlockTypeNotFound {
	return &BlockTypeNotFound{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), blockTypeNotFound: blockTypeNotFound{BlockTypeCode: blockTypeCodeArg}}
}

// WrapWithBlockTypeNotFound returns new instance of BlockTypeNotFound error wrapping an existing error.
func WrapWithBlockTypeNotFound(err error, blockTypeCodeArg string) *BlockTypeNotFound {
	return &BlockTypeNotFound{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), cause: err, blockTypeNotFound: blockTypeNotFound{BlockTypeCode: blockTypeCodeArg}}
}

// BlockTypeNotFound is an error type.
type BlockTypeNotFound struct {
	errorInstanceID uuid.UUID
	blockTypeNotFound
	cause error
	stack werror.StackTrace
}

// IsBlockTypeNotFound returns true if err is an instance of BlockTypeNotFound.
func IsBlockTypeNotFound(err error) bool {
	if err == nil {
		return false
	}
	_, ok := errors.GetConjureError(err).(*BlockTypeNotFound)
	return ok
}

func (e *BlockTypeNotFound) Error() string {
	return fmt.Sprintf("INVALID_ARGUMENT Content:BlockTypeNotFound (%s)", e.errorInstanceID)
}

// Cause returns the underlying cause of the error, or nil if none.
// Note that cause is not serialized and sent over the wire.
func (e *BlockTypeNotFound) Cause() error {
	return e.cause
}

// StackTrace returns the StackTrace for the error, or nil if none.
// Note that stack traces are not serialized and sent over the wire.
func (e *BlockTypeNotFound) StackTrace() werror.StackTrace {
	return e.stack
}

// Message returns the message body for the error.
func (e *BlockTypeNotFound) Message() string {
	return "INVALID_ARGUMENT Content:BlockTypeNotFound"
}

// Format implements fmt.Formatter, a requirement of werror.Werror.
func (e *BlockTypeNotFound) Format(state fmt.State, verb rune) {
	werror.Format(e, e.safeParams(), state, verb)
}

// Code returns an enum describing error category.
func (e *BlockTypeNotFound) Code() errors.ErrorCode {
	return errors.InvalidArgument
}

// Name returns an error name identifying error type.
func (e *BlockTypeNotFound) Name() string {
	return "Content:BlockTypeNotFound"
}

// InstanceID returns unique identifier of this particular error instance.
func (e *BlockTypeNotFound) InstanceID() uuid.UUID {
	return e.errorInstanceID
}

// Parameters returns a set of named parameters detailing this particular error instance.
func (e *BlockTypeNotFound) Parameters() map[string]interface{} {
	return map[string]interface{}{"blockTypeCode": e.BlockTypeCode}
}

// safeParams returns a set of named safe parameters detailing this particular error instance.
func (e *BlockTypeNotFound) safeParams() map[string]interface{} {
	return map[string]interface{}{"blockTypeCode": e.BlockTypeCode, "errorInstanceId": e.errorInstanceID, "errorName": e.Name()}
}

// SafeParams returns a set of named safe parameters detailing this particular error instance and
// any underlying causes.
func (e *BlockTypeNotFound) SafeParams() map[string]interface{} {
	safeParams, _ := werror.ParamsFromError(e.cause)
	for k, v := range e.safeParams() {
		if _, exists := safeParams[k]; !exists {
			safeParams[k] = v
		}
	}
	return safeParams
}

// unsafeParams returns a set of named unsafe parameters detailing this particular error instance.
func (e *BlockTypeNotFound) unsafeParams() map[string]interface{} {
	return map[string]interface{}{}
}

// UnsafeParams returns a set of named unsafe parameters detailing this particular error instance and
// any underlying causes.
func (e *BlockTypeNotFound) UnsafeParams() map[string]interface{} {
	_, unsafeParams := werror.ParamsFromError(e.cause)
	for k, v := range e.unsafeParams() {
		if _, exists := unsafeParams[k]; !exists {
			unsafeParams[k] = v
		}
	}
	return unsafeParams
}

func (e BlockTypeNotFound) MarshalJSON() ([]byte, error) {
	parameters, err := safejson.Marshal(e.blockTypeNotFound)
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(errors.SerializableError{ErrorCode: errors.InvalidArgument, ErrorName: "Content:BlockTypeNotFound", ErrorInstanceID: e.errorInstanceID, Parameters: json.RawMessage(parameters)})
}

func (e *BlockTypeNotFound) UnmarshalJSON(data []byte) error {
	var serializableError errors.SerializableError
	if err := safejson.Unmarshal(data, &serializableError); err != nil {
		return err
	}
	var parameters blockTypeNotFound
	if err := safejson.Unmarshal([]byte(serializableError.Parameters), &parameters); err != nil {
		return err
	}
	e.errorInstanceID = serializableError.ErrorInstanceID
	e.blockTypeNotFound = parameters
	return nil
}

type documentNotFound struct {
	DocumentId string `json:"documentId"`
}

func (o documentNotFound) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *documentNotFound) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// NewDocumentNotFound returns new instance of DocumentNotFound error.
func NewDocumentNotFound(documentIdArg string) *DocumentNotFound {
	return &DocumentNotFound{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), documentNotFound: documentNotFound{DocumentId: documentIdArg}}
}

// WrapWithDocumentNotFound returns new instance of DocumentNotFound error wrapping an existing error.
func WrapWithDocumentNotFound(err error, documentIdArg string) *DocumentNotFound {
	return &DocumentNotFound{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), cause: err, documentNotFound: documentNotFound{DocumentId: documentIdArg}}
}

// DocumentNotFound is an error type.
type DocumentNotFound struct {
	errorInstanceID uuid.UUID
	documentNotFound
	cause error
	stack werror.StackTrace
}

// IsDocumentNotFound returns true if err is an instance of DocumentNotFound.
func IsDocumentNotFound(err error) bool {
	if err == nil {
		return false
	}
	_, ok := errors.GetConjureError(err).(*DocumentNotFound)
	return ok
}

func (e *DocumentNotFound) Error() string {
	return fmt.Sprintf("NOT_FOUND Content:DocumentNotFound (%s)", e.errorInstanceID)
}

// Cause returns the underlying cause of the error, or nil if none.
// Note that cause is not serialized and sent over the wire.
func (e *DocumentNotFound) Cause() error {
	return e.cause
}

// StackTrace returns the StackTrace for the error, or nil if none.
// Note that stack traces are not serialized and sent over the wire.
func (e *DocumentNotFound) StackTrace() werror.StackTrace {
	return e.stack
}

// Message returns the message body for the error.
func (e *DocumentNotFound) Message() string {
	return "NOT_FOUND Content:DocumentNotFound"
}

// Format implements fmt.Formatter, a requirement of werror.Werror.
func (e *DocumentNotFound) Format(state fmt.State, verb rune) {
	werror.Format(e, e.safeParams(), state, verb)
}

// Code returns an enum describing error category.
func (e *DocumentNotFound) Code() errors.ErrorCode {
	return errors.NotFound
}

// Name returns an error name identifying error type.
func (e *DocumentNotFound) Name() string {
	return "Content:DocumentNotFound"
}

// InstanceID returns unique identifier of this particular error instance.
func (e *DocumentNotFound) InstanceID() uuid.UUID {
	return e.errorInstanceID
}

// Parameters returns a set of named parameters detailing this particular error instance.
func (e *DocumentNotFound) Parameters() map[string]interface{} {
	return map[string]interface{}{"documentId": e.DocumentId}
}

// safeParams returns a set of named safe parameters detailing this particular error instance.
func (e *DocumentNotFound) safeParams() map[string]interface{} {
	return map[string]interface{}{"documentId": e.DocumentId, "errorInstanceId": e.errorInstanceID, "errorName": e.Name()}
}

// SafeParams returns a set of named safe parameters detailing this particular error instance and
// any underlying causes.
func (e *DocumentNotFound) SafeParams() map[string]interface{} {
	safeParams, _ := werror.ParamsFromError(e.cause)
	for k, v := range e.safeParams() {
		if _, exists := safeParams[k]; !exists {
			safeParams[k] = v
		}
	}
	return safeParams
}

// unsafeParams returns a set of named unsafe parameters detailing this particular error instance.
func (e *DocumentNotFound) unsafeParams() map[string]interface{} {
	return map[string]interface{}{}
}

// UnsafeParams returns a set of named unsafe parameters detailing this particular error instance and
// any underlying causes.
func (e *DocumentNotFound) UnsafeParams() map[string]interface{} {
	_, unsafeParams := werror.ParamsFromError(e.cause)
	for k, v := range e.unsafeParams() {
		if _, exists := unsafeParams[k]; !exists {
			unsafeParams[k] = v
		}
	}
	return unsafeParams
}

func (e DocumentNotFound) MarshalJSON() ([]byte, error) {
	parameters, err := safejson.Marshal(e.documentNotFound)
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(errors.SerializableError{ErrorCode: errors.NotFound, ErrorName: "Content:DocumentNotFound", ErrorInstanceID: e.errorInstanceID, Parameters: json.RawMessage(parameters)})
}

func (e *DocumentNotFound) UnmarshalJSON(data []byte) error {
	var serializableError errors.SerializableError
	if err := safejson.Unmarshal(data, &serializableError); err != nil {
		return err
	}
	var parameters documentNotFound
	if err := safejson.Unmarshal([]byte(serializableError.Parameters), &parameters); err != nil {
		return err
	}
	e.errorInstanceID = serializableError.ErrorInstanceID
	e.documentNotFound = parameters
	return nil
}

type duplicateBlockPosition struct {
	Position int `json:"position"`
}

func (o duplicateBlockPosition) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *duplicateBlockPosition) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// NewDuplicateBlockPosition returns new instance of DuplicateBlockPosition error.
func NewDuplicateBlockPosition(positionArg int) *DuplicateBlockPosition {
	return &DuplicateBlockPosition{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), duplicateBlockPosition: duplicateBlockPosition{Position: positionArg}}
}

// WrapWithDuplicateBlockPosition returns new instance of DuplicateBlockPosition error wrapping an existing error.
func WrapWithDuplicateBlockPosition(err error, positionArg int) *DuplicateBlockPosition {
	return &DuplicateBlockPosition{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), cause: err, duplicateBlockPosition: duplicateBlockPosition{Position: positionArg}}
}

// DuplicateBlockPosition is an error type.
// Two blocks in the same putBlocks call shared a position — rejected up front, no re-derivation.
type DuplicateBlockPosition struct {
	errorInstanceID uuid.UUID
	duplicateBlockPosition
	cause error
	stack werror.StackTrace
}

// IsDuplicateBlockPosition returns true if err is an instance of DuplicateBlockPosition.
func IsDuplicateBlockPosition(err error) bool {
	if err == nil {
		return false
	}
	_, ok := errors.GetConjureError(err).(*DuplicateBlockPosition)
	return ok
}

func (e *DuplicateBlockPosition) Error() string {
	return fmt.Sprintf("INVALID_ARGUMENT Content:DuplicateBlockPosition (%s)", e.errorInstanceID)
}

// Cause returns the underlying cause of the error, or nil if none.
// Note that cause is not serialized and sent over the wire.
func (e *DuplicateBlockPosition) Cause() error {
	return e.cause
}

// StackTrace returns the StackTrace for the error, or nil if none.
// Note that stack traces are not serialized and sent over the wire.
func (e *DuplicateBlockPosition) StackTrace() werror.StackTrace {
	return e.stack
}

// Message returns the message body for the error.
func (e *DuplicateBlockPosition) Message() string {
	return "INVALID_ARGUMENT Content:DuplicateBlockPosition"
}

// Format implements fmt.Formatter, a requirement of werror.Werror.
func (e *DuplicateBlockPosition) Format(state fmt.State, verb rune) {
	werror.Format(e, e.safeParams(), state, verb)
}

// Code returns an enum describing error category.
func (e *DuplicateBlockPosition) Code() errors.ErrorCode {
	return errors.InvalidArgument
}

// Name returns an error name identifying error type.
func (e *DuplicateBlockPosition) Name() string {
	return "Content:DuplicateBlockPosition"
}

// InstanceID returns unique identifier of this particular error instance.
func (e *DuplicateBlockPosition) InstanceID() uuid.UUID {
	return e.errorInstanceID
}

// Parameters returns a set of named parameters detailing this particular error instance.
func (e *DuplicateBlockPosition) Parameters() map[string]interface{} {
	return map[string]interface{}{"position": e.Position}
}

// safeParams returns a set of named safe parameters detailing this particular error instance.
func (e *DuplicateBlockPosition) safeParams() map[string]interface{} {
	return map[string]interface{}{"position": e.Position, "errorInstanceId": e.errorInstanceID, "errorName": e.Name()}
}

// SafeParams returns a set of named safe parameters detailing this particular error instance and
// any underlying causes.
func (e *DuplicateBlockPosition) SafeParams() map[string]interface{} {
	safeParams, _ := werror.ParamsFromError(e.cause)
	for k, v := range e.safeParams() {
		if _, exists := safeParams[k]; !exists {
			safeParams[k] = v
		}
	}
	return safeParams
}

// unsafeParams returns a set of named unsafe parameters detailing this particular error instance.
func (e *DuplicateBlockPosition) unsafeParams() map[string]interface{} {
	return map[string]interface{}{}
}

// UnsafeParams returns a set of named unsafe parameters detailing this particular error instance and
// any underlying causes.
func (e *DuplicateBlockPosition) UnsafeParams() map[string]interface{} {
	_, unsafeParams := werror.ParamsFromError(e.cause)
	for k, v := range e.unsafeParams() {
		if _, exists := unsafeParams[k]; !exists {
			unsafeParams[k] = v
		}
	}
	return unsafeParams
}

func (e DuplicateBlockPosition) MarshalJSON() ([]byte, error) {
	parameters, err := safejson.Marshal(e.duplicateBlockPosition)
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(errors.SerializableError{ErrorCode: errors.InvalidArgument, ErrorName: "Content:DuplicateBlockPosition", ErrorInstanceID: e.errorInstanceID, Parameters: json.RawMessage(parameters)})
}

func (e *DuplicateBlockPosition) UnmarshalJSON(data []byte) error {
	var serializableError errors.SerializableError
	if err := safejson.Unmarshal(data, &serializableError); err != nil {
		return err
	}
	var parameters duplicateBlockPosition
	if err := safejson.Unmarshal([]byte(serializableError.Parameters), &parameters); err != nil {
		return err
	}
	e.errorInstanceID = serializableError.ErrorInstanceID
	e.duplicateBlockPosition = parameters
	return nil
}

type forbidden struct{}

func (o forbidden) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *forbidden) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// NewForbidden returns new instance of Forbidden error.
func NewForbidden() *Forbidden {
	return &Forbidden{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), forbidden: forbidden{}}
}

// WrapWithForbidden returns new instance of Forbidden error wrapping an existing error.
func WrapWithForbidden(err error) *Forbidden {
	return &Forbidden{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), cause: err, forbidden: forbidden{}}
}

// Forbidden is an error type.
// The caller does not hold religionorg.manage on this site's congregation unit.
type Forbidden struct {
	errorInstanceID uuid.UUID
	forbidden
	cause error
	stack werror.StackTrace
}

// IsForbidden returns true if err is an instance of Forbidden.
func IsForbidden(err error) bool {
	if err == nil {
		return false
	}
	_, ok := errors.GetConjureError(err).(*Forbidden)
	return ok
}

func (e *Forbidden) Error() string {
	return fmt.Sprintf("PERMISSION_DENIED Content:Forbidden (%s)", e.errorInstanceID)
}

// Cause returns the underlying cause of the error, or nil if none.
// Note that cause is not serialized and sent over the wire.
func (e *Forbidden) Cause() error {
	return e.cause
}

// StackTrace returns the StackTrace for the error, or nil if none.
// Note that stack traces are not serialized and sent over the wire.
func (e *Forbidden) StackTrace() werror.StackTrace {
	return e.stack
}

// Message returns the message body for the error.
func (e *Forbidden) Message() string {
	return "PERMISSION_DENIED Content:Forbidden"
}

// Format implements fmt.Formatter, a requirement of werror.Werror.
func (e *Forbidden) Format(state fmt.State, verb rune) {
	werror.Format(e, e.safeParams(), state, verb)
}

// Code returns an enum describing error category.
func (e *Forbidden) Code() errors.ErrorCode {
	return errors.PermissionDenied
}

// Name returns an error name identifying error type.
func (e *Forbidden) Name() string {
	return "Content:Forbidden"
}

// InstanceID returns unique identifier of this particular error instance.
func (e *Forbidden) InstanceID() uuid.UUID {
	return e.errorInstanceID
}

// Parameters returns a set of named parameters detailing this particular error instance.
func (e *Forbidden) Parameters() map[string]interface{} {
	return map[string]interface{}{}
}

// safeParams returns a set of named safe parameters detailing this particular error instance.
func (e *Forbidden) safeParams() map[string]interface{} {
	return map[string]interface{}{"errorInstanceId": e.errorInstanceID, "errorName": e.Name()}
}

// SafeParams returns a set of named safe parameters detailing this particular error instance and
// any underlying causes.
func (e *Forbidden) SafeParams() map[string]interface{} {
	safeParams, _ := werror.ParamsFromError(e.cause)
	for k, v := range e.safeParams() {
		if _, exists := safeParams[k]; !exists {
			safeParams[k] = v
		}
	}
	return safeParams
}

// unsafeParams returns a set of named unsafe parameters detailing this particular error instance.
func (e *Forbidden) unsafeParams() map[string]interface{} {
	return map[string]interface{}{}
}

// UnsafeParams returns a set of named unsafe parameters detailing this particular error instance and
// any underlying causes.
func (e *Forbidden) UnsafeParams() map[string]interface{} {
	_, unsafeParams := werror.ParamsFromError(e.cause)
	for k, v := range e.unsafeParams() {
		if _, exists := unsafeParams[k]; !exists {
			unsafeParams[k] = v
		}
	}
	return unsafeParams
}

func (e Forbidden) MarshalJSON() ([]byte, error) {
	parameters, err := safejson.Marshal(e.forbidden)
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(errors.SerializableError{ErrorCode: errors.PermissionDenied, ErrorName: "Content:Forbidden", ErrorInstanceID: e.errorInstanceID, Parameters: json.RawMessage(parameters)})
}

func (e *Forbidden) UnmarshalJSON(data []byte) error {
	var serializableError errors.SerializableError
	if err := safejson.Unmarshal(data, &serializableError); err != nil {
		return err
	}
	var parameters forbidden
	if err := safejson.Unmarshal([]byte(serializableError.Parameters), &parameters); err != nil {
		return err
	}
	e.errorInstanceID = serializableError.ErrorInstanceID
	e.forbidden = parameters
	return nil
}

type invalidTransition struct {
	DocumentId string `json:"documentId"`
	FromState  string `json:"fromState"`
	Action     string `json:"action"`
}

func (o invalidTransition) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *invalidTransition) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// NewInvalidTransition returns new instance of InvalidTransition error.
func NewInvalidTransition(documentIdArg string, fromStateArg string, actionArg string) *InvalidTransition {
	return &InvalidTransition{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), invalidTransition: invalidTransition{DocumentId: documentIdArg, FromState: fromStateArg, Action: actionArg}}
}

// WrapWithInvalidTransition returns new instance of InvalidTransition error wrapping an existing error.
func WrapWithInvalidTransition(err error, documentIdArg string, fromStateArg string, actionArg string) *InvalidTransition {
	return &InvalidTransition{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), cause: err, invalidTransition: invalidTransition{DocumentId: documentIdArg, FromState: fromStateArg, Action: actionArg}}
}

// InvalidTransition is an error type.
type InvalidTransition struct {
	errorInstanceID uuid.UUID
	invalidTransition
	cause error
	stack werror.StackTrace
}

// IsInvalidTransition returns true if err is an instance of InvalidTransition.
func IsInvalidTransition(err error) bool {
	if err == nil {
		return false
	}
	_, ok := errors.GetConjureError(err).(*InvalidTransition)
	return ok
}

func (e *InvalidTransition) Error() string {
	return fmt.Sprintf("INVALID_ARGUMENT Content:InvalidTransition (%s)", e.errorInstanceID)
}

// Cause returns the underlying cause of the error, or nil if none.
// Note that cause is not serialized and sent over the wire.
func (e *InvalidTransition) Cause() error {
	return e.cause
}

// StackTrace returns the StackTrace for the error, or nil if none.
// Note that stack traces are not serialized and sent over the wire.
func (e *InvalidTransition) StackTrace() werror.StackTrace {
	return e.stack
}

// Message returns the message body for the error.
func (e *InvalidTransition) Message() string {
	return "INVALID_ARGUMENT Content:InvalidTransition"
}

// Format implements fmt.Formatter, a requirement of werror.Werror.
func (e *InvalidTransition) Format(state fmt.State, verb rune) {
	werror.Format(e, e.safeParams(), state, verb)
}

// Code returns an enum describing error category.
func (e *InvalidTransition) Code() errors.ErrorCode {
	return errors.InvalidArgument
}

// Name returns an error name identifying error type.
func (e *InvalidTransition) Name() string {
	return "Content:InvalidTransition"
}

// InstanceID returns unique identifier of this particular error instance.
func (e *InvalidTransition) InstanceID() uuid.UUID {
	return e.errorInstanceID
}

// Parameters returns a set of named parameters detailing this particular error instance.
func (e *InvalidTransition) Parameters() map[string]interface{} {
	return map[string]interface{}{"documentId": e.DocumentId, "fromState": e.FromState, "action": e.Action}
}

// safeParams returns a set of named safe parameters detailing this particular error instance.
func (e *InvalidTransition) safeParams() map[string]interface{} {
	return map[string]interface{}{"documentId": e.DocumentId, "fromState": e.FromState, "action": e.Action, "errorInstanceId": e.errorInstanceID, "errorName": e.Name()}
}

// SafeParams returns a set of named safe parameters detailing this particular error instance and
// any underlying causes.
func (e *InvalidTransition) SafeParams() map[string]interface{} {
	safeParams, _ := werror.ParamsFromError(e.cause)
	for k, v := range e.safeParams() {
		if _, exists := safeParams[k]; !exists {
			safeParams[k] = v
		}
	}
	return safeParams
}

// unsafeParams returns a set of named unsafe parameters detailing this particular error instance.
func (e *InvalidTransition) unsafeParams() map[string]interface{} {
	return map[string]interface{}{}
}

// UnsafeParams returns a set of named unsafe parameters detailing this particular error instance and
// any underlying causes.
func (e *InvalidTransition) UnsafeParams() map[string]interface{} {
	_, unsafeParams := werror.ParamsFromError(e.cause)
	for k, v := range e.unsafeParams() {
		if _, exists := unsafeParams[k]; !exists {
			unsafeParams[k] = v
		}
	}
	return unsafeParams
}

func (e InvalidTransition) MarshalJSON() ([]byte, error) {
	parameters, err := safejson.Marshal(e.invalidTransition)
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(errors.SerializableError{ErrorCode: errors.InvalidArgument, ErrorName: "Content:InvalidTransition", ErrorInstanceID: e.errorInstanceID, Parameters: json.RawMessage(parameters)})
}

func (e *InvalidTransition) UnmarshalJSON(data []byte) error {
	var serializableError errors.SerializableError
	if err := safejson.Unmarshal(data, &serializableError); err != nil {
		return err
	}
	var parameters invalidTransition
	if err := safejson.Unmarshal([]byte(serializableError.Parameters), &parameters); err != nil {
		return err
	}
	e.errorInstanceID = serializableError.ErrorInstanceID
	e.invalidTransition = parameters
	return nil
}

type kindNotSupported struct {
	Kind string `json:"kind"`
}

func (o kindNotSupported) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *kindNotSupported) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// NewKindNotSupported returns new instance of KindNotSupported error.
func NewKindNotSupported(kindArg string) *KindNotSupported {
	return &KindNotSupported{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), kindNotSupported: kindNotSupported{Kind: kindArg}}
}

// WrapWithKindNotSupported returns new instance of KindNotSupported error wrapping an existing error.
func WrapWithKindNotSupported(err error, kindArg string) *KindNotSupported {
	return &KindNotSupported{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), cause: err, kindNotSupported: kindNotSupported{Kind: kindArg}}
}

// KindNotSupported is an error type.
// M3 ships kind=PAGE only; POST/EVENT land at M4.
type KindNotSupported struct {
	errorInstanceID uuid.UUID
	kindNotSupported
	cause error
	stack werror.StackTrace
}

// IsKindNotSupported returns true if err is an instance of KindNotSupported.
func IsKindNotSupported(err error) bool {
	if err == nil {
		return false
	}
	_, ok := errors.GetConjureError(err).(*KindNotSupported)
	return ok
}

func (e *KindNotSupported) Error() string {
	return fmt.Sprintf("INVALID_ARGUMENT Content:KindNotSupported (%s)", e.errorInstanceID)
}

// Cause returns the underlying cause of the error, or nil if none.
// Note that cause is not serialized and sent over the wire.
func (e *KindNotSupported) Cause() error {
	return e.cause
}

// StackTrace returns the StackTrace for the error, or nil if none.
// Note that stack traces are not serialized and sent over the wire.
func (e *KindNotSupported) StackTrace() werror.StackTrace {
	return e.stack
}

// Message returns the message body for the error.
func (e *KindNotSupported) Message() string {
	return "INVALID_ARGUMENT Content:KindNotSupported"
}

// Format implements fmt.Formatter, a requirement of werror.Werror.
func (e *KindNotSupported) Format(state fmt.State, verb rune) {
	werror.Format(e, e.safeParams(), state, verb)
}

// Code returns an enum describing error category.
func (e *KindNotSupported) Code() errors.ErrorCode {
	return errors.InvalidArgument
}

// Name returns an error name identifying error type.
func (e *KindNotSupported) Name() string {
	return "Content:KindNotSupported"
}

// InstanceID returns unique identifier of this particular error instance.
func (e *KindNotSupported) InstanceID() uuid.UUID {
	return e.errorInstanceID
}

// Parameters returns a set of named parameters detailing this particular error instance.
func (e *KindNotSupported) Parameters() map[string]interface{} {
	return map[string]interface{}{"kind": e.Kind}
}

// safeParams returns a set of named safe parameters detailing this particular error instance.
func (e *KindNotSupported) safeParams() map[string]interface{} {
	return map[string]interface{}{"kind": e.Kind, "errorInstanceId": e.errorInstanceID, "errorName": e.Name()}
}

// SafeParams returns a set of named safe parameters detailing this particular error instance and
// any underlying causes.
func (e *KindNotSupported) SafeParams() map[string]interface{} {
	safeParams, _ := werror.ParamsFromError(e.cause)
	for k, v := range e.safeParams() {
		if _, exists := safeParams[k]; !exists {
			safeParams[k] = v
		}
	}
	return safeParams
}

// unsafeParams returns a set of named unsafe parameters detailing this particular error instance.
func (e *KindNotSupported) unsafeParams() map[string]interface{} {
	return map[string]interface{}{}
}

// UnsafeParams returns a set of named unsafe parameters detailing this particular error instance and
// any underlying causes.
func (e *KindNotSupported) UnsafeParams() map[string]interface{} {
	_, unsafeParams := werror.ParamsFromError(e.cause)
	for k, v := range e.unsafeParams() {
		if _, exists := unsafeParams[k]; !exists {
			unsafeParams[k] = v
		}
	}
	return unsafeParams
}

func (e KindNotSupported) MarshalJSON() ([]byte, error) {
	parameters, err := safejson.Marshal(e.kindNotSupported)
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(errors.SerializableError{ErrorCode: errors.InvalidArgument, ErrorName: "Content:KindNotSupported", ErrorInstanceID: e.errorInstanceID, Parameters: json.RawMessage(parameters)})
}

func (e *KindNotSupported) UnmarshalJSON(data []byte) error {
	var serializableError errors.SerializableError
	if err := safejson.Unmarshal(data, &serializableError); err != nil {
		return err
	}
	var parameters kindNotSupported
	if err := safejson.Unmarshal([]byte(serializableError.Parameters), &parameters); err != nil {
		return err
	}
	e.errorInstanceID = serializableError.ErrorInstanceID
	e.kindNotSupported = parameters
	return nil
}

type parentTooDeep struct {
	ParentDocumentId string `json:"parentDocumentId"`
}

func (o parentTooDeep) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *parentTooDeep) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// NewParentTooDeep returns new instance of ParentTooDeep error.
func NewParentTooDeep(parentDocumentIdArg string) *ParentTooDeep {
	return &ParentTooDeep{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), parentTooDeep: parentTooDeep{ParentDocumentId: parentDocumentIdArg}}
}

// WrapWithParentTooDeep returns new instance of ParentTooDeep error wrapping an existing error.
func WrapWithParentTooDeep(err error, parentDocumentIdArg string) *ParentTooDeep {
	return &ParentTooDeep{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), cause: err, parentTooDeep: parentTooDeep{ParentDocumentId: parentDocumentIdArg}}
}

// ParentTooDeep is an error type.
type ParentTooDeep struct {
	errorInstanceID uuid.UUID
	parentTooDeep
	cause error
	stack werror.StackTrace
}

// IsParentTooDeep returns true if err is an instance of ParentTooDeep.
func IsParentTooDeep(err error) bool {
	if err == nil {
		return false
	}
	_, ok := errors.GetConjureError(err).(*ParentTooDeep)
	return ok
}

func (e *ParentTooDeep) Error() string {
	return fmt.Sprintf("INVALID_ARGUMENT Content:ParentTooDeep (%s)", e.errorInstanceID)
}

// Cause returns the underlying cause of the error, or nil if none.
// Note that cause is not serialized and sent over the wire.
func (e *ParentTooDeep) Cause() error {
	return e.cause
}

// StackTrace returns the StackTrace for the error, or nil if none.
// Note that stack traces are not serialized and sent over the wire.
func (e *ParentTooDeep) StackTrace() werror.StackTrace {
	return e.stack
}

// Message returns the message body for the error.
func (e *ParentTooDeep) Message() string {
	return "INVALID_ARGUMENT Content:ParentTooDeep"
}

// Format implements fmt.Formatter, a requirement of werror.Werror.
func (e *ParentTooDeep) Format(state fmt.State, verb rune) {
	werror.Format(e, e.safeParams(), state, verb)
}

// Code returns an enum describing error category.
func (e *ParentTooDeep) Code() errors.ErrorCode {
	return errors.InvalidArgument
}

// Name returns an error name identifying error type.
func (e *ParentTooDeep) Name() string {
	return "Content:ParentTooDeep"
}

// InstanceID returns unique identifier of this particular error instance.
func (e *ParentTooDeep) InstanceID() uuid.UUID {
	return e.errorInstanceID
}

// Parameters returns a set of named parameters detailing this particular error instance.
func (e *ParentTooDeep) Parameters() map[string]interface{} {
	return map[string]interface{}{"parentDocumentId": e.ParentDocumentId}
}

// safeParams returns a set of named safe parameters detailing this particular error instance.
func (e *ParentTooDeep) safeParams() map[string]interface{} {
	return map[string]interface{}{"parentDocumentId": e.ParentDocumentId, "errorInstanceId": e.errorInstanceID, "errorName": e.Name()}
}

// SafeParams returns a set of named safe parameters detailing this particular error instance and
// any underlying causes.
func (e *ParentTooDeep) SafeParams() map[string]interface{} {
	safeParams, _ := werror.ParamsFromError(e.cause)
	for k, v := range e.safeParams() {
		if _, exists := safeParams[k]; !exists {
			safeParams[k] = v
		}
	}
	return safeParams
}

// unsafeParams returns a set of named unsafe parameters detailing this particular error instance.
func (e *ParentTooDeep) unsafeParams() map[string]interface{} {
	return map[string]interface{}{}
}

// UnsafeParams returns a set of named unsafe parameters detailing this particular error instance and
// any underlying causes.
func (e *ParentTooDeep) UnsafeParams() map[string]interface{} {
	_, unsafeParams := werror.ParamsFromError(e.cause)
	for k, v := range e.unsafeParams() {
		if _, exists := unsafeParams[k]; !exists {
			unsafeParams[k] = v
		}
	}
	return unsafeParams
}

func (e ParentTooDeep) MarshalJSON() ([]byte, error) {
	parameters, err := safejson.Marshal(e.parentTooDeep)
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(errors.SerializableError{ErrorCode: errors.InvalidArgument, ErrorName: "Content:ParentTooDeep", ErrorInstanceID: e.errorInstanceID, Parameters: json.RawMessage(parameters)})
}

func (e *ParentTooDeep) UnmarshalJSON(data []byte) error {
	var serializableError errors.SerializableError
	if err := safejson.Unmarshal(data, &serializableError); err != nil {
		return err
	}
	var parameters parentTooDeep
	if err := safejson.Unmarshal([]byte(serializableError.Parameters), &parameters); err != nil {
		return err
	}
	e.errorInstanceID = serializableError.ErrorInstanceID
	e.parentTooDeep = parameters
	return nil
}

type siteNotFound struct {
	SiteId string `json:"siteId"`
}

func (o siteNotFound) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *siteNotFound) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// NewSiteNotFound returns new instance of SiteNotFound error.
func NewSiteNotFound(siteIdArg string) *SiteNotFound {
	return &SiteNotFound{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), siteNotFound: siteNotFound{SiteId: siteIdArg}}
}

// WrapWithSiteNotFound returns new instance of SiteNotFound error wrapping an existing error.
func WrapWithSiteNotFound(err error, siteIdArg string) *SiteNotFound {
	return &SiteNotFound{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), cause: err, siteNotFound: siteNotFound{SiteId: siteIdArg}}
}

// SiteNotFound is an error type.
type SiteNotFound struct {
	errorInstanceID uuid.UUID
	siteNotFound
	cause error
	stack werror.StackTrace
}

// IsSiteNotFound returns true if err is an instance of SiteNotFound.
func IsSiteNotFound(err error) bool {
	if err == nil {
		return false
	}
	_, ok := errors.GetConjureError(err).(*SiteNotFound)
	return ok
}

func (e *SiteNotFound) Error() string {
	return fmt.Sprintf("NOT_FOUND Content:SiteNotFound (%s)", e.errorInstanceID)
}

// Cause returns the underlying cause of the error, or nil if none.
// Note that cause is not serialized and sent over the wire.
func (e *SiteNotFound) Cause() error {
	return e.cause
}

// StackTrace returns the StackTrace for the error, or nil if none.
// Note that stack traces are not serialized and sent over the wire.
func (e *SiteNotFound) StackTrace() werror.StackTrace {
	return e.stack
}

// Message returns the message body for the error.
func (e *SiteNotFound) Message() string {
	return "NOT_FOUND Content:SiteNotFound"
}

// Format implements fmt.Formatter, a requirement of werror.Werror.
func (e *SiteNotFound) Format(state fmt.State, verb rune) {
	werror.Format(e, e.safeParams(), state, verb)
}

// Code returns an enum describing error category.
func (e *SiteNotFound) Code() errors.ErrorCode {
	return errors.NotFound
}

// Name returns an error name identifying error type.
func (e *SiteNotFound) Name() string {
	return "Content:SiteNotFound"
}

// InstanceID returns unique identifier of this particular error instance.
func (e *SiteNotFound) InstanceID() uuid.UUID {
	return e.errorInstanceID
}

// Parameters returns a set of named parameters detailing this particular error instance.
func (e *SiteNotFound) Parameters() map[string]interface{} {
	return map[string]interface{}{"siteId": e.SiteId}
}

// safeParams returns a set of named safe parameters detailing this particular error instance.
func (e *SiteNotFound) safeParams() map[string]interface{} {
	return map[string]interface{}{"siteId": e.SiteId, "errorInstanceId": e.errorInstanceID, "errorName": e.Name()}
}

// SafeParams returns a set of named safe parameters detailing this particular error instance and
// any underlying causes.
func (e *SiteNotFound) SafeParams() map[string]interface{} {
	safeParams, _ := werror.ParamsFromError(e.cause)
	for k, v := range e.safeParams() {
		if _, exists := safeParams[k]; !exists {
			safeParams[k] = v
		}
	}
	return safeParams
}

// unsafeParams returns a set of named unsafe parameters detailing this particular error instance.
func (e *SiteNotFound) unsafeParams() map[string]interface{} {
	return map[string]interface{}{}
}

// UnsafeParams returns a set of named unsafe parameters detailing this particular error instance and
// any underlying causes.
func (e *SiteNotFound) UnsafeParams() map[string]interface{} {
	_, unsafeParams := werror.ParamsFromError(e.cause)
	for k, v := range e.unsafeParams() {
		if _, exists := unsafeParams[k]; !exists {
			unsafeParams[k] = v
		}
	}
	return unsafeParams
}

func (e SiteNotFound) MarshalJSON() ([]byte, error) {
	parameters, err := safejson.Marshal(e.siteNotFound)
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(errors.SerializableError{ErrorCode: errors.NotFound, ErrorName: "Content:SiteNotFound", ErrorInstanceID: e.errorInstanceID, Parameters: json.RawMessage(parameters)})
}

func (e *SiteNotFound) UnmarshalJSON(data []byte) error {
	var serializableError errors.SerializableError
	if err := safejson.Unmarshal(data, &serializableError); err != nil {
		return err
	}
	var parameters siteNotFound
	if err := safejson.Unmarshal([]byte(serializableError.Parameters), &parameters); err != nil {
		return err
	}
	e.errorInstanceID = serializableError.ErrorInstanceID
	e.siteNotFound = parameters
	return nil
}

type slugTaken struct {
	Slug  string `json:"slug"`
	Scope string `json:"scope"`
}

func (o slugTaken) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *slugTaken) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

// NewSlugTaken returns new instance of SlugTaken error.
func NewSlugTaken(slugArg string, scopeArg string) *SlugTaken {
	return &SlugTaken{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), slugTaken: slugTaken{Slug: slugArg, Scope: scopeArg}}
}

// WrapWithSlugTaken returns new instance of SlugTaken error wrapping an existing error.
func WrapWithSlugTaken(err error, slugArg string, scopeArg string) *SlugTaken {
	return &SlugTaken{errorInstanceID: uuid.NewUUID(), stack: werror.NewStackTrace(), cause: err, slugTaken: slugTaken{Slug: slugArg, Scope: scopeArg}}
}

// SlugTaken is an error type.
// U5's resolution: admin-chosen slug, probed for uniqueness at write time — no silent suffixing. scope is "site" (globally unique) or "document" (unique within site+kind+locale).
type SlugTaken struct {
	errorInstanceID uuid.UUID
	slugTaken
	cause error
	stack werror.StackTrace
}

// IsSlugTaken returns true if err is an instance of SlugTaken.
func IsSlugTaken(err error) bool {
	if err == nil {
		return false
	}
	_, ok := errors.GetConjureError(err).(*SlugTaken)
	return ok
}

func (e *SlugTaken) Error() string {
	return fmt.Sprintf("CONFLICT Content:SlugTaken (%s)", e.errorInstanceID)
}

// Cause returns the underlying cause of the error, or nil if none.
// Note that cause is not serialized and sent over the wire.
func (e *SlugTaken) Cause() error {
	return e.cause
}

// StackTrace returns the StackTrace for the error, or nil if none.
// Note that stack traces are not serialized and sent over the wire.
func (e *SlugTaken) StackTrace() werror.StackTrace {
	return e.stack
}

// Message returns the message body for the error.
func (e *SlugTaken) Message() string {
	return "CONFLICT Content:SlugTaken"
}

// Format implements fmt.Formatter, a requirement of werror.Werror.
func (e *SlugTaken) Format(state fmt.State, verb rune) {
	werror.Format(e, e.safeParams(), state, verb)
}

// Code returns an enum describing error category.
func (e *SlugTaken) Code() errors.ErrorCode {
	return errors.Conflict
}

// Name returns an error name identifying error type.
func (e *SlugTaken) Name() string {
	return "Content:SlugTaken"
}

// InstanceID returns unique identifier of this particular error instance.
func (e *SlugTaken) InstanceID() uuid.UUID {
	return e.errorInstanceID
}

// Parameters returns a set of named parameters detailing this particular error instance.
func (e *SlugTaken) Parameters() map[string]interface{} {
	return map[string]interface{}{"slug": e.Slug, "scope": e.Scope}
}

// safeParams returns a set of named safe parameters detailing this particular error instance.
func (e *SlugTaken) safeParams() map[string]interface{} {
	return map[string]interface{}{"slug": e.Slug, "scope": e.Scope, "errorInstanceId": e.errorInstanceID, "errorName": e.Name()}
}

// SafeParams returns a set of named safe parameters detailing this particular error instance and
// any underlying causes.
func (e *SlugTaken) SafeParams() map[string]interface{} {
	safeParams, _ := werror.ParamsFromError(e.cause)
	for k, v := range e.safeParams() {
		if _, exists := safeParams[k]; !exists {
			safeParams[k] = v
		}
	}
	return safeParams
}

// unsafeParams returns a set of named unsafe parameters detailing this particular error instance.
func (e *SlugTaken) unsafeParams() map[string]interface{} {
	return map[string]interface{}{}
}

// UnsafeParams returns a set of named unsafe parameters detailing this particular error instance and
// any underlying causes.
func (e *SlugTaken) UnsafeParams() map[string]interface{} {
	_, unsafeParams := werror.ParamsFromError(e.cause)
	for k, v := range e.unsafeParams() {
		if _, exists := unsafeParams[k]; !exists {
			unsafeParams[k] = v
		}
	}
	return unsafeParams
}

func (e SlugTaken) MarshalJSON() ([]byte, error) {
	parameters, err := safejson.Marshal(e.slugTaken)
	if err != nil {
		return nil, err
	}
	return safejson.Marshal(errors.SerializableError{ErrorCode: errors.Conflict, ErrorName: "Content:SlugTaken", ErrorInstanceID: e.errorInstanceID, Parameters: json.RawMessage(parameters)})
}

func (e *SlugTaken) UnmarshalJSON(data []byte) error {
	var serializableError errors.SerializableError
	if err := safejson.Unmarshal(data, &serializableError); err != nil {
		return err
	}
	var parameters slugTaken
	if err := safejson.Unmarshal([]byte(serializableError.Parameters), &parameters); err != nil {
		return err
	}
	e.errorInstanceID = serializableError.ErrorInstanceID
	e.slugTaken = parameters
	return nil
}

func init() {
	conjureerrors.RegisterErrorType("Content:BlockDataInvalid", reflect.TypeOf(BlockDataInvalid{}))
	conjureerrors.RegisterErrorType("Content:BlockTypeNotFound", reflect.TypeOf(BlockTypeNotFound{}))
	conjureerrors.RegisterErrorType("Content:DocumentNotFound", reflect.TypeOf(DocumentNotFound{}))
	conjureerrors.RegisterErrorType("Content:DuplicateBlockPosition", reflect.TypeOf(DuplicateBlockPosition{}))
	conjureerrors.RegisterErrorType("Content:Forbidden", reflect.TypeOf(Forbidden{}))
	conjureerrors.RegisterErrorType("Content:InvalidTransition", reflect.TypeOf(InvalidTransition{}))
	conjureerrors.RegisterErrorType("Content:KindNotSupported", reflect.TypeOf(KindNotSupported{}))
	conjureerrors.RegisterErrorType("Content:ParentTooDeep", reflect.TypeOf(ParentTooDeep{}))
	conjureerrors.RegisterErrorType("Content:SiteNotFound", reflect.TypeOf(SiteNotFound{}))
	conjureerrors.RegisterErrorType("Content:SlugTaken", reflect.TypeOf(SlugTaken{}))
}
