// Code generated by conjure-go. DO NOT EDIT.

package content

import (
	"context"
	"net/http"

	"github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/codecs"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/errors"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-server/httpserver"
	"github.com/palantir/pkg/bearertoken"
	werror "github.com/palantir/witchcraft-go-error"
	"github.com/palantir/witchcraft-go-server/v2/witchcraft/wresource"
	"github.com/palantir/witchcraft-go-server/v2/wrouter"
)

// Anonymous reads only (openfaithmap-web holds no session — D-AdminSurface). Always filters to published/unlisted; never discloses draft documents or their blocks — with exactly one carve-out, M14.7's listPreviewDocuments/getPreviewBlocks, which require a valid site-scoped preview token (minted by ContentService.createPreviewLink) in place of a session, since this service's caller never holds one.
type ContentPublicService interface {
	GetSite(ctx context.Context, congregationUnitIdArg string) (Site, error)
	// M14.9: the tenant-subdomain proxy resolves a Host header's slug through this endpoint. A distinct top-level path (not nested under /sites/{siteId}/...) — same httprouter wildcard-slot conflict getSite's own comment above documents.
	GetSiteBySlug(ctx context.Context, slugArg string) (Site, error)
	ListPublicDocuments(ctx context.Context, siteIdArg string, kindArg *string, localeArg *string) (DocumentPage, error)
	// Content:DocumentNotFound if the document is draft or doesn't exist — never distinguishes the two.
	GetPublicBlocks(ctx context.Context, documentIdArg string) (BlockList, error)
	// M14.7. Like listPublicDocuments, but returns documents in every state (draft included) — gated by token (from createPreviewLink) instead of published/unlisted filtering. Content:PreviewTokenInvalid if the token is missing, malformed, expired, or scoped to a different site.
	ListPreviewDocuments(ctx context.Context, siteIdArg string, tokenArg string, kindArg *string, localeArg *string) (DocumentPage, error)
	// M14.7. Reads the document's draft revision regardless of its published state — gated by token (from createPreviewLink) instead of a session. Content:PreviewTokenInvalid if the token is missing, malformed, expired, or scoped to a different site than the document's own.
	GetPreviewBlocks(ctx context.Context, documentIdArg string, tokenArg string) (BlockList, error)
	// Active block types only.
	ListBlockTypes(ctx context.Context) (BlockTypePage, error)
	// M14.10. Resolved hrefs, in sortOrder — see PublicNavItem's own docs for the omit-on-missing-or-draft-target behavior.
	ListPublicNavItems(ctx context.Context, siteIdArg string) (PublicNavItemList, error)
	// M14.10. Resolves the leaf PAGE document (by locale + slug) plus its real ancestor chain, for the tenant-subdomain catch-all page route. path is a slash-joined, ordered list of slug segments (e.g. "parent-slug/child-slug"); every segment must match the document's real parent_document_id chain positionally — a mismatch at any position (including the leaf's own slug) 404s exactly like a wrong slug would, never resolving by the last segment alone. Content:DocumentNotFound if the leaf doesn't exist, isn't a PAGE, is DRAFT, or the ancestor chain doesn't match — one error for every case, same discipline as getPublicBlocks.
	GetPublicDocumentByPath(ctx context.Context, siteIdArg string, localeArg string, pathArg string) (DocumentWithAncestors, error)
}

// RegisterRoutesContentPublicService registers handlers for the ContentPublicService endpoints with a witchcraft wrouter.
// This should typically be called in a witchcraft server's InitFunc.
// impl provides an implementation of each endpoint, which can assume the request parameters have been parsed
// in accordance with the Conjure specification.
func RegisterRoutesContentPublicService(router wrouter.Router, impl ContentPublicService, routerParams ...wrouter.RouteParam) error {
	handler := contentPublicServiceHandler{impl: impl}
	resource := wresource.New("contentpublicservice", router)
	if err := resource.Get("GetSite", "/content/v1/public/units/{congregationUnitId}/site", httpserver.NewJSONHandler(handler.HandleGetSite, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getSite route")
	}
	if err := resource.Get("GetSiteBySlug", "/content/v1/public/site-by-slug/{slug}", httpserver.NewJSONHandler(handler.HandleGetSiteBySlug, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getSiteBySlug route")
	}
	if err := resource.Get("ListPublicDocuments", "/content/v1/public/sites/{siteId}/documents", httpserver.NewJSONHandler(handler.HandleListPublicDocuments, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listPublicDocuments route")
	}
	if err := resource.Get("GetPublicBlocks", "/content/v1/public/documents/{documentId}/blocks", httpserver.NewJSONHandler(handler.HandleGetPublicBlocks, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getPublicBlocks route")
	}
	if err := resource.Get("ListPreviewDocuments", "/content/v1/public/sites/{siteId}/preview-documents", httpserver.NewJSONHandler(handler.HandleListPreviewDocuments, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listPreviewDocuments route")
	}
	if err := resource.Get("GetPreviewBlocks", "/content/v1/public/documents/{documentId}/preview-blocks", httpserver.NewJSONHandler(handler.HandleGetPreviewBlocks, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getPreviewBlocks route")
	}
	if err := resource.Get("ListBlockTypes", "/content/v1/public/block-types", httpserver.NewJSONHandler(handler.HandleListBlockTypes, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listBlockTypes route")
	}
	if err := resource.Get("ListPublicNavItems", "/content/v1/public/sites/{siteId}/nav-items", httpserver.NewJSONHandler(handler.HandleListPublicNavItems, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listPublicNavItems route")
	}
	if err := resource.Get("GetPublicDocumentByPath", "/content/v1/public/sites/{siteId}/documents/by-path", httpserver.NewJSONHandler(handler.HandleGetPublicDocumentByPath, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getPublicDocumentByPath route")
	}
	return nil
}

type contentPublicServiceHandler struct {
	impl ContentPublicService
}

func (c *contentPublicServiceHandler) HandleGetSite(rw http.ResponseWriter, req *http.Request) error {
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	congregationUnitIdArg, ok := pathParams["congregationUnitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"congregationUnitId\" not present")
	}
	respArg, err := c.impl.GetSite(req.Context(), congregationUnitIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentPublicServiceHandler) HandleGetSiteBySlug(rw http.ResponseWriter, req *http.Request) error {
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	slugArg, ok := pathParams["slug"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"slug\" not present")
	}
	respArg, err := c.impl.GetSiteBySlug(req.Context(), slugArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentPublicServiceHandler) HandleListPublicDocuments(rw http.ResponseWriter, req *http.Request) error {
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	siteIdArg, ok := pathParams["siteId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"siteId\" not present")
	}
	var kindArg *string
	if kindArgStr := req.URL.Query().Get("kind"); kindArgStr != "" {
		kindArgInternal := kindArgStr
		kindArg = &kindArgInternal
	}
	var localeArg *string
	if localeArgStr := req.URL.Query().Get("locale"); localeArgStr != "" {
		localeArgInternal := localeArgStr
		localeArg = &localeArgInternal
	}
	respArg, err := c.impl.ListPublicDocuments(req.Context(), siteIdArg, kindArg, localeArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentPublicServiceHandler) HandleGetPublicBlocks(rw http.ResponseWriter, req *http.Request) error {
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	documentIdArg, ok := pathParams["documentId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"documentId\" not present")
	}
	respArg, err := c.impl.GetPublicBlocks(req.Context(), documentIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentPublicServiceHandler) HandleListPreviewDocuments(rw http.ResponseWriter, req *http.Request) error {
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	siteIdArg, ok := pathParams["siteId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"siteId\" not present")
	}
	tokenArg := req.URL.Query().Get("token")
	var kindArg *string
	if kindArgStr := req.URL.Query().Get("kind"); kindArgStr != "" {
		kindArgInternal := kindArgStr
		kindArg = &kindArgInternal
	}
	var localeArg *string
	if localeArgStr := req.URL.Query().Get("locale"); localeArgStr != "" {
		localeArgInternal := localeArgStr
		localeArg = &localeArgInternal
	}
	respArg, err := c.impl.ListPreviewDocuments(req.Context(), siteIdArg, tokenArg, kindArg, localeArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentPublicServiceHandler) HandleGetPreviewBlocks(rw http.ResponseWriter, req *http.Request) error {
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	documentIdArg, ok := pathParams["documentId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"documentId\" not present")
	}
	tokenArg := req.URL.Query().Get("token")
	respArg, err := c.impl.GetPreviewBlocks(req.Context(), documentIdArg, tokenArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentPublicServiceHandler) HandleListBlockTypes(rw http.ResponseWriter, req *http.Request) error {
	respArg, err := c.impl.ListBlockTypes(req.Context())
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentPublicServiceHandler) HandleListPublicNavItems(rw http.ResponseWriter, req *http.Request) error {
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	siteIdArg, ok := pathParams["siteId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"siteId\" not present")
	}
	respArg, err := c.impl.ListPublicNavItems(req.Context(), siteIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentPublicServiceHandler) HandleGetPublicDocumentByPath(rw http.ResponseWriter, req *http.Request) error {
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	siteIdArg, ok := pathParams["siteId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"siteId\" not present")
	}
	localeArg := req.URL.Query().Get("locale")
	pathArg := req.URL.Query().Get("path")
	respArg, err := c.impl.GetPublicDocumentByPath(req.Context(), siteIdArg, localeArg, pathArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

// Congregation site authoring: sites, documents (pages), blocks. Every write, and every read that must see draft state, is content.manage-gated — a live, target-scoped Authorize call against the site's own congregation unit (see file header). See docs/modules/content.md.
type ContentService interface {
	CreateSite(ctx context.Context, authHeader bearertoken.Token, requestArg CreateSiteRequest) (Site, error)
	UpdateSiteTheme(ctx context.Context, authHeader bearertoken.Token, siteIdArg string, requestArg UpdateSiteThemeRequest) (Site, error)
	// Admin read — returns documents in every state.
	ListDocuments(ctx context.Context, authHeader bearertoken.Token, siteIdArg string, kindArg *string, localeArg *string, stateArg *string) (DocumentPage, error)
	CreateDocument(ctx context.Context, authHeader bearertoken.Token, siteIdArg string, requestArg CreateDocumentRequest) (Document, error)
	UpdateDocument(ctx context.Context, authHeader bearertoken.Token, documentIdArg string, requestArg UpdateDocumentRequest) (Document, error)
	TransitionDocument(ctx context.Context, authHeader bearertoken.Token, documentIdArg string, requestArg TransitionDocumentRequest) (Document, error)
	// Admin read — works regardless of document state.
	GetBlocks(ctx context.Context, authHeader bearertoken.Token, documentIdArg string) (BlockList, error)
	// Full replace of the draft revision's blocks, validated against each referenced block type's json_schema (M14.6: this writes the draft only — never what's published — so this one endpoint serves both the editor's manual save and its debounced autosave).
	PutBlocks(ctx context.Context, authHeader bearertoken.Token, documentIdArg string, requestArg PutBlocksRequest) (BlockList, error)
	// History list (M14.6) — every past checkpoint, newest first, excluding the draft itself.
	ListRevisions(ctx context.Context, authHeader bearertoken.Token, documentIdArg string) (RevisionPage, error)
	// Copies a past checkpoint's blocks into the draft — into the draft only, never auto-publishing (owner decision, 2026-08-28). Publish afterward to make it live.
	RestoreRevision(ctx context.Context, authHeader bearertoken.Token, documentIdArg string, revisionIdArg string) (BlockList, error)
	// M14.7. Mints a short-lived, site-scoped preview token — content.manage-gated, same as every other write/draft-read on this service. The returned token is handed to ContentPublicService's preview endpoints on the tenant subdomain, never used here again.
	CreatePreviewLink(ctx context.Context, authHeader bearertoken.Token, siteIdArg string) (PreviewLink, error)
	// M14.10. Admin read of the site's nav menu, in sortOrder.
	ListNavItems(ctx context.Context, authHeader bearertoken.Token, siteIdArg string) (NavItemList, error)
	// M14.10. Full replace of the site's nav menu — a small, hand-curated list edited as a batch, the same shape putBlocks used before M14.6's revision refactor moved it to an in-place update. Content:DuplicateNavItemSortOrder if two items share a sortOrder, Content:NavTargetAmbiguous if an item has neither or both of targetDocumentId/targetUrl, Content:NavTargetInvalid if targetDocumentId doesn't resolve to a PAGE document in this same site.
	PutNavItems(ctx context.Context, authHeader bearertoken.Token, siteIdArg string, requestArg PutNavItemsRequest) (NavItemList, error)
}

// RegisterRoutesContentService registers handlers for the ContentService endpoints with a witchcraft wrouter.
// This should typically be called in a witchcraft server's InitFunc.
// impl provides an implementation of each endpoint, which can assume the request parameters have been parsed
// in accordance with the Conjure specification.
func RegisterRoutesContentService(router wrouter.Router, impl ContentService, routerParams ...wrouter.RouteParam) error {
	handler := contentServiceHandler{impl: impl}
	resource := wresource.New("contentservice", router)
	if err := resource.Post("CreateSite", "/content/v1/sites", httpserver.NewJSONHandler(handler.HandleCreateSite, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add createSite route")
	}
	if err := resource.Put("UpdateSiteTheme", "/content/v1/sites/{siteId}/theme", httpserver.NewJSONHandler(handler.HandleUpdateSiteTheme, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add updateSiteTheme route")
	}
	if err := resource.Get("ListDocuments", "/content/v1/sites/{siteId}/documents", httpserver.NewJSONHandler(handler.HandleListDocuments, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listDocuments route")
	}
	if err := resource.Post("CreateDocument", "/content/v1/sites/{siteId}/documents", httpserver.NewJSONHandler(handler.HandleCreateDocument, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add createDocument route")
	}
	if err := resource.Put("UpdateDocument", "/content/v1/documents/{documentId}", httpserver.NewJSONHandler(handler.HandleUpdateDocument, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add updateDocument route")
	}
	if err := resource.Post("TransitionDocument", "/content/v1/documents/{documentId}/transition", httpserver.NewJSONHandler(handler.HandleTransitionDocument, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add transitionDocument route")
	}
	if err := resource.Get("GetBlocks", "/content/v1/documents/{documentId}/blocks", httpserver.NewJSONHandler(handler.HandleGetBlocks, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getBlocks route")
	}
	if err := resource.Put("PutBlocks", "/content/v1/documents/{documentId}/blocks", httpserver.NewJSONHandler(handler.HandlePutBlocks, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add putBlocks route")
	}
	if err := resource.Get("ListRevisions", "/content/v1/documents/{documentId}/revisions", httpserver.NewJSONHandler(handler.HandleListRevisions, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listRevisions route")
	}
	if err := resource.Post("RestoreRevision", "/content/v1/documents/{documentId}/revisions/{revisionId}/restore", httpserver.NewJSONHandler(handler.HandleRestoreRevision, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add restoreRevision route")
	}
	if err := resource.Post("CreatePreviewLink", "/content/v1/sites/{siteId}/preview-link", httpserver.NewJSONHandler(handler.HandleCreatePreviewLink, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add createPreviewLink route")
	}
	if err := resource.Get("ListNavItems", "/content/v1/sites/{siteId}/nav-items", httpserver.NewJSONHandler(handler.HandleListNavItems, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listNavItems route")
	}
	if err := resource.Put("PutNavItems", "/content/v1/sites/{siteId}/nav-items", httpserver.NewJSONHandler(handler.HandlePutNavItems, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add putNavItems route")
	}
	return nil
}

type contentServiceHandler struct {
	impl ContentService
}

func (c *contentServiceHandler) HandleCreateSite(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg CreateSiteRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := c.impl.CreateSite(req.Context(), bearertoken.Token(authHeader), requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentServiceHandler) HandleUpdateSiteTheme(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	siteIdArg, ok := pathParams["siteId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"siteId\" not present")
	}
	var requestArg UpdateSiteThemeRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := c.impl.UpdateSiteTheme(req.Context(), bearertoken.Token(authHeader), siteIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentServiceHandler) HandleListDocuments(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	siteIdArg, ok := pathParams["siteId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"siteId\" not present")
	}
	var kindArg *string
	if kindArgStr := req.URL.Query().Get("kind"); kindArgStr != "" {
		kindArgInternal := kindArgStr
		kindArg = &kindArgInternal
	}
	var localeArg *string
	if localeArgStr := req.URL.Query().Get("locale"); localeArgStr != "" {
		localeArgInternal := localeArgStr
		localeArg = &localeArgInternal
	}
	var stateArg *string
	if stateArgStr := req.URL.Query().Get("state"); stateArgStr != "" {
		stateArgInternal := stateArgStr
		stateArg = &stateArgInternal
	}
	respArg, err := c.impl.ListDocuments(req.Context(), bearertoken.Token(authHeader), siteIdArg, kindArg, localeArg, stateArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentServiceHandler) HandleCreateDocument(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	siteIdArg, ok := pathParams["siteId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"siteId\" not present")
	}
	var requestArg CreateDocumentRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := c.impl.CreateDocument(req.Context(), bearertoken.Token(authHeader), siteIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentServiceHandler) HandleUpdateDocument(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	documentIdArg, ok := pathParams["documentId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"documentId\" not present")
	}
	var requestArg UpdateDocumentRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := c.impl.UpdateDocument(req.Context(), bearertoken.Token(authHeader), documentIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentServiceHandler) HandleTransitionDocument(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	documentIdArg, ok := pathParams["documentId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"documentId\" not present")
	}
	var requestArg TransitionDocumentRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := c.impl.TransitionDocument(req.Context(), bearertoken.Token(authHeader), documentIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentServiceHandler) HandleGetBlocks(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	documentIdArg, ok := pathParams["documentId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"documentId\" not present")
	}
	respArg, err := c.impl.GetBlocks(req.Context(), bearertoken.Token(authHeader), documentIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentServiceHandler) HandlePutBlocks(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	documentIdArg, ok := pathParams["documentId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"documentId\" not present")
	}
	var requestArg PutBlocksRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := c.impl.PutBlocks(req.Context(), bearertoken.Token(authHeader), documentIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentServiceHandler) HandleListRevisions(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	documentIdArg, ok := pathParams["documentId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"documentId\" not present")
	}
	respArg, err := c.impl.ListRevisions(req.Context(), bearertoken.Token(authHeader), documentIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentServiceHandler) HandleRestoreRevision(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	documentIdArg, ok := pathParams["documentId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"documentId\" not present")
	}
	revisionIdArg, ok := pathParams["revisionId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"revisionId\" not present")
	}
	respArg, err := c.impl.RestoreRevision(req.Context(), bearertoken.Token(authHeader), documentIdArg, revisionIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentServiceHandler) HandleCreatePreviewLink(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	siteIdArg, ok := pathParams["siteId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"siteId\" not present")
	}
	respArg, err := c.impl.CreatePreviewLink(req.Context(), bearertoken.Token(authHeader), siteIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentServiceHandler) HandleListNavItems(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	siteIdArg, ok := pathParams["siteId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"siteId\" not present")
	}
	respArg, err := c.impl.ListNavItems(req.Context(), bearertoken.Token(authHeader), siteIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentServiceHandler) HandlePutNavItems(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	siteIdArg, ok := pathParams["siteId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"siteId\" not present")
	}
	var requestArg PutNavItemsRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := c.impl.PutNavItems(req.Context(), bearertoken.Token(authHeader), siteIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}
