// Code generated by conjure-go. DO NOT EDIT.

package content

import (
	"context"
	"net/http"

	"github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/codecs"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/errors"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-server/httpserver"
	"github.com/palantir/pkg/bearertoken"
	werror "github.com/palantir/witchcraft-go-error"
	"github.com/palantir/witchcraft-go-server/v2/witchcraft/wresource"
	"github.com/palantir/witchcraft-go-server/v2/wrouter"
)

// Anonymous reads only (openfaithmap-web holds no session — D-AdminSurface). Always filters to published/unlisted; never discloses draft documents or their blocks.
type ContentPublicService interface {
	GetSite(ctx context.Context, congregationUnitIdArg string) (Site, error)
	ListPublicDocuments(ctx context.Context, siteIdArg string, kindArg *string, localeArg *string) (DocumentPage, error)
	// Content:DocumentNotFound if the document is draft or doesn't exist — never distinguishes the two.
	GetPublicBlocks(ctx context.Context, documentIdArg string) (BlockList, error)
	// Active block types only.
	ListBlockTypes(ctx context.Context) (BlockTypePage, error)
}

// RegisterRoutesContentPublicService registers handlers for the ContentPublicService endpoints with a witchcraft wrouter.
// This should typically be called in a witchcraft server's InitFunc.
// impl provides an implementation of each endpoint, which can assume the request parameters have been parsed
// in accordance with the Conjure specification.
func RegisterRoutesContentPublicService(router wrouter.Router, impl ContentPublicService, routerParams ...wrouter.RouteParam) error {
	handler := contentPublicServiceHandler{impl: impl}
	resource := wresource.New("contentpublicservice", router)
	if err := resource.Get("GetSite", "/content/v1/public/units/{congregationUnitId}/site", httpserver.NewJSONHandler(handler.HandleGetSite, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getSite route")
	}
	if err := resource.Get("ListPublicDocuments", "/content/v1/public/sites/{siteId}/documents", httpserver.NewJSONHandler(handler.HandleListPublicDocuments, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listPublicDocuments route")
	}
	if err := resource.Get("GetPublicBlocks", "/content/v1/public/documents/{documentId}/blocks", httpserver.NewJSONHandler(handler.HandleGetPublicBlocks, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getPublicBlocks route")
	}
	if err := resource.Get("ListBlockTypes", "/content/v1/public/block-types", httpserver.NewJSONHandler(handler.HandleListBlockTypes, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listBlockTypes route")
	}
	return nil
}

type contentPublicServiceHandler struct {
	impl ContentPublicService
}

func (c *contentPublicServiceHandler) HandleGetSite(rw http.ResponseWriter, req *http.Request) error {
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	congregationUnitIdArg, ok := pathParams["congregationUnitId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"congregationUnitId\" not present")
	}
	respArg, err := c.impl.GetSite(req.Context(), congregationUnitIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentPublicServiceHandler) HandleListPublicDocuments(rw http.ResponseWriter, req *http.Request) error {
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	siteIdArg, ok := pathParams["siteId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"siteId\" not present")
	}
	var kindArg *string
	if kindArgStr := req.URL.Query().Get("kind"); kindArgStr != "" {
		kindArgInternal := kindArgStr
		kindArg = &kindArgInternal
	}
	var localeArg *string
	if localeArgStr := req.URL.Query().Get("locale"); localeArgStr != "" {
		localeArgInternal := localeArgStr
		localeArg = &localeArgInternal
	}
	respArg, err := c.impl.ListPublicDocuments(req.Context(), siteIdArg, kindArg, localeArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentPublicServiceHandler) HandleGetPublicBlocks(rw http.ResponseWriter, req *http.Request) error {
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	documentIdArg, ok := pathParams["documentId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"documentId\" not present")
	}
	respArg, err := c.impl.GetPublicBlocks(req.Context(), documentIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentPublicServiceHandler) HandleListBlockTypes(rw http.ResponseWriter, req *http.Request) error {
	respArg, err := c.impl.ListBlockTypes(req.Context())
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

// Congregation site authoring: sites, documents (pages), blocks. Every write, and every read that must see draft state, is content.manage-gated — a live, target-scoped Authorize call against the site's own congregation unit (see file header). See docs/modules/content.md.
type ContentService interface {
	CreateSite(ctx context.Context, authHeader bearertoken.Token, requestArg CreateSiteRequest) (Site, error)
	UpdateSiteTheme(ctx context.Context, authHeader bearertoken.Token, siteIdArg string, requestArg UpdateSiteThemeRequest) (Site, error)
	// Admin read — returns documents in every state.
	ListDocuments(ctx context.Context, authHeader bearertoken.Token, siteIdArg string, kindArg *string, localeArg *string, stateArg *string) (DocumentPage, error)
	CreateDocument(ctx context.Context, authHeader bearertoken.Token, siteIdArg string, requestArg CreateDocumentRequest) (Document, error)
	UpdateDocument(ctx context.Context, authHeader bearertoken.Token, documentIdArg string, requestArg UpdateDocumentRequest) (Document, error)
	TransitionDocument(ctx context.Context, authHeader bearertoken.Token, documentIdArg string, requestArg TransitionDocumentRequest) (Document, error)
	// Admin read — works regardless of document state.
	GetBlocks(ctx context.Context, authHeader bearertoken.Token, documentIdArg string) (BlockList, error)
	// Full replace, validated against each referenced block type's json_schema.
	PutBlocks(ctx context.Context, authHeader bearertoken.Token, documentIdArg string, requestArg PutBlocksRequest) (BlockList, error)
}

// RegisterRoutesContentService registers handlers for the ContentService endpoints with a witchcraft wrouter.
// This should typically be called in a witchcraft server's InitFunc.
// impl provides an implementation of each endpoint, which can assume the request parameters have been parsed
// in accordance with the Conjure specification.
func RegisterRoutesContentService(router wrouter.Router, impl ContentService, routerParams ...wrouter.RouteParam) error {
	handler := contentServiceHandler{impl: impl}
	resource := wresource.New("contentservice", router)
	if err := resource.Post("CreateSite", "/content/v1/sites", httpserver.NewJSONHandler(handler.HandleCreateSite, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add createSite route")
	}
	if err := resource.Put("UpdateSiteTheme", "/content/v1/sites/{siteId}/theme", httpserver.NewJSONHandler(handler.HandleUpdateSiteTheme, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add updateSiteTheme route")
	}
	if err := resource.Get("ListDocuments", "/content/v1/sites/{siteId}/documents", httpserver.NewJSONHandler(handler.HandleListDocuments, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listDocuments route")
	}
	if err := resource.Post("CreateDocument", "/content/v1/sites/{siteId}/documents", httpserver.NewJSONHandler(handler.HandleCreateDocument, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add createDocument route")
	}
	if err := resource.Put("UpdateDocument", "/content/v1/documents/{documentId}", httpserver.NewJSONHandler(handler.HandleUpdateDocument, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add updateDocument route")
	}
	if err := resource.Post("TransitionDocument", "/content/v1/documents/{documentId}/transition", httpserver.NewJSONHandler(handler.HandleTransitionDocument, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add transitionDocument route")
	}
	if err := resource.Get("GetBlocks", "/content/v1/documents/{documentId}/blocks", httpserver.NewJSONHandler(handler.HandleGetBlocks, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getBlocks route")
	}
	if err := resource.Put("PutBlocks", "/content/v1/documents/{documentId}/blocks", httpserver.NewJSONHandler(handler.HandlePutBlocks, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add putBlocks route")
	}
	return nil
}

type contentServiceHandler struct {
	impl ContentService
}

func (c *contentServiceHandler) HandleCreateSite(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg CreateSiteRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := c.impl.CreateSite(req.Context(), bearertoken.Token(authHeader), requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentServiceHandler) HandleUpdateSiteTheme(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	siteIdArg, ok := pathParams["siteId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"siteId\" not present")
	}
	var requestArg UpdateSiteThemeRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := c.impl.UpdateSiteTheme(req.Context(), bearertoken.Token(authHeader), siteIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentServiceHandler) HandleListDocuments(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	siteIdArg, ok := pathParams["siteId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"siteId\" not present")
	}
	var kindArg *string
	if kindArgStr := req.URL.Query().Get("kind"); kindArgStr != "" {
		kindArgInternal := kindArgStr
		kindArg = &kindArgInternal
	}
	var localeArg *string
	if localeArgStr := req.URL.Query().Get("locale"); localeArgStr != "" {
		localeArgInternal := localeArgStr
		localeArg = &localeArgInternal
	}
	var stateArg *string
	if stateArgStr := req.URL.Query().Get("state"); stateArgStr != "" {
		stateArgInternal := stateArgStr
		stateArg = &stateArgInternal
	}
	respArg, err := c.impl.ListDocuments(req.Context(), bearertoken.Token(authHeader), siteIdArg, kindArg, localeArg, stateArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentServiceHandler) HandleCreateDocument(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	siteIdArg, ok := pathParams["siteId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"siteId\" not present")
	}
	var requestArg CreateDocumentRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := c.impl.CreateDocument(req.Context(), bearertoken.Token(authHeader), siteIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentServiceHandler) HandleUpdateDocument(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	documentIdArg, ok := pathParams["documentId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"documentId\" not present")
	}
	var requestArg UpdateDocumentRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := c.impl.UpdateDocument(req.Context(), bearertoken.Token(authHeader), documentIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentServiceHandler) HandleTransitionDocument(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	documentIdArg, ok := pathParams["documentId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"documentId\" not present")
	}
	var requestArg TransitionDocumentRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := c.impl.TransitionDocument(req.Context(), bearertoken.Token(authHeader), documentIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentServiceHandler) HandleGetBlocks(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	documentIdArg, ok := pathParams["documentId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"documentId\" not present")
	}
	respArg, err := c.impl.GetBlocks(req.Context(), bearertoken.Token(authHeader), documentIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (c *contentServiceHandler) HandlePutBlocks(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	documentIdArg, ok := pathParams["documentId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"documentId\" not present")
	}
	var requestArg PutBlocksRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := c.impl.PutBlocks(req.Context(), bearertoken.Token(authHeader), documentIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}
