// Code generated by conjure-go. DO NOT EDIT.

package content

import (
	"github.com/palantir/pkg/datetime"
	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
)

type Block struct {
	Id            string            `json:"id"`
	DocumentId    string            `json:"documentId"`
	BlockTypeCode string            `json:"blockTypeCode"`
	Position      int               `json:"position"`
	Data          interface{}       `json:"data"`
	CreatedAt     datetime.DateTime `json:"createdAt"`
	UpdatedAt     datetime.DateTime `json:"updatedAt"`
}

func (o Block) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *Block) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type BlockInput struct {
	BlockTypeCode string      `json:"blockTypeCode"`
	Position      int         `json:"position"`
	Data          interface{} `json:"data"`
}

func (o BlockInput) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *BlockInput) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type BlockList struct {
	Blocks []Block `json:"blocks"`
}

func (o BlockList) MarshalJSON() ([]byte, error) {
	if o.Blocks == nil {
		o.Blocks = make([]Block, 0)
	}
	type _tmpBlockList BlockList
	return safejson.Marshal(_tmpBlockList(o))
}

func (o *BlockList) UnmarshalJSON(data []byte) error {
	type _tmpBlockList BlockList
	var rawBlockList _tmpBlockList
	if err := safejson.Unmarshal(data, &rawBlockList); err != nil {
		return err
	}
	if rawBlockList.Blocks == nil {
		rawBlockList.Blocks = make([]Block, 0)
	}
	*o = BlockList(rawBlockList)
	return nil
}

func (o BlockList) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *BlockList) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type BlockType struct {
	Id         string          `json:"id"`
	Code       string          `json:"code"`
	Name       string          `json:"name"`
	JsonSchema interface{}     `json:"jsonSchema"`
	Status     BlockTypeStatus `json:"status"`
	SortOrder  int             `json:"sortOrder"`
}

func (o BlockType) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *BlockType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type BlockTypePage struct {
	BlockTypes []BlockType `json:"blockTypes"`
}

func (o BlockTypePage) MarshalJSON() ([]byte, error) {
	if o.BlockTypes == nil {
		o.BlockTypes = make([]BlockType, 0)
	}
	type _tmpBlockTypePage BlockTypePage
	return safejson.Marshal(_tmpBlockTypePage(o))
}

func (o *BlockTypePage) UnmarshalJSON(data []byte) error {
	type _tmpBlockTypePage BlockTypePage
	var rawBlockTypePage _tmpBlockTypePage
	if err := safejson.Unmarshal(data, &rawBlockTypePage); err != nil {
		return err
	}
	if rawBlockTypePage.BlockTypes == nil {
		rawBlockTypePage.BlockTypes = make([]BlockType, 0)
	}
	*o = BlockTypePage(rawBlockTypePage)
	return nil
}

func (o BlockTypePage) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *BlockTypePage) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type CreateDocumentRequest struct {
	// EVENT requires eventStartsAt to be set (Content:EventMissingStart otherwise).
	Kind DocumentKind `json:"kind"`
	// Omit to start a new translation group; set to join an existing one as another locale variant.
	TranslationGroupId *string `json:"translationGroupId,omitempty"`
	Locale             string  `json:"locale"`
	ParentDocumentId   *string `json:"parentDocumentId,omitempty"`
	Slug               string  `json:"slug"`
	// EVENT only. Required when kind is EVENT; ignored for PAGE/POST.
	EventStartsAt        *datetime.DateTime `json:"eventStartsAt,omitempty"`
	EventEndsAt          *datetime.DateTime `json:"eventEndsAt,omitempty"`
	EventRecurrenceRrule *string            `json:"eventRecurrenceRrule,omitempty"`
}

func (o CreateDocumentRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *CreateDocumentRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type CreateSiteRequest struct {
	CongregationUnitId string `json:"congregationUnitId"`
	// Admin-chosen, probed for uniqueness at write time (U5) — Content:SlugTaken on collision.
	Slug string `json:"slug"`
}

func (o CreateSiteRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *CreateSiteRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type Document struct {
	Id     string       `json:"id"`
	SiteId string       `json:"siteId"`
	Kind   DocumentKind `json:"kind"`
	// Shared across every locale variant of one conceptual document.
	TranslationGroupId string `json:"translationGroupId"`
	Locale             string `json:"locale"`
	// Pages only, up to 3 levels deep (app-enforced, not a DB constraint).
	ParentDocumentId     *string            `json:"parentDocumentId,omitempty"`
	Slug                 string             `json:"slug"`
	State                DocumentState      `json:"state"`
	PublishedAt          *datetime.DateTime `json:"publishedAt,omitempty"`
	EventStartsAt        *datetime.DateTime `json:"eventStartsAt,omitempty"`
	EventEndsAt          *datetime.DateTime `json:"eventEndsAt,omitempty"`
	EventRecurrenceRrule *string            `json:"eventRecurrenceRrule,omitempty"`
	CreatedAt            datetime.DateTime  `json:"createdAt"`
	UpdatedAt            datetime.DateTime  `json:"updatedAt"`
}

func (o Document) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *Document) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type DocumentPage struct {
	Documents []Document `json:"documents"`
}

func (o DocumentPage) MarshalJSON() ([]byte, error) {
	if o.Documents == nil {
		o.Documents = make([]Document, 0)
	}
	type _tmpDocumentPage DocumentPage
	return safejson.Marshal(_tmpDocumentPage(o))
}

func (o *DocumentPage) UnmarshalJSON(data []byte) error {
	type _tmpDocumentPage DocumentPage
	var rawDocumentPage _tmpDocumentPage
	if err := safejson.Unmarshal(data, &rawDocumentPage); err != nil {
		return err
	}
	if rawDocumentPage.Documents == nil {
		rawDocumentPage.Documents = make([]Document, 0)
	}
	*o = DocumentPage(rawDocumentPage)
	return nil
}

func (o DocumentPage) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *DocumentPage) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type PutBlocksRequest struct {
	Blocks []BlockInput `json:"blocks"`
}

func (o PutBlocksRequest) MarshalJSON() ([]byte, error) {
	if o.Blocks == nil {
		o.Blocks = make([]BlockInput, 0)
	}
	type _tmpPutBlocksRequest PutBlocksRequest
	return safejson.Marshal(_tmpPutBlocksRequest(o))
}

func (o *PutBlocksRequest) UnmarshalJSON(data []byte) error {
	type _tmpPutBlocksRequest PutBlocksRequest
	var rawPutBlocksRequest _tmpPutBlocksRequest
	if err := safejson.Unmarshal(data, &rawPutBlocksRequest); err != nil {
		return err
	}
	if rawPutBlocksRequest.Blocks == nil {
		rawPutBlocksRequest.Blocks = make([]BlockInput, 0)
	}
	*o = PutBlocksRequest(rawPutBlocksRequest)
	return nil
}

func (o PutBlocksRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *PutBlocksRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type Site struct {
	Id string `json:"id"`
	// The go-oikumenea Unit RID this site belongs to (opaque foreign value).
	CongregationUnitId string `json:"congregationUnitId"`
	Slug               string `json:"slug"`
	// Accent color, font pairing, header layout — data, never a per-tenant code fork.
	Theme     interface{}       `json:"theme"`
	CreatedAt datetime.DateTime `json:"createdAt"`
	UpdatedAt datetime.DateTime `json:"updatedAt"`
}

func (o Site) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *Site) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type TransitionDocumentRequest struct {
	Action DocumentTransitionAction `json:"action"`
}

func (o TransitionDocumentRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *TransitionDocumentRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type UpdateDocumentRequest struct {
	Slug *string `json:"slug,omitempty"`
	// Set a new parent. Omit (with clearParent false) to leave the parent unchanged.
	ParentDocumentId *string `json:"parentDocumentId,omitempty"`
	// Set true (with parentDocumentId omitted) to move the page to top level.
	ClearParent bool `json:"clearParent"`
}

func (o UpdateDocumentRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *UpdateDocumentRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type UpdateSiteThemeRequest struct {
	Theme interface{} `json:"theme"`
}

func (o UpdateSiteThemeRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *UpdateSiteThemeRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}
