// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: directory.sql

package directorysql

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceMoveJob = `-- name: AdvanceMoveJob :one
UPDATE openfaithmap.directory_unit_move_jobs
SET status = $1, error = NULL
WHERE id = $2
RETURNING id, graph_id, unit_id, old_parent_unit_id, new_parent_unit_id, status, performed_by_person_id, error, created_at, updated_at
`

type AdvanceMoveJobParams struct {
	Status string
	ID     string
}

func (q *Queries) AdvanceMoveJob(ctx context.Context, arg AdvanceMoveJobParams) (OpenfaithmapDirectoryUnitMoveJob, error) {
	row := q.db.QueryRow(ctx, advanceMoveJob, arg.Status, arg.ID)
	var i OpenfaithmapDirectoryUnitMoveJob
	err := row.Scan(
		&i.ID,
		&i.GraphID,
		&i.UnitID,
		&i.OldParentUnitID,
		&i.NewParentUnitID,
		&i.Status,
		&i.PerformedByPersonID,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const closureHasPath = `-- name: ClosureHasPath :one
SELECT EXISTS(
	SELECT 1 FROM openfaithmap.directory_unit_closure
	WHERE graph_id = $1 AND ancestor_id = $2 AND descendant_id = $3
)
`

type ClosureHasPathParams struct {
	GraphID      string
	AncestorID   string
	DescendantID string
}

func (q *Queries) ClosureHasPath(ctx context.Context, arg ClosureHasPathParams) (bool, error) {
	row := q.db.QueryRow(ctx, closureHasPath, arg.GraphID, arg.AncestorID, arg.DescendantID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createMoveJob = `-- name: CreateMoveJob :one
INSERT INTO openfaithmap.directory_unit_move_jobs
	(graph_id, unit_id, old_parent_unit_id, new_parent_unit_id, performed_by_person_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, graph_id, unit_id, old_parent_unit_id, new_parent_unit_id, status, performed_by_person_id, error, created_at, updated_at
`

type CreateMoveJobParams struct {
	GraphID             string
	UnitID              string
	OldParentUnitID     string
	NewParentUnitID     string
	PerformedByPersonID string
}

func (q *Queries) CreateMoveJob(ctx context.Context, arg CreateMoveJobParams) (OpenfaithmapDirectoryUnitMoveJob, error) {
	row := q.db.QueryRow(ctx, createMoveJob,
		arg.GraphID,
		arg.UnitID,
		arg.OldParentUnitID,
		arg.NewParentUnitID,
		arg.PerformedByPersonID,
	)
	var i OpenfaithmapDirectoryUnitMoveJob
	err := row.Scan(
		&i.ID,
		&i.GraphID,
		&i.UnitID,
		&i.OldParentUnitID,
		&i.NewParentUnitID,
		&i.Status,
		&i.PerformedByPersonID,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClosureForGraph = `-- name: DeleteClosureForGraph :exec
DELETE FROM openfaithmap.directory_unit_closure WHERE graph_id = $1
`

func (q *Queries) DeleteClosureForGraph(ctx context.Context, graphID string) error {
	_, err := q.db.Exec(ctx, deleteClosureForGraph, graphID)
	return err
}

const deleteClosureSlice = `-- name: DeleteClosureSlice :exec
WITH anc AS (
  SELECT tc.ancestor_id AS u FROM openfaithmap.directory_unit_closure tc
  WHERE tc.graph_id = $1 AND tc.descendant_id = $2
  UNION SELECT $2::uuid
),
dsc AS (
  SELECT tc.descendant_id AS u FROM openfaithmap.directory_unit_closure tc
  WHERE tc.graph_id = $1 AND tc.ancestor_id = $3
  UNION SELECT $3::uuid
)
DELETE FROM openfaithmap.directory_unit_closure tc
WHERE tc.graph_id = $1
  AND tc.ancestor_id   IN (SELECT u FROM anc)
  AND tc.descendant_id IN (SELECT u FROM dsc)
`

type DeleteClosureSliceParams struct {
	GraphID  string
	ParentID string
	ChildID  string
}

func (q *Queries) DeleteClosureSlice(ctx context.Context, arg DeleteClosureSliceParams) error {
	_, err := q.db.Exec(ctx, deleteClosureSlice, arg.GraphID, arg.ParentID, arg.ChildID)
	return err
}

const deleteEdge = `-- name: DeleteEdge :execrows
DELETE FROM openfaithmap.directory_unit_edges
WHERE graph_id = $1 AND parent_id = $2 AND child_id = $3
`

type DeleteEdgeParams struct {
	GraphID  string
	ParentID string
	ChildID  string
}

func (q *Queries) DeleteEdge(ctx context.Context, arg DeleteEdgeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEdge, arg.GraphID, arg.ParentID, arg.ChildID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const extendClosureForEdge = `-- name: ExtendClosureForEdge :exec
INSERT INTO openfaithmap.directory_unit_closure (graph_id, ancestor_id, descendant_id, depth)
SELECT $1::uuid, anc.ancestor_id, dsc.descendant_id, anc.depth + dsc.depth + 1
FROM openfaithmap.directory_unit_closure anc
JOIN openfaithmap.directory_unit_closure dsc
  ON dsc.graph_id = $1 AND dsc.ancestor_id = $2
WHERE anc.graph_id = $1 AND anc.descendant_id = $3
ON CONFLICT (graph_id, ancestor_id, descendant_id)
DO UPDATE SET depth = LEAST(openfaithmap.directory_unit_closure.depth, EXCLUDED.depth)
`

type ExtendClosureForEdgeParams struct {
	GraphID  string
	ChildID  string
	ParentID string
}

func (q *Queries) ExtendClosureForEdge(ctx context.Context, arg ExtendClosureForEdgeParams) error {
	_, err := q.db.Exec(ctx, extendClosureForEdge, arg.GraphID, arg.ChildID, arg.ParentID)
	return err
}

const failMoveJob = `-- name: FailMoveJob :one
UPDATE openfaithmap.directory_unit_move_jobs
SET status = 'FAILED', error = $1
WHERE id = $2
RETURNING id, graph_id, unit_id, old_parent_unit_id, new_parent_unit_id, status, performed_by_person_id, error, created_at, updated_at
`

type FailMoveJobParams struct {
	Error pgtype.Text
	ID    string
}

func (q *Queries) FailMoveJob(ctx context.Context, arg FailMoveJobParams) (OpenfaithmapDirectoryUnitMoveJob, error) {
	row := q.db.QueryRow(ctx, failMoveJob, arg.Error, arg.ID)
	var i OpenfaithmapDirectoryUnitMoveJob
	err := row.Scan(
		&i.ID,
		&i.GraphID,
		&i.UnitID,
		&i.OldParentUnitID,
		&i.NewParentUnitID,
		&i.Status,
		&i.PerformedByPersonID,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGraphByCode = `-- name: GetGraphByCode :one
SELECT id, code, name, is_default, is_authority_bearing
FROM openfaithmap.directory_graphs
WHERE code = $1 AND deleted_at IS NULL
`

type GetGraphByCodeRow struct {
	ID                 string
	Code               string
	Name               string
	IsDefault          bool
	IsAuthorityBearing bool
}

func (q *Queries) GetGraphByCode(ctx context.Context, code string) (GetGraphByCodeRow, error) {
	row := q.db.QueryRow(ctx, getGraphByCode, code)
	var i GetGraphByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsDefault,
		&i.IsAuthorityBearing,
	)
	return i, err
}

const getGraphByID = `-- name: GetGraphByID :one
SELECT id, code, name, is_default, is_authority_bearing
FROM openfaithmap.directory_graphs
WHERE id = $1 AND deleted_at IS NULL
`

type GetGraphByIDRow struct {
	ID                 string
	Code               string
	Name               string
	IsDefault          bool
	IsAuthorityBearing bool
}

func (q *Queries) GetGraphByID(ctx context.Context, id string) (GetGraphByIDRow, error) {
	row := q.db.QueryRow(ctx, getGraphByID, id)
	var i GetGraphByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsDefault,
		&i.IsAuthorityBearing,
	)
	return i, err
}

const getLatestMoveJob = `-- name: GetLatestMoveJob :one
SELECT id, graph_id, unit_id, old_parent_unit_id, new_parent_unit_id, status, performed_by_person_id, error, created_at, updated_at
FROM openfaithmap.directory_unit_move_jobs
WHERE graph_id = $1 AND unit_id = $2
ORDER BY created_at DESC LIMIT 1
`

type GetLatestMoveJobParams struct {
	GraphID string
	UnitID  string
}

func (q *Queries) GetLatestMoveJob(ctx context.Context, arg GetLatestMoveJobParams) (OpenfaithmapDirectoryUnitMoveJob, error) {
	row := q.db.QueryRow(ctx, getLatestMoveJob, arg.GraphID, arg.UnitID)
	var i OpenfaithmapDirectoryUnitMoveJob
	err := row.Scan(
		&i.ID,
		&i.GraphID,
		&i.UnitID,
		&i.OldParentUnitID,
		&i.NewParentUnitID,
		&i.Status,
		&i.PerformedByPersonID,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLiveMoveJob = `-- name: GetLiveMoveJob :one
SELECT id, graph_id, unit_id, old_parent_unit_id, new_parent_unit_id, status, performed_by_person_id, error, created_at, updated_at
FROM openfaithmap.directory_unit_move_jobs
WHERE graph_id = $1 AND unit_id = $2 AND status NOT IN ('FAILED', 'VERIFIED')
`

type GetLiveMoveJobParams struct {
	GraphID string
	UnitID  string
}

func (q *Queries) GetLiveMoveJob(ctx context.Context, arg GetLiveMoveJobParams) (OpenfaithmapDirectoryUnitMoveJob, error) {
	row := q.db.QueryRow(ctx, getLiveMoveJob, arg.GraphID, arg.UnitID)
	var i OpenfaithmapDirectoryUnitMoveJob
	err := row.Scan(
		&i.ID,
		&i.GraphID,
		&i.UnitID,
		&i.OldParentUnitID,
		&i.NewParentUnitID,
		&i.Status,
		&i.PerformedByPersonID,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnit = `-- name: GetUnit :one
SELECT id, code, name, level, state, metadata, created_at, updated_at
FROM openfaithmap.directory_units
WHERE id = $1 AND deleted_at IS NULL
`

type GetUnitRow struct {
	ID        string
	Code      pgtype.Text
	Name      string
	Level     pgtype.Int2
	State     string
	Metadata  json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetUnit(ctx context.Context, id string) (GetUnitRow, error) {
	row := q.db.QueryRow(ctx, getUnit, id)
	var i GetUnitRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Level,
		&i.State,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnitByCode = `-- name: GetUnitByCode :one
SELECT id, code, name, level, state, metadata, created_at, updated_at
FROM openfaithmap.directory_units
WHERE code = $1 AND deleted_at IS NULL
`

type GetUnitByCodeRow struct {
	ID        string
	Code      pgtype.Text
	Name      string
	Level     pgtype.Int2
	State     string
	Metadata  json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

// Added for the seed-ID refactor (internal/platform/seed.Resolve): directory_units.code carries a
// unique-while-active index (directory_units_code_active_idx) the same shape as
// authz_roles_code_active_idx — mirrors GetGraphByCode's own shape.
func (q *Queries) GetUnitByCode(ctx context.Context, code pgtype.Text) (GetUnitByCodeRow, error) {
	row := q.db.QueryRow(ctx, getUnitByCode, code)
	var i GetUnitByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Level,
		&i.State,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasChildren = `-- name: HasChildren :one
SELECT EXISTS(
	SELECT 1 FROM openfaithmap.directory_unit_edges e
	JOIN openfaithmap.directory_units u ON u.id = e.child_id AND u.deleted_at IS NULL
	WHERE e.parent_id = $1
)
`

func (q *Queries) HasChildren(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, hasChildren, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertEdge = `-- name: InsertEdge :one
INSERT INTO openfaithmap.directory_unit_edges (graph_id, parent_id, child_id)
VALUES ($1, $2, $3)
RETURNING id, parent_id, child_id, created_at
`

type InsertEdgeParams struct {
	GraphID  string
	ParentID string
	ChildID  string
}

type InsertEdgeRow struct {
	ID        string
	ParentID  string
	ChildID   string
	CreatedAt time.Time
}

func (q *Queries) InsertEdge(ctx context.Context, arg InsertEdgeParams) (InsertEdgeRow, error) {
	row := q.db.QueryRow(ctx, insertEdge, arg.GraphID, arg.ParentID, arg.ChildID)
	var i InsertEdgeRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.ChildID,
		&i.CreatedAt,
	)
	return i, err
}

const insertUnit = `-- name: InsertUnit :one
INSERT INTO openfaithmap.directory_units (code, name, level, state, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code, name, level, state, metadata, created_at, updated_at
`

type InsertUnitParams struct {
	Code     pgtype.Text
	Name     string
	Level    pgtype.Int2
	State    string
	Metadata json.RawMessage
}

type InsertUnitRow struct {
	ID        string
	Code      pgtype.Text
	Name      string
	Level     pgtype.Int2
	State     string
	Metadata  json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertUnit(ctx context.Context, arg InsertUnitParams) (InsertUnitRow, error) {
	row := q.db.QueryRow(ctx, insertUnit,
		arg.Code,
		arg.Name,
		arg.Level,
		arg.State,
		arg.Metadata,
	)
	var i InsertUnitRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Level,
		&i.State,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUnitWithID = `-- name: InsertUnitWithID :one
INSERT INTO openfaithmap.directory_units (id, code, name, level, state, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, code, name, level, state, metadata, created_at, updated_at
`

type InsertUnitWithIDParams struct {
	ID       string
	Code     pgtype.Text
	Name     string
	Level    pgtype.Int2
	State    string
	Metadata json.RawMessage
}

type InsertUnitWithIDRow struct {
	ID        string
	Code      pgtype.Text
	Name      string
	Level     pgtype.Int2
	State     string
	Metadata  json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) InsertUnitWithID(ctx context.Context, arg InsertUnitWithIDParams) (InsertUnitWithIDRow, error) {
	row := q.db.QueryRow(ctx, insertUnitWithID,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Level,
		arg.State,
		arg.Metadata,
	)
	var i InsertUnitWithIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Level,
		&i.State,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAncestors = `-- name: ListAncestors :many
SELECT u.id, COALESCE(u.code, '') AS code, u.name, c.depth
FROM openfaithmap.directory_unit_closure c
JOIN openfaithmap.directory_units u ON u.id = c.ancestor_id AND u.deleted_at IS NULL
WHERE c.graph_id = $1 AND c.descendant_id = $2 AND c.depth > 0
ORDER BY c.depth, u.code
`

type ListAncestorsParams struct {
	GraphID string
	UnitID  string
}

type ListAncestorsRow struct {
	ID    string
	Code  string
	Name  string
	Depth int32
}

func (q *Queries) ListAncestors(ctx context.Context, arg ListAncestorsParams) ([]ListAncestorsRow, error) {
	rows, err := q.db.Query(ctx, listAncestors, arg.GraphID, arg.UnitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAncestorsRow
	for rows.Next() {
		var i ListAncestorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildren = `-- name: ListChildren :many
SELECT u.id, u.code, u.name, u.level, u.state, u.metadata, u.created_at, u.updated_at
FROM openfaithmap.directory_unit_edges e
JOIN openfaithmap.directory_units u ON u.id = e.child_id AND u.deleted_at IS NULL
WHERE e.graph_id = $1 AND e.parent_id = $2
ORDER BY u.name
LIMIT $3
`

type ListChildrenParams struct {
	GraphID    string
	UnitID     string
	LimitCount int32
}

type ListChildrenRow struct {
	ID        string
	Code      pgtype.Text
	Name      string
	Level     pgtype.Int2
	State     string
	Metadata  json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

// One-hop direct children via the edge table (not the closure table — M12.7's admin hierarchy
// tree loads one level at a time, so this deliberately doesn't reuse ListDescendants' depth>0
// closure query, which returns the whole subtree).
func (q *Queries) ListChildren(ctx context.Context, arg ListChildrenParams) ([]ListChildrenRow, error) {
	rows, err := q.db.Query(ctx, listChildren, arg.GraphID, arg.UnitID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChildrenRow
	for rows.Next() {
		var i ListChildrenRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Level,
			&i.State,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDescendants = `-- name: ListDescendants :many
SELECT u.id, COALESCE(u.code, '') AS code, u.name, c.depth
FROM openfaithmap.directory_unit_closure c
JOIN openfaithmap.directory_units u ON u.id = c.descendant_id AND u.deleted_at IS NULL
WHERE c.graph_id = $1 AND c.ancestor_id = $2 AND c.depth > 0
ORDER BY c.descendant_id
LIMIT $3
`

type ListDescendantsParams struct {
	GraphID    string
	UnitID     string
	LimitCount int32
}

type ListDescendantsRow struct {
	ID    string
	Code  string
	Name  string
	Depth int32
}

func (q *Queries) ListDescendants(ctx context.Context, arg ListDescendantsParams) ([]ListDescendantsRow, error) {
	rows, err := q.db.Query(ctx, listDescendants, arg.GraphID, arg.UnitID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDescendantsRow
	for rows.Next() {
		var i ListDescendantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGraphs = `-- name: ListGraphs :many
SELECT id, code, name, is_default, is_authority_bearing
FROM openfaithmap.directory_graphs WHERE deleted_at IS NULL ORDER BY code
`

type ListGraphsRow struct {
	ID                 string
	Code               string
	Name               string
	IsDefault          bool
	IsAuthorityBearing bool
}

func (q *Queries) ListGraphs(ctx context.Context) ([]ListGraphsRow, error) {
	rows, err := q.db.Query(ctx, listGraphs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGraphsRow
	for rows.Next() {
		var i ListGraphsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.IsDefault,
			&i.IsAuthorityBearing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGraphForClosure = `-- name: LockGraphForClosure :one
SELECT id FROM openfaithmap.directory_graphs WHERE id = $1 FOR NO KEY UPDATE
`

func (q *Queries) LockGraphForClosure(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockGraphForClosure, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const mintUnitID = `-- name: MintUnitID :one
SELECT openfaithmap.new_id(3, 1, 1)::text AS id
`

func (q *Queries) MintUnitID(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, mintUnitID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const pruneClosureSelfRows = `-- name: PruneClosureSelfRows :exec
DELETE FROM openfaithmap.directory_unit_closure tc
WHERE tc.graph_id = $1
  AND tc.ancestor_id = tc.descendant_id
  AND tc.ancestor_id IN ($2::uuid, $3::uuid)
  AND NOT EXISTS (
    SELECT 1 FROM openfaithmap.directory_unit_edges e
    WHERE e.graph_id = $1 AND (e.parent_id = tc.ancestor_id OR e.child_id = tc.ancestor_id)
  )
`

type PruneClosureSelfRowsParams struct {
	GraphID  string
	ParentID string
	ChildID  string
}

func (q *Queries) PruneClosureSelfRows(ctx context.Context, arg PruneClosureSelfRowsParams) error {
	_, err := q.db.Exec(ctx, pruneClosureSelfRows, arg.GraphID, arg.ParentID, arg.ChildID)
	return err
}

const rebuildClosureForGraph = `-- name: RebuildClosureForGraph :exec
WITH RECURSIVE
nodes AS (
  SELECT parent_id AS u FROM openfaithmap.directory_unit_edges e0 WHERE e0.graph_id = $1
  UNION SELECT child_id FROM openfaithmap.directory_unit_edges e1 WHERE e1.graph_id = $1
),
reach AS (
  SELECT u AS ancestor_id, u AS descendant_id, 0 AS depth FROM nodes
  UNION ALL
  SELECT r.ancestor_id, e.child_id, r.depth + 1
  FROM reach r
  JOIN openfaithmap.directory_unit_edges e ON e.graph_id = $1 AND e.parent_id = r.descendant_id
)
INSERT INTO openfaithmap.directory_unit_closure (graph_id, ancestor_id, descendant_id, depth)
SELECT $1::uuid, ancestor_id, descendant_id, min(depth)::int
FROM reach GROUP BY ancestor_id, descendant_id
`

func (q *Queries) RebuildClosureForGraph(ctx context.Context, graphID string) error {
	_, err := q.db.Exec(ctx, rebuildClosureForGraph, graphID)
	return err
}

const rederiveClosureSlice = `-- name: RederiveClosureSlice :exec
WITH RECURSIVE
anc AS (
  SELECT tc.ancestor_id AS u FROM openfaithmap.directory_unit_closure tc
  WHERE tc.graph_id = $1 AND tc.descendant_id = $2
  UNION SELECT $2::uuid
),
dsc AS (
  SELECT tc.descendant_id AS u FROM openfaithmap.directory_unit_closure tc
  WHERE tc.graph_id = $1 AND tc.ancestor_id = $3
  UNION SELECT $3::uuid
),
walk AS (
  SELECT a.u AS ancestor_id, a.u AS node, 0 AS depth FROM anc a
  UNION ALL
  SELECT w.ancestor_id, e.child_id, w.depth + 1
  FROM walk w
  JOIN openfaithmap.directory_unit_edges e ON e.graph_id = $1 AND e.parent_id = w.node
  WHERE w.node IN (SELECT u FROM anc)
),
pairs AS (
  SELECT w.ancestor_id, tc.descendant_id, w.depth + tc.depth AS depth
  FROM walk w
  JOIN openfaithmap.directory_unit_closure tc ON tc.graph_id = $1 AND tc.ancestor_id = w.node
  WHERE w.node NOT IN (SELECT u FROM anc)
    AND tc.descendant_id IN (SELECT u FROM dsc)
)
INSERT INTO openfaithmap.directory_unit_closure (graph_id, ancestor_id, descendant_id, depth)
SELECT $1::uuid, ancestor_id, descendant_id, min(depth)::int
FROM pairs GROUP BY ancestor_id, descendant_id
`

type RederiveClosureSliceParams struct {
	GraphID  string
	ParentID string
	ChildID  string
}

func (q *Queries) RederiveClosureSlice(ctx context.Context, arg RederiveClosureSliceParams) error {
	_, err := q.db.Exec(ctx, rederiveClosureSlice, arg.GraphID, arg.ParentID, arg.ChildID)
	return err
}

const searchUnits = `-- name: SearchUnits :many
SELECT id, code, name, level, state, metadata, created_at, updated_at
FROM openfaithmap.directory_units
WHERE deleted_at IS NULL
  AND ($1::text = '' OR code ILIKE '%' || $1::text || '%' OR name ILIKE '%' || $1::text || '%')
ORDER BY name
LIMIT $2
`

type SearchUnitsParams struct {
	Query      string
	LimitCount int32
}

type SearchUnitsRow struct {
	ID        string
	Code      pgtype.Text
	Name      string
	Level     pgtype.Int2
	State     string
	Metadata  json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) SearchUnits(ctx context.Context, arg SearchUnitsParams) ([]SearchUnitsRow, error) {
	rows, err := q.db.Query(ctx, searchUnits, arg.Query, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUnitsRow
	for rows.Next() {
		var i SearchUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Level,
			&i.State,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedClosureSelfRows = `-- name: SeedClosureSelfRows :exec
INSERT INTO openfaithmap.directory_unit_closure (graph_id, ancestor_id, descendant_id, depth)
VALUES ($1, $2, $2, 0), ($1, $3, $3, 0)
ON CONFLICT DO NOTHING
`

type SeedClosureSelfRowsParams struct {
	GraphID  string
	ParentID string
	ChildID  string
}

func (q *Queries) SeedClosureSelfRows(ctx context.Context, arg SeedClosureSelfRowsParams) error {
	_, err := q.db.Exec(ctx, seedClosureSelfRows, arg.GraphID, arg.ParentID, arg.ChildID)
	return err
}

const setUnitState = `-- name: SetUnitState :one
UPDATE openfaithmap.directory_units
SET state = $1
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, code, name, level, state, metadata, created_at, updated_at
`

type SetUnitStateParams struct {
	State string
	ID    string
}

type SetUnitStateRow struct {
	ID        string
	Code      pgtype.Text
	Name      string
	Level     pgtype.Int2
	State     string
	Metadata  json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) SetUnitState(ctx context.Context, arg SetUnitStateParams) (SetUnitStateRow, error) {
	row := q.db.QueryRow(ctx, setUnitState, arg.State, arg.ID)
	var i SetUnitStateRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Level,
		&i.State,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteUnit = `-- name: SoftDeleteUnit :one
UPDATE openfaithmap.directory_units
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, code, name, level, state, metadata, created_at, updated_at
`

type SoftDeleteUnitRow struct {
	ID        string
	Code      pgtype.Text
	Name      string
	Level     pgtype.Int2
	State     string
	Metadata  json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) SoftDeleteUnit(ctx context.Context, id string) (SoftDeleteUnitRow, error) {
	row := q.db.QueryRow(ctx, softDeleteUnit, id)
	var i SoftDeleteUnitRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Level,
		&i.State,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUnit = `-- name: UpdateUnit :one
UPDATE openfaithmap.directory_units
SET name = $1, code = $2, level = $3
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, code, name, level, state, metadata, created_at, updated_at
`

type UpdateUnitParams struct {
	Name  string
	Code  pgtype.Text
	Level pgtype.Int2
	ID    string
}

type UpdateUnitRow struct {
	ID        string
	Code      pgtype.Text
	Name      string
	Level     pgtype.Int2
	State     string
	Metadata  json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpdateUnit(ctx context.Context, arg UpdateUnitParams) (UpdateUnitRow, error) {
	row := q.db.QueryRow(ctx, updateUnit,
		arg.Name,
		arg.Code,
		arg.Level,
		arg.ID,
	)
	var i UpdateUnitRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Level,
		&i.State,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertClosureStatus = `-- name: UpsertClosureStatus :exec
INSERT INTO openfaithmap.directory_closure_status (graph_id, missing_count, extra_count, in_drift, sample, last_checked_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (graph_id) DO UPDATE SET
  missing_count = EXCLUDED.missing_count, extra_count = EXCLUDED.extra_count,
  in_drift = EXCLUDED.in_drift, sample = EXCLUDED.sample, last_checked_at = now()
`

type UpsertClosureStatusParams struct {
	GraphID      string
	MissingCount int32
	ExtraCount   int32
	InDrift      bool
	Sample       []byte
}

func (q *Queries) UpsertClosureStatus(ctx context.Context, arg UpsertClosureStatusParams) error {
	_, err := q.db.Exec(ctx, upsertClosureStatus,
		arg.GraphID,
		arg.MissingCount,
		arg.ExtraCount,
		arg.InDrift,
		arg.Sample,
	)
	return err
}

const verifyClosureForGraph = `-- name: VerifyClosureForGraph :one
WITH RECURSIVE
nodes AS (
  SELECT parent_id AS u FROM openfaithmap.directory_unit_edges e0 WHERE e0.graph_id = $1
  UNION SELECT child_id FROM openfaithmap.directory_unit_edges e1 WHERE e1.graph_id = $1
),
reach AS (
  SELECT u AS ancestor_id, u AS descendant_id, 0 AS depth FROM nodes
  UNION ALL
  SELECT r.ancestor_id, e.child_id, r.depth + 1
  FROM reach r
  JOIN openfaithmap.directory_unit_edges e ON e.graph_id = $1 AND e.parent_id = r.descendant_id
),
expected AS (
  SELECT ancestor_id, descendant_id, min(depth)::int AS depth FROM reach GROUP BY ancestor_id, descendant_id
),
stored AS (
  SELECT tc.ancestor_id, tc.descendant_id, tc.depth FROM openfaithmap.directory_unit_closure tc WHERE tc.graph_id = $1
),
missing AS (SELECT ancestor_id, descendant_id, depth FROM expected EXCEPT SELECT ancestor_id, descendant_id, depth FROM stored),
extra   AS (SELECT ancestor_id, descendant_id, depth FROM stored   EXCEPT SELECT ancestor_id, descendant_id, depth FROM expected)
SELECT
  (SELECT count(*) FROM missing)::int AS missing_count,
  (SELECT count(*) FROM extra)::int AS extra_count,
  (SELECT coalesce(jsonb_agg(s), '[]'::jsonb) FROM (
     (SELECT 'missing'::text AS kind, ancestor_id, descendant_id FROM missing LIMIT 5)
     UNION ALL
     (SELECT 'extra'::text AS kind, ancestor_id, descendant_id FROM extra LIMIT 5)
   ) s)::jsonb AS sample
`

type VerifyClosureForGraphRow struct {
	MissingCount int32
	ExtraCount   int32
	Sample       json.RawMessage
}

func (q *Queries) VerifyClosureForGraph(ctx context.Context, graphID string) (VerifyClosureForGraphRow, error) {
	row := q.db.QueryRow(ctx, verifyClosureForGraph, graphID)
	var i VerifyClosureForGraphRow
	err := row.Scan(&i.MissingCount, &i.ExtraCount, &i.Sample)
	return i, err
}
