// Code generated by conjure-go. DO NOT EDIT.

package vouching

import (
	"context"
	"net/http"
	"strconv"

	"github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/codecs"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/errors"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-server/httpserver"
	"github.com/palantir/pkg/bearertoken"
	werror "github.com/palantir/witchcraft-go-error"
	"github.com/palantir/witchcraft-go-server/v2/witchcraft/wresource"
	"github.com/palantir/witchcraft-go-server/v2/wrouter"
)

// Filing and reviewing vouches, and managing guarantor standing. See docs/modules/vouching.md.
type VouchingService interface {
	// File a vouch as the caller (the guarantor). Rejects with Vouching:Forbidden if the caller lacks religionorg.manage on guarantorCongregationUnitId, and with Vouching:GuarantorRevoked if the caller currently holds REVOKED status — both checked live, never cached.
	CreateVouch(ctx context.Context, authHeader bearertoken.Token, requestArg CreateVouchRequest) (Vouch, error)
	// List vouches for a claim. Requires platform-moderator standing.
	ListVouches(ctx context.Context, authHeader bearertoken.Token, claimantArg *string, congregationArg *string, pageSizeArg *int, pageTokenArg *string) (VouchPage, error)
	// Revoke a guarantor. Requires platform-moderator standing. Never invalidates the guarantor's past vouches automatically — instead files one moderation report per affected vouch for moderator review (vouching.md's invariant).
	RevokeGuarantor(ctx context.Context, authHeader bearertoken.Token, personRidArg string, requestArg RevokeGuarantorRequest) (GuarantorStatusRecord, error)
	// Read a guarantor's current status. Requires platform-moderator standing.
	GetGuarantorStatus(ctx context.Context, authHeader bearertoken.Token, personRidArg string) (GuarantorStatusRecord, error)
}

// RegisterRoutesVouchingService registers handlers for the VouchingService endpoints with a witchcraft wrouter.
// This should typically be called in a witchcraft server's InitFunc.
// impl provides an implementation of each endpoint, which can assume the request parameters have been parsed
// in accordance with the Conjure specification.
func RegisterRoutesVouchingService(router wrouter.Router, impl VouchingService, routerParams ...wrouter.RouteParam) error {
	handler := vouchingServiceHandler{impl: impl}
	resource := wresource.New("vouchingservice", router)
	if err := resource.Post("CreateVouch", "/vouching/v1/vouches", httpserver.NewJSONHandler(handler.HandleCreateVouch, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add createVouch route")
	}
	if err := resource.Get("ListVouches", "/vouching/v1/vouches", httpserver.NewJSONHandler(handler.HandleListVouches, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listVouches route")
	}
	if err := resource.Post("RevokeGuarantor", "/vouching/v1/guarantors/{personRid}/revoke", httpserver.NewJSONHandler(handler.HandleRevokeGuarantor, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add revokeGuarantor route")
	}
	if err := resource.Get("GetGuarantorStatus", "/vouching/v1/guarantors/{personRid}/status", httpserver.NewJSONHandler(handler.HandleGetGuarantorStatus, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getGuarantorStatus route")
	}
	return nil
}

type vouchingServiceHandler struct {
	impl VouchingService
}

func (v *vouchingServiceHandler) HandleCreateVouch(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg CreateVouchRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := v.impl.CreateVouch(req.Context(), bearertoken.Token(authHeader), requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (v *vouchingServiceHandler) HandleListVouches(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var claimantArg *string
	if claimantArgStr := req.URL.Query().Get("claimant"); claimantArgStr != "" {
		claimantArgInternal := claimantArgStr
		claimantArg = &claimantArgInternal
	}
	var congregationArg *string
	if congregationArgStr := req.URL.Query().Get("congregation"); congregationArgStr != "" {
		congregationArgInternal := congregationArgStr
		congregationArg = &congregationArgInternal
	}
	var pageSizeArg *int
	if pageSizeArgStr := req.URL.Query().Get("pageSize"); pageSizeArgStr != "" {
		pageSizeArgInternal, err := strconv.Atoi(pageSizeArgStr)
		if err != nil {
			return werror.WrapWithContextParams(req.Context(), errors.WrapWithInvalidArgument(err), "failed to parse \"pageSize\" as integer")
		}
		pageSizeArg = &pageSizeArgInternal
	}
	var pageTokenArg *string
	if pageTokenArgStr := req.URL.Query().Get("pageToken"); pageTokenArgStr != "" {
		pageTokenArgInternal := pageTokenArgStr
		pageTokenArg = &pageTokenArgInternal
	}
	respArg, err := v.impl.ListVouches(req.Context(), bearertoken.Token(authHeader), claimantArg, congregationArg, pageSizeArg, pageTokenArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (v *vouchingServiceHandler) HandleRevokeGuarantor(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	personRidArg, ok := pathParams["personRid"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"personRid\" not present")
	}
	var requestArg RevokeGuarantorRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := v.impl.RevokeGuarantor(req.Context(), bearertoken.Token(authHeader), personRidArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (v *vouchingServiceHandler) HandleGetGuarantorStatus(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	personRidArg, ok := pathParams["personRid"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"personRid\" not present")
	}
	respArg, err := v.impl.GetGuarantorStatus(req.Context(), bearertoken.Token(authHeader), personRidArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}
