// Code generated by conjure-go. DO NOT EDIT.

package vouching

import (
	"context"
	"fmt"
	"net/url"

	"github.com/olehmushka/open-faith-map/internal/conjure/internal/conjureerrors"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-client/httpclient"
	"github.com/palantir/pkg/bearertoken"
	werror "github.com/palantir/witchcraft-go-error"
)

// Filing and reviewing vouches, and managing guarantor standing. See docs/modules/vouching.md.
type VouchingServiceClient interface {
	// File a vouch as the caller (the guarantor). Rejects with Vouching:Forbidden if the caller lacks religionorg.manage on guarantorCongregationUnitId, and with Vouching:GuarantorRevoked if the caller currently holds REVOKED status — both checked live, never cached.
	CreateVouch(ctx context.Context, authHeader bearertoken.Token, requestArg CreateVouchRequest) (Vouch, error)
	// List vouches for a claim. Requires platform-moderator standing.
	ListVouches(ctx context.Context, authHeader bearertoken.Token, claimantArg *string, congregationArg *string, pageSizeArg *int, pageTokenArg *string) (VouchPage, error)
	// Revoke a guarantor. Requires platform-moderator standing. Never invalidates the guarantor's past vouches automatically — instead files one moderation report per affected vouch for moderator review (vouching.md's invariant).
	RevokeGuarantor(ctx context.Context, authHeader bearertoken.Token, personRidArg string, requestArg RevokeGuarantorRequest) (GuarantorStatusRecord, error)
	// Read a guarantor's current status. Requires platform-moderator standing.
	GetGuarantorStatus(ctx context.Context, authHeader bearertoken.Token, personRidArg string) (GuarantorStatusRecord, error)
}

type vouchingServiceClient struct {
	client httpclient.Client
}

func NewVouchingServiceClient(client httpclient.Client) VouchingServiceClient {
	return &vouchingServiceClient{client: client}
}

func (c *vouchingServiceClient) CreateVouch(ctx context.Context, authHeader bearertoken.Token, requestArg CreateVouchRequest) (Vouch, error) {
	var returnVal *Vouch
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("CreateVouch"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/vouching/v1/vouches"))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(Vouch), werror.WrapWithContextParams(ctx, err, "createVouch failed")
	}
	if returnVal == nil {
		return *new(Vouch), werror.ErrorWithContextParams(ctx, "createVouch response cannot be nil")
	}
	return *returnVal, nil
}

func (c *vouchingServiceClient) ListVouches(ctx context.Context, authHeader bearertoken.Token, claimantArg *string, congregationArg *string, pageSizeArg *int, pageTokenArg *string) (VouchPage, error) {
	var returnVal *VouchPage
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("ListVouches"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/vouching/v1/vouches"))
	queryParams := make(url.Values)
	if claimantArg != nil {
		queryParams.Set("claimant", fmt.Sprint(*claimantArg))
	}
	if congregationArg != nil {
		queryParams.Set("congregation", fmt.Sprint(*congregationArg))
	}
	if pageSizeArg != nil {
		queryParams.Set("pageSize", fmt.Sprint(*pageSizeArg))
	}
	if pageTokenArg != nil {
		queryParams.Set("pageToken", fmt.Sprint(*pageTokenArg))
	}
	requestParams = append(requestParams, httpclient.WithQueryValues(queryParams))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(VouchPage), werror.WrapWithContextParams(ctx, err, "listVouches failed")
	}
	if returnVal == nil {
		return *new(VouchPage), werror.ErrorWithContextParams(ctx, "listVouches response cannot be nil")
	}
	return *returnVal, nil
}

func (c *vouchingServiceClient) RevokeGuarantor(ctx context.Context, authHeader bearertoken.Token, personRidArg string, requestArg RevokeGuarantorRequest) (GuarantorStatusRecord, error) {
	var returnVal *GuarantorStatusRecord
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("RevokeGuarantor"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/vouching/v1/guarantors/%s/revoke", url.PathEscape(fmt.Sprint(personRidArg))))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(GuarantorStatusRecord), werror.WrapWithContextParams(ctx, err, "revokeGuarantor failed")
	}
	if returnVal == nil {
		return *new(GuarantorStatusRecord), werror.ErrorWithContextParams(ctx, "revokeGuarantor response cannot be nil")
	}
	return *returnVal, nil
}

func (c *vouchingServiceClient) GetGuarantorStatus(ctx context.Context, authHeader bearertoken.Token, personRidArg string) (GuarantorStatusRecord, error) {
	var returnVal *GuarantorStatusRecord
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("GetGuarantorStatus"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/vouching/v1/guarantors/%s/status", url.PathEscape(fmt.Sprint(personRidArg))))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(GuarantorStatusRecord), werror.WrapWithContextParams(ctx, err, "getGuarantorStatus failed")
	}
	if returnVal == nil {
		return *new(GuarantorStatusRecord), werror.ErrorWithContextParams(ctx, "getGuarantorStatus response cannot be nil")
	}
	return *returnVal, nil
}

// Filing and reviewing vouches, and managing guarantor standing. See docs/modules/vouching.md.
type VouchingServiceClientWithAuth interface {
	// File a vouch as the caller (the guarantor). Rejects with Vouching:Forbidden if the caller lacks religionorg.manage on guarantorCongregationUnitId, and with Vouching:GuarantorRevoked if the caller currently holds REVOKED status — both checked live, never cached.
	CreateVouch(ctx context.Context, requestArg CreateVouchRequest) (Vouch, error)
	// List vouches for a claim. Requires platform-moderator standing.
	ListVouches(ctx context.Context, claimantArg *string, congregationArg *string, pageSizeArg *int, pageTokenArg *string) (VouchPage, error)
	// Revoke a guarantor. Requires platform-moderator standing. Never invalidates the guarantor's past vouches automatically — instead files one moderation report per affected vouch for moderator review (vouching.md's invariant).
	RevokeGuarantor(ctx context.Context, personRidArg string, requestArg RevokeGuarantorRequest) (GuarantorStatusRecord, error)
	// Read a guarantor's current status. Requires platform-moderator standing.
	GetGuarantorStatus(ctx context.Context, personRidArg string) (GuarantorStatusRecord, error)
}

func NewVouchingServiceClientWithAuth(client VouchingServiceClient, authHeader bearertoken.Token) VouchingServiceClientWithAuth {
	return &vouchingServiceClientWithAuth{client: client, authHeader: authHeader}
}

type vouchingServiceClientWithAuth struct {
	client     VouchingServiceClient
	authHeader bearertoken.Token
}

func (c *vouchingServiceClientWithAuth) CreateVouch(ctx context.Context, requestArg CreateVouchRequest) (Vouch, error) {
	return c.client.CreateVouch(ctx, c.authHeader, requestArg)
}

func (c *vouchingServiceClientWithAuth) ListVouches(ctx context.Context, claimantArg *string, congregationArg *string, pageSizeArg *int, pageTokenArg *string) (VouchPage, error) {
	return c.client.ListVouches(ctx, c.authHeader, claimantArg, congregationArg, pageSizeArg, pageTokenArg)
}

func (c *vouchingServiceClientWithAuth) RevokeGuarantor(ctx context.Context, personRidArg string, requestArg RevokeGuarantorRequest) (GuarantorStatusRecord, error) {
	return c.client.RevokeGuarantor(ctx, c.authHeader, personRidArg, requestArg)
}

func (c *vouchingServiceClientWithAuth) GetGuarantorStatus(ctx context.Context, personRidArg string) (GuarantorStatusRecord, error) {
	return c.client.GetGuarantorStatus(ctx, c.authHeader, personRidArg)
}

func NewVouchingServiceClientWithTokenProvider(client VouchingServiceClient, tokenProvider httpclient.TokenProvider) VouchingServiceClientWithAuth {
	return &vouchingServiceClientWithTokenProvider{client: client, tokenProvider: tokenProvider}
}

type vouchingServiceClientWithTokenProvider struct {
	client        VouchingServiceClient
	tokenProvider httpclient.TokenProvider
}

func (c *vouchingServiceClientWithTokenProvider) CreateVouch(ctx context.Context, requestArg CreateVouchRequest) (Vouch, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(Vouch), err
	}
	return c.client.CreateVouch(ctx, bearertoken.Token(token), requestArg)
}

func (c *vouchingServiceClientWithTokenProvider) ListVouches(ctx context.Context, claimantArg *string, congregationArg *string, pageSizeArg *int, pageTokenArg *string) (VouchPage, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(VouchPage), err
	}
	return c.client.ListVouches(ctx, bearertoken.Token(token), claimantArg, congregationArg, pageSizeArg, pageTokenArg)
}

func (c *vouchingServiceClientWithTokenProvider) RevokeGuarantor(ctx context.Context, personRidArg string, requestArg RevokeGuarantorRequest) (GuarantorStatusRecord, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(GuarantorStatusRecord), err
	}
	return c.client.RevokeGuarantor(ctx, bearertoken.Token(token), personRidArg, requestArg)
}

func (c *vouchingServiceClientWithTokenProvider) GetGuarantorStatus(ctx context.Context, personRidArg string) (GuarantorStatusRecord, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(GuarantorStatusRecord), err
	}
	return c.client.GetGuarantorStatus(ctx, bearertoken.Token(token), personRidArg)
}
