// Code generated by conjure-go. DO NOT EDIT.

package vouching

import (
	"github.com/palantir/pkg/datetime"
	"github.com/palantir/pkg/safejson"
	"github.com/palantir/pkg/safeyaml"
)

type CreateVouchRequest struct {
	ClaimantPersonId   string `json:"claimantPersonId"`
	CongregationUnitId string `json:"congregationUnitId"`
	// The unit the CALLER (guarantor) proves their own religionorg.manage standing on — deliberately independent of congregationUnitId, the claim being vouched for. See this file's header comment.
	GuarantorCongregationUnitId string  `json:"guarantorCongregationUnitId"`
	Statement                   *string `json:"statement,omitempty"`
}

func (o CreateVouchRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *CreateVouchRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type GuarantorStatusRecord struct {
	GuarantorPersonId string             `json:"guarantorPersonId"`
	Status            GuarantorStatus    `json:"status"`
	RevokedAt         *datetime.DateTime `json:"revokedAt,omitempty"`
	RevokedReason     *string            `json:"revokedReason,omitempty"`
	RevokedByPersonId *string            `json:"revokedByPersonId,omitempty"`
	// Unset when this record was synthesized (no underlying row exists yet).
	UpdatedAt *datetime.DateTime `json:"updatedAt,omitempty"`
}

func (o GuarantorStatusRecord) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *GuarantorStatusRecord) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type RevokeGuarantorRequest struct {
	Reason string `json:"reason"`
}

func (o RevokeGuarantorRequest) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *RevokeGuarantorRequest) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type Vouch struct {
	// OpenFaithMap-local uuid (openfaithmap.vouching_edges.id).
	Id string `json:"id"`
	// The identity_persons RID of the admin who vouched.
	GuarantorPersonId string `json:"guarantorPersonId"`
	// The identity_persons RID of the person being vouched for.
	ClaimantPersonId string `json:"claimantPersonId"`
	// The directory_units RID of the congregation the claim is about.
	CongregationUnitId string            `json:"congregationUnitId"`
	Statement          *string           `json:"statement,omitempty"`
	CreatedAt          datetime.DateTime `json:"createdAt"`
}

func (o Vouch) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *Vouch) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}

type VouchPage struct {
	Vouches       []Vouch `json:"vouches"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

func (o VouchPage) MarshalJSON() ([]byte, error) {
	if o.Vouches == nil {
		o.Vouches = make([]Vouch, 0)
	}
	type _tmpVouchPage VouchPage
	return safejson.Marshal(_tmpVouchPage(o))
}

func (o *VouchPage) UnmarshalJSON(data []byte) error {
	type _tmpVouchPage VouchPage
	var rawVouchPage _tmpVouchPage
	if err := safejson.Unmarshal(data, &rawVouchPage); err != nil {
		return err
	}
	if rawVouchPage.Vouches == nil {
		rawVouchPage.Vouches = make([]Vouch, 0)
	}
	*o = VouchPage(rawVouchPage)
	return nil
}

func (o VouchPage) MarshalYAML() (interface{}, error) {
	jsonBytes, err := safejson.Marshal(o)
	if err != nil {
		return nil, err
	}
	return safeyaml.JSONtoYAMLMapSlice(jsonBytes)
}

func (o *VouchPage) UnmarshalYAML(unmarshal func(interface{}) error) error {
	jsonBytes, err := safeyaml.UnmarshalerToJSONBytes(unmarshal)
	if err != nil {
		return err
	}
	return safejson.Unmarshal(jsonBytes, *&o)
}
