// Copyright 2026 Oleh Mushka
// SPDX-License-Identifier: Apache-2.0

package domain

import (
	"errors"
	"time"
)

var (
	ErrPersonNotFound        = errors.New("person not found")
	ErrAccountNotFound       = errors.New("account not found")
	ErrAccountDisabled       = errors.New("account is disabled")
	ErrAccountAlreadyExists  = errors.New("an active account already exists for this email")
	ErrIdentityNotFound      = errors.New("external identity not found")
	ErrIdentityConflict      = errors.New("external identity already linked to a different person")
	ErrInvalidExternalID     = errors.New("external identity requires both issuer and subject")
	ErrSessionNotFound       = errors.New("session not found")
	ErrSessionRevoked        = errors.New("session is revoked")
	ErrInviteNotFound        = errors.New("invite not found")
	ErrInviteExpired         = errors.New("invite has expired")
	ErrInviteAlreadyAccepted = errors.New("invite has already been accepted")
)

// Account status values — must match identity_accounts' CHECK constraint literals
// (migrations/0008_core_identity.sql).
const (
	AccountStatusActive   = "active"
	AccountStatusDisabled = "disabled"
)

// Invite status values — must match identity_invites' CHECK constraint literals
// (migrations/0018_core_invites.sql). No "expired"/"revoked" value: see that migration's own
// comment for why both are checked live instead of stored.
const (
	InviteStatusPending  = "pending"
	InviteStatusAccepted = "accepted"
)

// Person is identity_persons — the durable PDP subject. Trimmed relative to go-oikumenea's own
// person module (D-CorePortScope): no birthdate/sex/country-of-birth, none of it used anywhere in
// this repo.
type Person struct {
	ID          string
	Code        string // optional stable external id, unique among active
	DisplayName string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	// LastActiveAt is M11.4's activity signal: the most recent identity_sessions.last_seen_at across
	// all of this person's account's sessions, revoked or not (same "revoked or not" read convention
	// GetSession already uses). Nil if the person has no account or that account has no sessions.
	// Only SearchPersons populates this today — GetPerson/GetPersons (non-admin CoreService reads)
	// leave it nil, so it stays absent for every caller besides the super-admin people list.
	LastActiveAt *time.Time
}

// Account is identity_accounts — an optional login attachment to exactly one person. Tokens/
// passwords are never stored; auth is delegated to Google (D-DirectTokenVerification).
type Account struct {
	ID        string
	PersonID  string
	Email     string // citext; unique among active when set
	Status    string // AccountStatusActive | AccountStatusDisabled
	CreatedAt time.Time
	UpdatedAt time.Time
}

// ExternalIdentity is identity_external_identities — a verified (issuer, subject) login point
// federating to one account. Immutable once created; an unlink is a hard delete.
type ExternalIdentity struct {
	ID        string
	AccountID string
	Issuer    string
	Subject   string
	CreatedAt time.Time
}

func (e ExternalIdentity) Validate() error {
	if e.Issuer == "" || e.Subject == "" {
		return ErrInvalidExternalID
	}
	return nil
}

// Resolution is what a successful identity lookup or JIT link yields: enough to build an
// authz.Subject without the caller needing the full Person/Account rows.
type Resolution struct {
	PersonID  string
	AccountID string
	Email     string
}

// Session is identity_sessions (M11.3, D-SessionTracking) — one row per NextAuth sign-in on the
// admin app. Mutable, unlike ExternalIdentity: LastSeenAt is bumped on the request path (throttled,
// see adapters.sessionTouchThrottle) and RevokedAt is set by RevokeSession.
type Session struct {
	ID          string
	AccountID   string
	Issuer      string
	DeviceLabel string // best-effort User-Agent captured at sign-in; may be empty
	CreatedAt   time.Time
	LastSeenAt  time.Time
	RevokedAt   *time.Time
}

// Invite is identity_invites (M11.6, D-InviteLinkMVP) — a shareable one-time link for a
// pre-provisioned Person+Account pair, generated by an admin and consumed by M10.2's existing JIT
// link-on-match logic on the invitee's first Google sign-in. TokenHash is the only form of the
// token ever persisted (see migrations/0018_core_invites.sql); the raw token is returned once, by
// CreateInvite, and never stored.
type Invite struct {
	ID         string
	PersonID   string
	AccountID  string
	Email      string
	Status     string // InviteStatusPending | InviteStatusAccepted
	InvitedBy  string
	ExpiresAt  time.Time
	CreatedAt  time.Time
	AcceptedAt *time.Time
}
