// Code generated by conjure-go. DO NOT EDIT.

package registration

import (
	"context"
	"net/http"
	"strconv"

	"github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/codecs"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-contract/errors"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-server/httpserver"
	"github.com/palantir/pkg/bearertoken"
	werror "github.com/palantir/witchcraft-go-error"
	"github.com/palantir/witchcraft-go-server/v2/witchcraft/wresource"
	"github.com/palantir/witchcraft-go-server/v2/wrouter"
)

// Congregation-registration requests: submit (any authenticated person), list/approve/reject (a registration operator — verified live against go-oikumenea's PDP, not a locally-cached role). See docs/modules/registration.md.
type RegistrationService interface {
	// Submit a new registration request as the caller. Runs the D-Exclusions taxon check (walking the taxon's ancestors via go-oikumenea's religion.read) before persisting — returns Registration:TaxonExcluded if the tradition (or an ancestor) is on the named exclusion list, Registration:TaxonNotFound if taxonId doesn't resolve.
	SubmitRequest(ctx context.Context, authHeader bearertoken.Token, requestArg SubmitRegistrationRequest) (RegistrationRequest, error)
	// List registration requests. Operator-only for now (verified live: does the caller hold religionorg.manage on the configured root unit?) — see open seams in docs/modules/registration.md for a submitter's-own-requests view.
	ListRequests(ctx context.Context, authHeader bearertoken.Token, statusArg *string, pageSizeArg *int, pageTokenArg *string) (RegistrationRequestPage, error)
	// Read one request. The submitter or an operator (verified live) may read it.
	GetRequest(ctx context.Context, authHeader bearertoken.Token, requestIdArg string) (RegistrationRequest, error)
	// Approve a PENDING request: performs the real go-oikumenea writes (createChildOrg under the configured root unit, org classification, a site over a new location, a filled Position, and a unit-scoped role assignment granting the submitter authority over their new congregation) using the caller's own forwarded token — go-oikumenea's PDP decides for real; this returns whatever error go-oikumenea's PDP does if the caller lacks authority.
	ApproveRequest(ctx context.Context, authHeader bearertoken.Token, requestIdArg string, requestArg ApproveRegistrationRequest) (RegistrationRequest, error)
	// Reject a PENDING request with a reason. No go-oikumenea writes.
	RejectRequest(ctx context.Context, authHeader bearertoken.Token, requestIdArg string, requestArg RejectRegistrationRequest) (RegistrationRequest, error)
}

// RegisterRoutesRegistrationService registers handlers for the RegistrationService endpoints with a witchcraft wrouter.
// This should typically be called in a witchcraft server's InitFunc.
// impl provides an implementation of each endpoint, which can assume the request parameters have been parsed
// in accordance with the Conjure specification.
func RegisterRoutesRegistrationService(router wrouter.Router, impl RegistrationService, routerParams ...wrouter.RouteParam) error {
	handler := registrationServiceHandler{impl: impl}
	resource := wresource.New("registrationservice", router)
	if err := resource.Post("SubmitRequest", "/registration/v1/requests", httpserver.NewJSONHandler(handler.HandleSubmitRequest, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add submitRequest route")
	}
	if err := resource.Get("ListRequests", "/registration/v1/requests", httpserver.NewJSONHandler(handler.HandleListRequests, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add listRequests route")
	}
	if err := resource.Get("GetRequest", "/registration/v1/requests/{requestId}", httpserver.NewJSONHandler(handler.HandleGetRequest, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add getRequest route")
	}
	if err := resource.Post("ApproveRequest", "/registration/v1/requests/{requestId}/approve", httpserver.NewJSONHandler(handler.HandleApproveRequest, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add approveRequest route")
	}
	if err := resource.Post("RejectRequest", "/registration/v1/requests/{requestId}/reject", httpserver.NewJSONHandler(handler.HandleRejectRequest, httpserver.StatusCodeMapper, httpserver.ErrHandler), routerParams...); err != nil {
		return werror.WrapWithContextParams(context.TODO(), err, "failed to add rejectRequest route")
	}
	return nil
}

type registrationServiceHandler struct {
	impl RegistrationService
}

func (r *registrationServiceHandler) HandleSubmitRequest(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var requestArg SubmitRegistrationRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.SubmitRequest(req.Context(), bearertoken.Token(authHeader), requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *registrationServiceHandler) HandleListRequests(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	var statusArg *string
	if statusArgStr := req.URL.Query().Get("status"); statusArgStr != "" {
		statusArgInternal := statusArgStr
		statusArg = &statusArgInternal
	}
	var pageSizeArg *int
	if pageSizeArgStr := req.URL.Query().Get("pageSize"); pageSizeArgStr != "" {
		pageSizeArgInternal, err := strconv.Atoi(pageSizeArgStr)
		if err != nil {
			return werror.WrapWithContextParams(req.Context(), errors.WrapWithInvalidArgument(err), "failed to parse \"pageSize\" as integer")
		}
		pageSizeArg = &pageSizeArgInternal
	}
	var pageTokenArg *string
	if pageTokenArgStr := req.URL.Query().Get("pageToken"); pageTokenArgStr != "" {
		pageTokenArgInternal := pageTokenArgStr
		pageTokenArg = &pageTokenArgInternal
	}
	respArg, err := r.impl.ListRequests(req.Context(), bearertoken.Token(authHeader), statusArg, pageSizeArg, pageTokenArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *registrationServiceHandler) HandleGetRequest(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	requestIdArg, ok := pathParams["requestId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"requestId\" not present")
	}
	respArg, err := r.impl.GetRequest(req.Context(), bearertoken.Token(authHeader), requestIdArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *registrationServiceHandler) HandleApproveRequest(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	requestIdArg, ok := pathParams["requestId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"requestId\" not present")
	}
	var requestArg ApproveRegistrationRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.ApproveRequest(req.Context(), bearertoken.Token(authHeader), requestIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}

func (r *registrationServiceHandler) HandleRejectRequest(rw http.ResponseWriter, req *http.Request) error {
	authHeader, err := httpserver.ParseBearerTokenHeader(req)
	if err != nil {
		return errors.WrapWithPermissionDenied(err)
	}
	pathParams := wrouter.PathParams(req)
	if pathParams == nil {
		return werror.WrapWithContextParams(req.Context(), errors.NewInternal(), "path params not found on request: ensure this endpoint is registered with wrouter")
	}
	requestIdArg, ok := pathParams["requestId"]
	if !ok {
		return werror.WrapWithContextParams(req.Context(), errors.NewInvalidArgument(), "path parameter \"requestId\" not present")
	}
	var requestArg RejectRegistrationRequest
	if err := codecs.JSON.Decode(req.Body, &requestArg); err != nil {
		return errors.WrapWithInvalidArgument(err)
	}
	respArg, err := r.impl.RejectRequest(req.Context(), bearertoken.Token(authHeader), requestIdArg, requestArg)
	if err != nil {
		return err
	}
	rw.Header().Add("Content-Type", codecs.JSON.ContentType())
	return codecs.JSON.Encode(rw, respArg)
}
