// Code generated by conjure-go. DO NOT EDIT.

package registration

import (
	"context"
	"fmt"
	"net/url"

	"github.com/olehmushka/open-faith-map/internal/conjure/internal/conjureerrors"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-client/httpclient"
	"github.com/palantir/pkg/bearertoken"
	werror "github.com/palantir/witchcraft-go-error"
)

// Congregation-registration requests: submit (any authenticated person), list/approve/reject (a registration operator — verified live against go-oikumenea's PDP, not a locally-cached role). See docs/modules/registration.md.
type RegistrationServiceClient interface {
	// Submit a new registration request as the caller. Runs the D-Exclusions taxon check (walking the taxon's ancestors via go-oikumenea's religion.read) before persisting — returns Registration:TaxonExcluded if the tradition (or an ancestor) is on the named exclusion list, Registration:TaxonNotFound if taxonId doesn't resolve.
	SubmitRequest(ctx context.Context, authHeader bearertoken.Token, requestArg SubmitRegistrationRequest) (RegistrationRequest, error)
	// List registration requests. Operator-only for now (verified live: does the caller hold religionorg.manage on the configured root unit?) — see open seams in docs/modules/registration.md for a submitter's-own-requests view.
	ListRequests(ctx context.Context, authHeader bearertoken.Token, statusArg *string, pageSizeArg *int, pageTokenArg *string) (RegistrationRequestPage, error)
	// Read one request. The submitter or an operator (verified live) may read it.
	GetRequest(ctx context.Context, authHeader bearertoken.Token, requestIdArg string) (RegistrationRequest, error)
	// Approve a PENDING request: performs the real go-oikumenea writes (createChildOrg under the configured root unit, org classification, a site over a new location, a filled Position, and a unit-scoped role assignment granting the submitter authority over their new congregation) using the caller's own forwarded token — go-oikumenea's PDP decides for real; this returns whatever error go-oikumenea's PDP does if the caller lacks authority.
	ApproveRequest(ctx context.Context, authHeader bearertoken.Token, requestIdArg string, requestArg ApproveRegistrationRequest) (RegistrationRequest, error)
	// Reject a PENDING request with a reason. No go-oikumenea writes.
	RejectRequest(ctx context.Context, authHeader bearertoken.Token, requestIdArg string, requestArg RejectRegistrationRequest) (RegistrationRequest, error)
}

type registrationServiceClient struct {
	client httpclient.Client
}

func NewRegistrationServiceClient(client httpclient.Client) RegistrationServiceClient {
	return &registrationServiceClient{client: client}
}

func (c *registrationServiceClient) SubmitRequest(ctx context.Context, authHeader bearertoken.Token, requestArg SubmitRegistrationRequest) (RegistrationRequest, error) {
	var returnVal *RegistrationRequest
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("SubmitRequest"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/registration/v1/requests"))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(RegistrationRequest), werror.WrapWithContextParams(ctx, err, "submitRequest failed")
	}
	if returnVal == nil {
		return *new(RegistrationRequest), werror.ErrorWithContextParams(ctx, "submitRequest response cannot be nil")
	}
	return *returnVal, nil
}

func (c *registrationServiceClient) ListRequests(ctx context.Context, authHeader bearertoken.Token, statusArg *string, pageSizeArg *int, pageTokenArg *string) (RegistrationRequestPage, error) {
	var returnVal *RegistrationRequestPage
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("ListRequests"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/registration/v1/requests"))
	queryParams := make(url.Values)
	if statusArg != nil {
		queryParams.Set("status", fmt.Sprint(*statusArg))
	}
	if pageSizeArg != nil {
		queryParams.Set("pageSize", fmt.Sprint(*pageSizeArg))
	}
	if pageTokenArg != nil {
		queryParams.Set("pageToken", fmt.Sprint(*pageTokenArg))
	}
	requestParams = append(requestParams, httpclient.WithQueryValues(queryParams))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(RegistrationRequestPage), werror.WrapWithContextParams(ctx, err, "listRequests failed")
	}
	if returnVal == nil {
		return *new(RegistrationRequestPage), werror.ErrorWithContextParams(ctx, "listRequests response cannot be nil")
	}
	return *returnVal, nil
}

func (c *registrationServiceClient) GetRequest(ctx context.Context, authHeader bearertoken.Token, requestIdArg string) (RegistrationRequest, error) {
	var returnVal *RegistrationRequest
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("GetRequest"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/registration/v1/requests/%s", url.PathEscape(fmt.Sprint(requestIdArg))))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(RegistrationRequest), werror.WrapWithContextParams(ctx, err, "getRequest failed")
	}
	if returnVal == nil {
		return *new(RegistrationRequest), werror.ErrorWithContextParams(ctx, "getRequest response cannot be nil")
	}
	return *returnVal, nil
}

func (c *registrationServiceClient) ApproveRequest(ctx context.Context, authHeader bearertoken.Token, requestIdArg string, requestArg ApproveRegistrationRequest) (RegistrationRequest, error) {
	var returnVal *RegistrationRequest
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("ApproveRequest"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/registration/v1/requests/%s/approve", url.PathEscape(fmt.Sprint(requestIdArg))))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(RegistrationRequest), werror.WrapWithContextParams(ctx, err, "approveRequest failed")
	}
	if returnVal == nil {
		return *new(RegistrationRequest), werror.ErrorWithContextParams(ctx, "approveRequest response cannot be nil")
	}
	return *returnVal, nil
}

func (c *registrationServiceClient) RejectRequest(ctx context.Context, authHeader bearertoken.Token, requestIdArg string, requestArg RejectRegistrationRequest) (RegistrationRequest, error) {
	var returnVal *RegistrationRequest
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("RejectRequest"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/registration/v1/requests/%s/reject", url.PathEscape(fmt.Sprint(requestIdArg))))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(RegistrationRequest), werror.WrapWithContextParams(ctx, err, "rejectRequest failed")
	}
	if returnVal == nil {
		return *new(RegistrationRequest), werror.ErrorWithContextParams(ctx, "rejectRequest response cannot be nil")
	}
	return *returnVal, nil
}

// Congregation-registration requests: submit (any authenticated person), list/approve/reject (a registration operator — verified live against go-oikumenea's PDP, not a locally-cached role). See docs/modules/registration.md.
type RegistrationServiceClientWithAuth interface {
	// Submit a new registration request as the caller. Runs the D-Exclusions taxon check (walking the taxon's ancestors via go-oikumenea's religion.read) before persisting — returns Registration:TaxonExcluded if the tradition (or an ancestor) is on the named exclusion list, Registration:TaxonNotFound if taxonId doesn't resolve.
	SubmitRequest(ctx context.Context, requestArg SubmitRegistrationRequest) (RegistrationRequest, error)
	// List registration requests. Operator-only for now (verified live: does the caller hold religionorg.manage on the configured root unit?) — see open seams in docs/modules/registration.md for a submitter's-own-requests view.
	ListRequests(ctx context.Context, statusArg *string, pageSizeArg *int, pageTokenArg *string) (RegistrationRequestPage, error)
	// Read one request. The submitter or an operator (verified live) may read it.
	GetRequest(ctx context.Context, requestIdArg string) (RegistrationRequest, error)
	// Approve a PENDING request: performs the real go-oikumenea writes (createChildOrg under the configured root unit, org classification, a site over a new location, a filled Position, and a unit-scoped role assignment granting the submitter authority over their new congregation) using the caller's own forwarded token — go-oikumenea's PDP decides for real; this returns whatever error go-oikumenea's PDP does if the caller lacks authority.
	ApproveRequest(ctx context.Context, requestIdArg string, requestArg ApproveRegistrationRequest) (RegistrationRequest, error)
	// Reject a PENDING request with a reason. No go-oikumenea writes.
	RejectRequest(ctx context.Context, requestIdArg string, requestArg RejectRegistrationRequest) (RegistrationRequest, error)
}

func NewRegistrationServiceClientWithAuth(client RegistrationServiceClient, authHeader bearertoken.Token) RegistrationServiceClientWithAuth {
	return &registrationServiceClientWithAuth{client: client, authHeader: authHeader}
}

type registrationServiceClientWithAuth struct {
	client     RegistrationServiceClient
	authHeader bearertoken.Token
}

func (c *registrationServiceClientWithAuth) SubmitRequest(ctx context.Context, requestArg SubmitRegistrationRequest) (RegistrationRequest, error) {
	return c.client.SubmitRequest(ctx, c.authHeader, requestArg)
}

func (c *registrationServiceClientWithAuth) ListRequests(ctx context.Context, statusArg *string, pageSizeArg *int, pageTokenArg *string) (RegistrationRequestPage, error) {
	return c.client.ListRequests(ctx, c.authHeader, statusArg, pageSizeArg, pageTokenArg)
}

func (c *registrationServiceClientWithAuth) GetRequest(ctx context.Context, requestIdArg string) (RegistrationRequest, error) {
	return c.client.GetRequest(ctx, c.authHeader, requestIdArg)
}

func (c *registrationServiceClientWithAuth) ApproveRequest(ctx context.Context, requestIdArg string, requestArg ApproveRegistrationRequest) (RegistrationRequest, error) {
	return c.client.ApproveRequest(ctx, c.authHeader, requestIdArg, requestArg)
}

func (c *registrationServiceClientWithAuth) RejectRequest(ctx context.Context, requestIdArg string, requestArg RejectRegistrationRequest) (RegistrationRequest, error) {
	return c.client.RejectRequest(ctx, c.authHeader, requestIdArg, requestArg)
}

func NewRegistrationServiceClientWithTokenProvider(client RegistrationServiceClient, tokenProvider httpclient.TokenProvider) RegistrationServiceClientWithAuth {
	return &registrationServiceClientWithTokenProvider{client: client, tokenProvider: tokenProvider}
}

type registrationServiceClientWithTokenProvider struct {
	client        RegistrationServiceClient
	tokenProvider httpclient.TokenProvider
}

func (c *registrationServiceClientWithTokenProvider) SubmitRequest(ctx context.Context, requestArg SubmitRegistrationRequest) (RegistrationRequest, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(RegistrationRequest), err
	}
	return c.client.SubmitRequest(ctx, bearertoken.Token(token), requestArg)
}

func (c *registrationServiceClientWithTokenProvider) ListRequests(ctx context.Context, statusArg *string, pageSizeArg *int, pageTokenArg *string) (RegistrationRequestPage, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(RegistrationRequestPage), err
	}
	return c.client.ListRequests(ctx, bearertoken.Token(token), statusArg, pageSizeArg, pageTokenArg)
}

func (c *registrationServiceClientWithTokenProvider) GetRequest(ctx context.Context, requestIdArg string) (RegistrationRequest, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(RegistrationRequest), err
	}
	return c.client.GetRequest(ctx, bearertoken.Token(token), requestIdArg)
}

func (c *registrationServiceClientWithTokenProvider) ApproveRequest(ctx context.Context, requestIdArg string, requestArg ApproveRegistrationRequest) (RegistrationRequest, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(RegistrationRequest), err
	}
	return c.client.ApproveRequest(ctx, bearertoken.Token(token), requestIdArg, requestArg)
}

func (c *registrationServiceClientWithTokenProvider) RejectRequest(ctx context.Context, requestIdArg string, requestArg RejectRegistrationRequest) (RegistrationRequest, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(RegistrationRequest), err
	}
	return c.client.RejectRequest(ctx, bearertoken.Token(token), requestIdArg, requestArg)
}
