// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration.sql

package registrationsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveRegistrationRequest = `-- name: ApproveRegistrationRequest :one
UPDATE openfaithmap.registration_requests
SET status = 'APPROVED', decided_by_person_id = $1, decided_at = $2,
	created_unit_id = $3
WHERE id = $4 AND status IN ('PENDING', 'PROVISIONING')
RETURNING id, submitted_by_person_id, taxon_id, congregation_name, country_id, admin_area1, locality,
	street, house_number, postal_code, latitude, longitude, status, rejection_reason,
	decided_by_person_id, decided_at, created_unit_id, jurisdiction_unit_id, created_at, updated_at
`

type ApproveRegistrationRequestParams struct {
	DecidedByPersonID pgtype.Text
	DecidedAt         pgtype.Timestamptz
	CreatedUnitID     pgtype.Text
	ID                string
}

func (q *Queries) ApproveRegistrationRequest(ctx context.Context, arg ApproveRegistrationRequestParams) (OpenfaithmapRegistrationRequest, error) {
	row := q.db.QueryRow(ctx, approveRegistrationRequest,
		arg.DecidedByPersonID,
		arg.DecidedAt,
		arg.CreatedUnitID,
		arg.ID,
	)
	var i OpenfaithmapRegistrationRequest
	err := row.Scan(
		&i.ID,
		&i.SubmittedByPersonID,
		&i.TaxonID,
		&i.CongregationName,
		&i.CountryID,
		&i.AdminArea1,
		&i.Locality,
		&i.Street,
		&i.HouseNumber,
		&i.PostalCode,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.RejectionReason,
		&i.DecidedByPersonID,
		&i.DecidedAt,
		&i.CreatedUnitID,
		&i.JurisdictionUnitID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegistrationRequest = `-- name: GetRegistrationRequest :one
SELECT id, submitted_by_person_id, taxon_id, congregation_name, country_id, admin_area1, locality,
	street, house_number, postal_code, latitude, longitude, status, rejection_reason,
	decided_by_person_id, decided_at, created_unit_id, jurisdiction_unit_id, created_at, updated_at
FROM openfaithmap.registration_requests WHERE id = $1
`

func (q *Queries) GetRegistrationRequest(ctx context.Context, id string) (OpenfaithmapRegistrationRequest, error) {
	row := q.db.QueryRow(ctx, getRegistrationRequest, id)
	var i OpenfaithmapRegistrationRequest
	err := row.Scan(
		&i.ID,
		&i.SubmittedByPersonID,
		&i.TaxonID,
		&i.CongregationName,
		&i.CountryID,
		&i.AdminArea1,
		&i.Locality,
		&i.Street,
		&i.HouseNumber,
		&i.PostalCode,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.RejectionReason,
		&i.DecidedByPersonID,
		&i.DecidedAt,
		&i.CreatedUnitID,
		&i.JurisdictionUnitID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRegistrationRequest = `-- name: InsertRegistrationRequest :one
INSERT INTO openfaithmap.registration_requests
	(submitted_by_person_id, taxon_id, congregation_name, country_id, admin_area1, locality,
	 street, house_number, postal_code, latitude, longitude)
VALUES ($1, $2, $3, $4,
	$5, $6, $7, $8, $9,
	$10, $11)
RETURNING id, submitted_by_person_id, taxon_id, congregation_name, country_id, admin_area1, locality,
	street, house_number, postal_code, latitude, longitude, status, rejection_reason,
	decided_by_person_id, decided_at, created_unit_id, jurisdiction_unit_id, created_at, updated_at
`

type InsertRegistrationRequestParams struct {
	SubmittedByPersonID string
	TaxonID             string
	CongregationName    string
	CountryID           string
	AdminArea1          pgtype.Text
	Locality            pgtype.Text
	Street              pgtype.Text
	HouseNumber         pgtype.Text
	PostalCode          pgtype.Text
	Latitude            float64
	Longitude           float64
}

func (q *Queries) InsertRegistrationRequest(ctx context.Context, arg InsertRegistrationRequestParams) (OpenfaithmapRegistrationRequest, error) {
	row := q.db.QueryRow(ctx, insertRegistrationRequest,
		arg.SubmittedByPersonID,
		arg.TaxonID,
		arg.CongregationName,
		arg.CountryID,
		arg.AdminArea1,
		arg.Locality,
		arg.Street,
		arg.HouseNumber,
		arg.PostalCode,
		arg.Latitude,
		arg.Longitude,
	)
	var i OpenfaithmapRegistrationRequest
	err := row.Scan(
		&i.ID,
		&i.SubmittedByPersonID,
		&i.TaxonID,
		&i.CongregationName,
		&i.CountryID,
		&i.AdminArea1,
		&i.Locality,
		&i.Street,
		&i.HouseNumber,
		&i.PostalCode,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.RejectionReason,
		&i.DecidedByPersonID,
		&i.DecidedAt,
		&i.CreatedUnitID,
		&i.JurisdictionUnitID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRegistrationRequests = `-- name: ListRegistrationRequests :many
SELECT id, submitted_by_person_id, taxon_id, congregation_name, country_id, admin_area1, locality,
	street, house_number, postal_code, latitude, longitude, status, rejection_reason,
	decided_by_person_id, decided_at, created_unit_id, jurisdiction_unit_id, created_at, updated_at
FROM openfaithmap.registration_requests
WHERE ($1::text IS NULL OR status = $1::text)
ORDER BY created_at DESC LIMIT $2
`

type ListRegistrationRequestsParams struct {
	Status   pgtype.Text
	PageSize int32
}

func (q *Queries) ListRegistrationRequests(ctx context.Context, arg ListRegistrationRequestsParams) ([]OpenfaithmapRegistrationRequest, error) {
	rows, err := q.db.Query(ctx, listRegistrationRequests, arg.Status, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpenfaithmapRegistrationRequest
	for rows.Next() {
		var i OpenfaithmapRegistrationRequest
		if err := rows.Scan(
			&i.ID,
			&i.SubmittedByPersonID,
			&i.TaxonID,
			&i.CongregationName,
			&i.CountryID,
			&i.AdminArea1,
			&i.Locality,
			&i.Street,
			&i.HouseNumber,
			&i.PostalCode,
			&i.Latitude,
			&i.Longitude,
			&i.Status,
			&i.RejectionReason,
			&i.DecidedByPersonID,
			&i.DecidedAt,
			&i.CreatedUnitID,
			&i.JurisdictionUnitID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistrationRequestsBySubmitter = `-- name: ListRegistrationRequestsBySubmitter :many
SELECT id, submitted_by_person_id, taxon_id, congregation_name, country_id, admin_area1, locality,
	street, house_number, postal_code, latitude, longitude, status, rejection_reason,
	decided_by_person_id, decided_at, created_unit_id, jurisdiction_unit_id, created_at, updated_at
FROM openfaithmap.registration_requests
WHERE submitted_by_person_id = $1
ORDER BY created_at DESC LIMIT $2
`

type ListRegistrationRequestsBySubmitterParams struct {
	SubmittedByPersonID string
	PageSize            int32
}

func (q *Queries) ListRegistrationRequestsBySubmitter(ctx context.Context, arg ListRegistrationRequestsBySubmitterParams) ([]OpenfaithmapRegistrationRequest, error) {
	rows, err := q.db.Query(ctx, listRegistrationRequestsBySubmitter, arg.SubmittedByPersonID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OpenfaithmapRegistrationRequest
	for rows.Next() {
		var i OpenfaithmapRegistrationRequest
		if err := rows.Scan(
			&i.ID,
			&i.SubmittedByPersonID,
			&i.TaxonID,
			&i.CongregationName,
			&i.CountryID,
			&i.AdminArea1,
			&i.Locality,
			&i.Street,
			&i.HouseNumber,
			&i.PostalCode,
			&i.Latitude,
			&i.Longitude,
			&i.Status,
			&i.RejectionReason,
			&i.DecidedByPersonID,
			&i.DecidedAt,
			&i.CreatedUnitID,
			&i.JurisdictionUnitID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRegistrationRequestProvisioning = `-- name: MarkRegistrationRequestProvisioning :one
UPDATE openfaithmap.registration_requests
SET status = 'PROVISIONING', decided_by_person_id = $1,
	created_unit_id = $2, jurisdiction_unit_id = $3
WHERE id = $4 AND status = 'PENDING'
RETURNING id, submitted_by_person_id, taxon_id, congregation_name, country_id, admin_area1, locality,
	street, house_number, postal_code, latitude, longitude, status, rejection_reason,
	decided_by_person_id, decided_at, created_unit_id, jurisdiction_unit_id, created_at, updated_at
`

type MarkRegistrationRequestProvisioningParams struct {
	DecidedByPersonID  pgtype.Text
	CreatedUnitID      pgtype.Text
	JurisdictionUnitID pgtype.Text
	ID                 string
}

func (q *Queries) MarkRegistrationRequestProvisioning(ctx context.Context, arg MarkRegistrationRequestProvisioningParams) (OpenfaithmapRegistrationRequest, error) {
	row := q.db.QueryRow(ctx, markRegistrationRequestProvisioning,
		arg.DecidedByPersonID,
		arg.CreatedUnitID,
		arg.JurisdictionUnitID,
		arg.ID,
	)
	var i OpenfaithmapRegistrationRequest
	err := row.Scan(
		&i.ID,
		&i.SubmittedByPersonID,
		&i.TaxonID,
		&i.CongregationName,
		&i.CountryID,
		&i.AdminArea1,
		&i.Locality,
		&i.Street,
		&i.HouseNumber,
		&i.PostalCode,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.RejectionReason,
		&i.DecidedByPersonID,
		&i.DecidedAt,
		&i.CreatedUnitID,
		&i.JurisdictionUnitID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rejectRegistrationRequest = `-- name: RejectRegistrationRequest :one
UPDATE openfaithmap.registration_requests
SET status = 'REJECTED', decided_by_person_id = $1, decided_at = $2,
	rejection_reason = $3
WHERE id = $4 AND status = 'PENDING'
RETURNING id, submitted_by_person_id, taxon_id, congregation_name, country_id, admin_area1, locality,
	street, house_number, postal_code, latitude, longitude, status, rejection_reason,
	decided_by_person_id, decided_at, created_unit_id, jurisdiction_unit_id, created_at, updated_at
`

type RejectRegistrationRequestParams struct {
	DecidedByPersonID pgtype.Text
	DecidedAt         pgtype.Timestamptz
	RejectionReason   pgtype.Text
	ID                string
}

func (q *Queries) RejectRegistrationRequest(ctx context.Context, arg RejectRegistrationRequestParams) (OpenfaithmapRegistrationRequest, error) {
	row := q.db.QueryRow(ctx, rejectRegistrationRequest,
		arg.DecidedByPersonID,
		arg.DecidedAt,
		arg.RejectionReason,
		arg.ID,
	)
	var i OpenfaithmapRegistrationRequest
	err := row.Scan(
		&i.ID,
		&i.SubmittedByPersonID,
		&i.TaxonID,
		&i.CongregationName,
		&i.CountryID,
		&i.AdminArea1,
		&i.Locality,
		&i.Street,
		&i.HouseNumber,
		&i.PostalCode,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.RejectionReason,
		&i.DecidedByPersonID,
		&i.DecidedAt,
		&i.CreatedUnitID,
		&i.JurisdictionUnitID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
