// Code generated by conjure-go. DO NOT EDIT.

package moderation

import (
	"strings"
)

type ActionKind struct {
	val ActionKind_Value
}

type ActionKind_Value string

const (
	ActionKind_HIDE         ActionKind_Value = "HIDE"
	ActionKind_SUSPEND      ActionKind_Value = "SUSPEND"
	ActionKind_ARCHIVE      ActionKind_Value = "ARCHIVE"
	ActionKind_WARN_ADMIN   ActionKind_Value = "WARN_ADMIN"
	ActionKind_REVOKE_VOUCH ActionKind_Value = "REVOKE_VOUCH"
	ActionKind_REVERSE      ActionKind_Value = "REVERSE"
	ActionKind_UNKNOWN      ActionKind_Value = "UNKNOWN"
)

// ActionKind_Values returns all known variants of ActionKind.
func ActionKind_Values() []ActionKind_Value {
	return []ActionKind_Value{ActionKind_HIDE, ActionKind_SUSPEND, ActionKind_ARCHIVE, ActionKind_WARN_ADMIN, ActionKind_REVOKE_VOUCH, ActionKind_REVERSE}
}

func New_ActionKind(value ActionKind_Value) ActionKind {
	return ActionKind{val: value}
}

// IsUnknown returns false for all known variants of ActionKind and true otherwise.
func (e ActionKind) IsUnknown() bool {
	switch e.val {
	case ActionKind_HIDE, ActionKind_SUSPEND, ActionKind_ARCHIVE, ActionKind_WARN_ADMIN, ActionKind_REVOKE_VOUCH, ActionKind_REVERSE:
		return false
	}
	return true
}

func (e ActionKind) Value() ActionKind_Value {
	if e.IsUnknown() {
		return ActionKind_UNKNOWN
	}
	return e.val
}

func (e ActionKind) String() string {
	return string(e.val)
}

func (e ActionKind) MarshalText() ([]byte, error) {
	return []byte(e.val), nil
}

func (e *ActionKind) UnmarshalText(data []byte) error {
	switch v := strings.ToUpper(string(data)); v {
	default:
		*e = New_ActionKind(ActionKind_Value(v))
	case "HIDE":
		*e = New_ActionKind(ActionKind_HIDE)
	case "SUSPEND":
		*e = New_ActionKind(ActionKind_SUSPEND)
	case "ARCHIVE":
		*e = New_ActionKind(ActionKind_ARCHIVE)
	case "WARN_ADMIN":
		*e = New_ActionKind(ActionKind_WARN_ADMIN)
	case "REVOKE_VOUCH":
		*e = New_ActionKind(ActionKind_REVOKE_VOUCH)
	case "REVERSE":
		*e = New_ActionKind(ActionKind_REVERSE)
	}
	return nil
}

type AppealDecision struct {
	val AppealDecision_Value
}

type AppealDecision_Value string

const (
	AppealDecision_UPHELD     AppealDecision_Value = "UPHELD"
	AppealDecision_OVERTURNED AppealDecision_Value = "OVERTURNED"
	AppealDecision_UNKNOWN    AppealDecision_Value = "UNKNOWN"
)

// AppealDecision_Values returns all known variants of AppealDecision.
func AppealDecision_Values() []AppealDecision_Value {
	return []AppealDecision_Value{AppealDecision_UPHELD, AppealDecision_OVERTURNED}
}

func New_AppealDecision(value AppealDecision_Value) AppealDecision {
	return AppealDecision{val: value}
}

// IsUnknown returns false for all known variants of AppealDecision and true otherwise.
func (e AppealDecision) IsUnknown() bool {
	switch e.val {
	case AppealDecision_UPHELD, AppealDecision_OVERTURNED:
		return false
	}
	return true
}

func (e AppealDecision) Value() AppealDecision_Value {
	if e.IsUnknown() {
		return AppealDecision_UNKNOWN
	}
	return e.val
}

func (e AppealDecision) String() string {
	return string(e.val)
}

func (e AppealDecision) MarshalText() ([]byte, error) {
	return []byte(e.val), nil
}

func (e *AppealDecision) UnmarshalText(data []byte) error {
	switch v := strings.ToUpper(string(data)); v {
	default:
		*e = New_AppealDecision(AppealDecision_Value(v))
	case "UPHELD":
		*e = New_AppealDecision(AppealDecision_UPHELD)
	case "OVERTURNED":
		*e = New_AppealDecision(AppealDecision_OVERTURNED)
	}
	return nil
}

type AppealStatus struct {
	val AppealStatus_Value
}

type AppealStatus_Value string

const (
	AppealStatus_OPEN       AppealStatus_Value = "OPEN"
	AppealStatus_UPHELD     AppealStatus_Value = "UPHELD"
	AppealStatus_OVERTURNED AppealStatus_Value = "OVERTURNED"
	AppealStatus_UNKNOWN    AppealStatus_Value = "UNKNOWN"
)

// AppealStatus_Values returns all known variants of AppealStatus.
func AppealStatus_Values() []AppealStatus_Value {
	return []AppealStatus_Value{AppealStatus_OPEN, AppealStatus_UPHELD, AppealStatus_OVERTURNED}
}

func New_AppealStatus(value AppealStatus_Value) AppealStatus {
	return AppealStatus{val: value}
}

// IsUnknown returns false for all known variants of AppealStatus and true otherwise.
func (e AppealStatus) IsUnknown() bool {
	switch e.val {
	case AppealStatus_OPEN, AppealStatus_UPHELD, AppealStatus_OVERTURNED:
		return false
	}
	return true
}

func (e AppealStatus) Value() AppealStatus_Value {
	if e.IsUnknown() {
		return AppealStatus_UNKNOWN
	}
	return e.val
}

func (e AppealStatus) String() string {
	return string(e.val)
}

func (e AppealStatus) MarshalText() ([]byte, error) {
	return []byte(e.val), nil
}

func (e *AppealStatus) UnmarshalText(data []byte) error {
	switch v := strings.ToUpper(string(data)); v {
	default:
		*e = New_AppealStatus(AppealStatus_Value(v))
	case "OPEN":
		*e = New_AppealStatus(AppealStatus_OPEN)
	case "UPHELD":
		*e = New_AppealStatus(AppealStatus_UPHELD)
	case "OVERTURNED":
		*e = New_AppealStatus(AppealStatus_OVERTURNED)
	}
	return nil
}

type QueueScope struct {
	val QueueScope_Value
}

type QueueScope_Value string

const (
	QueueScope_PLATFORM     QueueScope_Value = "PLATFORM"
	QueueScope_CONGREGATION QueueScope_Value = "CONGREGATION"
	QueueScope_JURISDICTION QueueScope_Value = "JURISDICTION"
	QueueScope_UNKNOWN      QueueScope_Value = "UNKNOWN"
)

// QueueScope_Values returns all known variants of QueueScope.
func QueueScope_Values() []QueueScope_Value {
	return []QueueScope_Value{QueueScope_PLATFORM, QueueScope_CONGREGATION, QueueScope_JURISDICTION}
}

func New_QueueScope(value QueueScope_Value) QueueScope {
	return QueueScope{val: value}
}

// IsUnknown returns false for all known variants of QueueScope and true otherwise.
func (e QueueScope) IsUnknown() bool {
	switch e.val {
	case QueueScope_PLATFORM, QueueScope_CONGREGATION, QueueScope_JURISDICTION:
		return false
	}
	return true
}

func (e QueueScope) Value() QueueScope_Value {
	if e.IsUnknown() {
		return QueueScope_UNKNOWN
	}
	return e.val
}

func (e QueueScope) String() string {
	return string(e.val)
}

func (e QueueScope) MarshalText() ([]byte, error) {
	return []byte(e.val), nil
}

func (e *QueueScope) UnmarshalText(data []byte) error {
	switch v := strings.ToUpper(string(data)); v {
	default:
		*e = New_QueueScope(QueueScope_Value(v))
	case "PLATFORM":
		*e = New_QueueScope(QueueScope_PLATFORM)
	case "CONGREGATION":
		*e = New_QueueScope(QueueScope_CONGREGATION)
	case "JURISDICTION":
		*e = New_QueueScope(QueueScope_JURISDICTION)
	}
	return nil
}

// Catalog-typed report reason. OTHER accepts free text via Report.detail. Deliberately has no DOCTRINAL_CONCERN value (docs/modules/moderation.md's invariant: doctrinal disputes are not adjudicated — they are filed under OTHER and moderators decline to act on doctrinal grounds alone).
type ReasonCode struct {
	val ReasonCode_Value
}

type ReasonCode_Value string

const (
	ReasonCode_SPAM                  ReasonCode_Value = "SPAM"
	ReasonCode_INCORRECT_INFORMATION ReasonCode_Value = "INCORRECT_INFORMATION"
	ReasonCode_INAPPROPRIATE_CONTENT ReasonCode_Value = "INAPPROPRIATE_CONTENT"
	ReasonCode_DUPLICATE             ReasonCode_Value = "DUPLICATE"
	ReasonCode_OTHER                 ReasonCode_Value = "OTHER"
	ReasonCode_UNKNOWN               ReasonCode_Value = "UNKNOWN"
)

// ReasonCode_Values returns all known variants of ReasonCode.
func ReasonCode_Values() []ReasonCode_Value {
	return []ReasonCode_Value{ReasonCode_SPAM, ReasonCode_INCORRECT_INFORMATION, ReasonCode_INAPPROPRIATE_CONTENT, ReasonCode_DUPLICATE, ReasonCode_OTHER}
}

func New_ReasonCode(value ReasonCode_Value) ReasonCode {
	return ReasonCode{val: value}
}

// IsUnknown returns false for all known variants of ReasonCode and true otherwise.
func (e ReasonCode) IsUnknown() bool {
	switch e.val {
	case ReasonCode_SPAM, ReasonCode_INCORRECT_INFORMATION, ReasonCode_INAPPROPRIATE_CONTENT, ReasonCode_DUPLICATE, ReasonCode_OTHER:
		return false
	}
	return true
}

func (e ReasonCode) Value() ReasonCode_Value {
	if e.IsUnknown() {
		return ReasonCode_UNKNOWN
	}
	return e.val
}

func (e ReasonCode) String() string {
	return string(e.val)
}

func (e ReasonCode) MarshalText() ([]byte, error) {
	return []byte(e.val), nil
}

func (e *ReasonCode) UnmarshalText(data []byte) error {
	switch v := strings.ToUpper(string(data)); v {
	default:
		*e = New_ReasonCode(ReasonCode_Value(v))
	case "SPAM":
		*e = New_ReasonCode(ReasonCode_SPAM)
	case "INCORRECT_INFORMATION":
		*e = New_ReasonCode(ReasonCode_INCORRECT_INFORMATION)
	case "INAPPROPRIATE_CONTENT":
		*e = New_ReasonCode(ReasonCode_INAPPROPRIATE_CONTENT)
	case "DUPLICATE":
		*e = New_ReasonCode(ReasonCode_DUPLICATE)
	case "OTHER":
		*e = New_ReasonCode(ReasonCode_OTHER)
	}
	return nil
}

type ReportStatus struct {
	val ReportStatus_Value
}

type ReportStatus_Value string

const (
	ReportStatus_OPEN      ReportStatus_Value = "OPEN"
	ReportStatus_ACTIONED  ReportStatus_Value = "ACTIONED"
	ReportStatus_DISMISSED ReportStatus_Value = "DISMISSED"
	ReportStatus_UNKNOWN   ReportStatus_Value = "UNKNOWN"
)

// ReportStatus_Values returns all known variants of ReportStatus.
func ReportStatus_Values() []ReportStatus_Value {
	return []ReportStatus_Value{ReportStatus_OPEN, ReportStatus_ACTIONED, ReportStatus_DISMISSED}
}

func New_ReportStatus(value ReportStatus_Value) ReportStatus {
	return ReportStatus{val: value}
}

// IsUnknown returns false for all known variants of ReportStatus and true otherwise.
func (e ReportStatus) IsUnknown() bool {
	switch e.val {
	case ReportStatus_OPEN, ReportStatus_ACTIONED, ReportStatus_DISMISSED:
		return false
	}
	return true
}

func (e ReportStatus) Value() ReportStatus_Value {
	if e.IsUnknown() {
		return ReportStatus_UNKNOWN
	}
	return e.val
}

func (e ReportStatus) String() string {
	return string(e.val)
}

func (e ReportStatus) MarshalText() ([]byte, error) {
	return []byte(e.val), nil
}

func (e *ReportStatus) UnmarshalText(data []byte) error {
	switch v := strings.ToUpper(string(data)); v {
	default:
		*e = New_ReportStatus(ReportStatus_Value(v))
	case "OPEN":
		*e = New_ReportStatus(ReportStatus_OPEN)
	case "ACTIONED":
		*e = New_ReportStatus(ReportStatus_ACTIONED)
	case "DISMISSED":
		*e = New_ReportStatus(ReportStatus_DISMISSED)
	}
	return nil
}

// What a report or action targets.
type TargetKind struct {
	val TargetKind_Value
}

type TargetKind_Value string

const (
	TargetKind_SITE          TargetKind_Value = "SITE"
	TargetKind_DOCUMENT      TargetKind_Value = "DOCUMENT"
	TargetKind_CONGREGATION  TargetKind_Value = "CONGREGATION"
	TargetKind_VOUCHING_EDGE TargetKind_Value = "VOUCHING_EDGE"
	TargetKind_UNKNOWN       TargetKind_Value = "UNKNOWN"
)

// TargetKind_Values returns all known variants of TargetKind.
func TargetKind_Values() []TargetKind_Value {
	return []TargetKind_Value{TargetKind_SITE, TargetKind_DOCUMENT, TargetKind_CONGREGATION, TargetKind_VOUCHING_EDGE}
}

func New_TargetKind(value TargetKind_Value) TargetKind {
	return TargetKind{val: value}
}

// IsUnknown returns false for all known variants of TargetKind and true otherwise.
func (e TargetKind) IsUnknown() bool {
	switch e.val {
	case TargetKind_SITE, TargetKind_DOCUMENT, TargetKind_CONGREGATION, TargetKind_VOUCHING_EDGE:
		return false
	}
	return true
}

func (e TargetKind) Value() TargetKind_Value {
	if e.IsUnknown() {
		return TargetKind_UNKNOWN
	}
	return e.val
}

func (e TargetKind) String() string {
	return string(e.val)
}

func (e TargetKind) MarshalText() ([]byte, error) {
	return []byte(e.val), nil
}

func (e *TargetKind) UnmarshalText(data []byte) error {
	switch v := strings.ToUpper(string(data)); v {
	default:
		*e = New_TargetKind(TargetKind_Value(v))
	case "SITE":
		*e = New_TargetKind(TargetKind_SITE)
	case "DOCUMENT":
		*e = New_TargetKind(TargetKind_DOCUMENT)
	case "CONGREGATION":
		*e = New_TargetKind(TargetKind_CONGREGATION)
	case "VOUCHING_EDGE":
		*e = New_TargetKind(TargetKind_VOUCHING_EDGE)
	}
	return nil
}
