// Code generated by conjure-go. DO NOT EDIT.

package moderation

import (
	"context"
	"fmt"
	"net/url"

	"github.com/olehmushka/open-faith-map/internal/conjure/internal/conjureerrors"
	"github.com/palantir/conjure-go-runtime/v2/conjure-go-client/httpclient"
	"github.com/palantir/pkg/bearertoken"
	werror "github.com/palantir/witchcraft-go-error"
)

// Anonymous public surface (openfaithmap-web holds no session — D-AdminSurface): file a report against any target, and run the D-Exclusions taxon check ahead of registration as a standalone dry-run. See docs/modules/moderation.md.
type ModerationPublicServiceClient interface {
	// File a report. reporterPersonId is unset — this endpoint never asks for identity.
	FileReport(ctx context.Context, requestArg FileReportRequest) (Report, error)
	// Dry-run the D-Exclusions taxon check via the server's own service-principal token — the caller here is anonymous and has no token of its own to forward. Re-run at registration time itself (internal/registration), never cached from a prior visit here.
	CheckExclusion(ctx context.Context, requestArg ExclusionCheckRequest) (ExclusionCheckResult, error)
}

type moderationPublicServiceClient struct {
	client httpclient.Client
}

func NewModerationPublicServiceClient(client httpclient.Client) ModerationPublicServiceClient {
	return &moderationPublicServiceClient{client: client}
}

func (c *moderationPublicServiceClient) FileReport(ctx context.Context, requestArg FileReportRequest) (Report, error) {
	var returnVal *Report
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("FileReport"))
	requestParams = append(requestParams, httpclient.WithPathf("/moderation/v1/reports"))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(Report), werror.WrapWithContextParams(ctx, err, "fileReport failed")
	}
	if returnVal == nil {
		return *new(Report), werror.ErrorWithContextParams(ctx, "fileReport response cannot be nil")
	}
	return *returnVal, nil
}

func (c *moderationPublicServiceClient) CheckExclusion(ctx context.Context, requestArg ExclusionCheckRequest) (ExclusionCheckResult, error) {
	var returnVal *ExclusionCheckResult
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("CheckExclusion"))
	requestParams = append(requestParams, httpclient.WithPathf("/moderation/v1/exclusion-check"))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(ExclusionCheckResult), werror.WrapWithContextParams(ctx, err, "checkExclusion failed")
	}
	if returnVal == nil {
		return *new(ExclusionCheckResult), werror.ErrorWithContextParams(ctx, "checkExclusion response cannot be nil")
	}
	return *returnVal, nil
}

// Moderator queue, actions, and appeals. moderation.read/moderation.act (docs/modules/moderation.md) both resolve to one live PDP check: does the caller hold platform-moderator's grant on the shared root unit (D-PlatformModerator)? No OpenFaithMap-owned moderator roster — verified live against internal/authz's PDP, same discipline registration/content/discovery already follow.
type ModerationServiceClient interface {
	// List reports in the given queue scope (default PLATFORM). Requires platform-moderator standing.
	ListReports(ctx context.Context, authHeader bearertoken.Token, scopeArg *QueueScope, statusArg *ReportStatus, pageSizeArg *int, pageTokenArg *string) (ReportPage, error)
	// Take an action against a report's target. The moderation_actions row is written before any local effect is applied (D-Moderation's Correction replacement invariant). Marks the report ACTIONED.
	TakeActionOnReport(ctx context.Context, authHeader bearertoken.Token, reportIdArg string, requestArg TakeActionOnReportRequest) (ModerationAction, error)
	// Take a proactive action with no prior report (e.g. enforcing D-Exclusions directly).
	TakeAction(ctx context.Context, authHeader bearertoken.Token, requestArg TakeActionRequest) (ModerationAction, error)
	// Reverse a prior action within its grace window. Writes a new, append-only REVERSE row and sets reversedByActionId on the original — the original row is never edited or deleted.
	ReverseAction(ctx context.Context, authHeader bearertoken.Token, actionIdArg string, requestArg ReverseActionRequest) (ModerationAction, error)
	// File an appeal against an action, as the affected congregation admin (verified live via an internal/authz.Require check on the target unit, not a platform-moderator check).
	FileAppeal(ctx context.Context, authHeader bearertoken.Token, actionIdArg string, requestArg FileAppealRequest) (Appeal, error)
	// List appeals. Requires platform-moderator standing.
	ListAppeals(ctx context.Context, authHeader bearertoken.Token, statusArg *AppealStatus, pageSizeArg *int, pageTokenArg *string) (AppealPage, error)
	// Decide an appeal. Rejects with Moderation:AppealActorConflict if the caller is the original action's actor — enforced at write time, never left to moderator discipline.
	DecideAppeal(ctx context.Context, authHeader bearertoken.Token, appealIdArg string, requestArg DecideAppealRequest) (Appeal, error)
}

type moderationServiceClient struct {
	client httpclient.Client
}

func NewModerationServiceClient(client httpclient.Client) ModerationServiceClient {
	return &moderationServiceClient{client: client}
}

func (c *moderationServiceClient) ListReports(ctx context.Context, authHeader bearertoken.Token, scopeArg *QueueScope, statusArg *ReportStatus, pageSizeArg *int, pageTokenArg *string) (ReportPage, error) {
	var returnVal *ReportPage
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("ListReports"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/moderation/v1/reports"))
	queryParams := make(url.Values)
	if scopeArg != nil {
		queryParams.Set("scope", fmt.Sprint(*scopeArg))
	}
	if statusArg != nil {
		queryParams.Set("status", fmt.Sprint(*statusArg))
	}
	if pageSizeArg != nil {
		queryParams.Set("pageSize", fmt.Sprint(*pageSizeArg))
	}
	if pageTokenArg != nil {
		queryParams.Set("pageToken", fmt.Sprint(*pageTokenArg))
	}
	requestParams = append(requestParams, httpclient.WithQueryValues(queryParams))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(ReportPage), werror.WrapWithContextParams(ctx, err, "listReports failed")
	}
	if returnVal == nil {
		return *new(ReportPage), werror.ErrorWithContextParams(ctx, "listReports response cannot be nil")
	}
	return *returnVal, nil
}

func (c *moderationServiceClient) TakeActionOnReport(ctx context.Context, authHeader bearertoken.Token, reportIdArg string, requestArg TakeActionOnReportRequest) (ModerationAction, error) {
	var returnVal *ModerationAction
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("TakeActionOnReport"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/moderation/v1/reports/%s/actions", url.PathEscape(fmt.Sprint(reportIdArg))))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(ModerationAction), werror.WrapWithContextParams(ctx, err, "takeActionOnReport failed")
	}
	if returnVal == nil {
		return *new(ModerationAction), werror.ErrorWithContextParams(ctx, "takeActionOnReport response cannot be nil")
	}
	return *returnVal, nil
}

func (c *moderationServiceClient) TakeAction(ctx context.Context, authHeader bearertoken.Token, requestArg TakeActionRequest) (ModerationAction, error) {
	var returnVal *ModerationAction
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("TakeAction"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/moderation/v1/actions"))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(ModerationAction), werror.WrapWithContextParams(ctx, err, "takeAction failed")
	}
	if returnVal == nil {
		return *new(ModerationAction), werror.ErrorWithContextParams(ctx, "takeAction response cannot be nil")
	}
	return *returnVal, nil
}

func (c *moderationServiceClient) ReverseAction(ctx context.Context, authHeader bearertoken.Token, actionIdArg string, requestArg ReverseActionRequest) (ModerationAction, error) {
	var returnVal *ModerationAction
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("ReverseAction"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/moderation/v1/actions/%s/reverse", url.PathEscape(fmt.Sprint(actionIdArg))))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(ModerationAction), werror.WrapWithContextParams(ctx, err, "reverseAction failed")
	}
	if returnVal == nil {
		return *new(ModerationAction), werror.ErrorWithContextParams(ctx, "reverseAction response cannot be nil")
	}
	return *returnVal, nil
}

func (c *moderationServiceClient) FileAppeal(ctx context.Context, authHeader bearertoken.Token, actionIdArg string, requestArg FileAppealRequest) (Appeal, error) {
	var returnVal *Appeal
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("FileAppeal"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/moderation/v1/actions/%s/appeals", url.PathEscape(fmt.Sprint(actionIdArg))))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(Appeal), werror.WrapWithContextParams(ctx, err, "fileAppeal failed")
	}
	if returnVal == nil {
		return *new(Appeal), werror.ErrorWithContextParams(ctx, "fileAppeal response cannot be nil")
	}
	return *returnVal, nil
}

func (c *moderationServiceClient) ListAppeals(ctx context.Context, authHeader bearertoken.Token, statusArg *AppealStatus, pageSizeArg *int, pageTokenArg *string) (AppealPage, error) {
	var returnVal *AppealPage
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("ListAppeals"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/moderation/v1/appeals"))
	queryParams := make(url.Values)
	if statusArg != nil {
		queryParams.Set("status", fmt.Sprint(*statusArg))
	}
	if pageSizeArg != nil {
		queryParams.Set("pageSize", fmt.Sprint(*pageSizeArg))
	}
	if pageTokenArg != nil {
		queryParams.Set("pageToken", fmt.Sprint(*pageTokenArg))
	}
	requestParams = append(requestParams, httpclient.WithQueryValues(queryParams))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Get(ctx, requestParams...); err != nil {
		return *new(AppealPage), werror.WrapWithContextParams(ctx, err, "listAppeals failed")
	}
	if returnVal == nil {
		return *new(AppealPage), werror.ErrorWithContextParams(ctx, "listAppeals response cannot be nil")
	}
	return *returnVal, nil
}

func (c *moderationServiceClient) DecideAppeal(ctx context.Context, authHeader bearertoken.Token, appealIdArg string, requestArg DecideAppealRequest) (Appeal, error) {
	var returnVal *Appeal
	var requestParams []httpclient.RequestParam
	requestParams = append(requestParams, httpclient.WithRPCMethodName("DecideAppeal"))
	requestParams = append(requestParams, httpclient.WithHeader("Authorization", fmt.Sprint("Bearer ", authHeader)))
	requestParams = append(requestParams, httpclient.WithPathf("/moderation/v1/appeals/%s/decide", url.PathEscape(fmt.Sprint(appealIdArg))))
	requestParams = append(requestParams, httpclient.WithJSONRequest(requestArg))
	requestParams = append(requestParams, httpclient.WithJSONResponse(&returnVal))
	requestParams = append(requestParams, httpclient.WithRequestConjureErrorDecoder(conjureerrors.Decoder()))
	if _, err := c.client.Post(ctx, requestParams...); err != nil {
		return *new(Appeal), werror.WrapWithContextParams(ctx, err, "decideAppeal failed")
	}
	if returnVal == nil {
		return *new(Appeal), werror.ErrorWithContextParams(ctx, "decideAppeal response cannot be nil")
	}
	return *returnVal, nil
}

// Moderator queue, actions, and appeals. moderation.read/moderation.act (docs/modules/moderation.md) both resolve to one live PDP check: does the caller hold platform-moderator's grant on the shared root unit (D-PlatformModerator)? No OpenFaithMap-owned moderator roster — verified live against internal/authz's PDP, same discipline registration/content/discovery already follow.
type ModerationServiceClientWithAuth interface {
	// List reports in the given queue scope (default PLATFORM). Requires platform-moderator standing.
	ListReports(ctx context.Context, scopeArg *QueueScope, statusArg *ReportStatus, pageSizeArg *int, pageTokenArg *string) (ReportPage, error)
	// Take an action against a report's target. The moderation_actions row is written before any local effect is applied (D-Moderation's Correction replacement invariant). Marks the report ACTIONED.
	TakeActionOnReport(ctx context.Context, reportIdArg string, requestArg TakeActionOnReportRequest) (ModerationAction, error)
	// Take a proactive action with no prior report (e.g. enforcing D-Exclusions directly).
	TakeAction(ctx context.Context, requestArg TakeActionRequest) (ModerationAction, error)
	// Reverse a prior action within its grace window. Writes a new, append-only REVERSE row and sets reversedByActionId on the original — the original row is never edited or deleted.
	ReverseAction(ctx context.Context, actionIdArg string, requestArg ReverseActionRequest) (ModerationAction, error)
	// File an appeal against an action, as the affected congregation admin (verified live via an internal/authz.Require check on the target unit, not a platform-moderator check).
	FileAppeal(ctx context.Context, actionIdArg string, requestArg FileAppealRequest) (Appeal, error)
	// List appeals. Requires platform-moderator standing.
	ListAppeals(ctx context.Context, statusArg *AppealStatus, pageSizeArg *int, pageTokenArg *string) (AppealPage, error)
	// Decide an appeal. Rejects with Moderation:AppealActorConflict if the caller is the original action's actor — enforced at write time, never left to moderator discipline.
	DecideAppeal(ctx context.Context, appealIdArg string, requestArg DecideAppealRequest) (Appeal, error)
}

func NewModerationServiceClientWithAuth(client ModerationServiceClient, authHeader bearertoken.Token) ModerationServiceClientWithAuth {
	return &moderationServiceClientWithAuth{client: client, authHeader: authHeader}
}

type moderationServiceClientWithAuth struct {
	client     ModerationServiceClient
	authHeader bearertoken.Token
}

func (c *moderationServiceClientWithAuth) ListReports(ctx context.Context, scopeArg *QueueScope, statusArg *ReportStatus, pageSizeArg *int, pageTokenArg *string) (ReportPage, error) {
	return c.client.ListReports(ctx, c.authHeader, scopeArg, statusArg, pageSizeArg, pageTokenArg)
}

func (c *moderationServiceClientWithAuth) TakeActionOnReport(ctx context.Context, reportIdArg string, requestArg TakeActionOnReportRequest) (ModerationAction, error) {
	return c.client.TakeActionOnReport(ctx, c.authHeader, reportIdArg, requestArg)
}

func (c *moderationServiceClientWithAuth) TakeAction(ctx context.Context, requestArg TakeActionRequest) (ModerationAction, error) {
	return c.client.TakeAction(ctx, c.authHeader, requestArg)
}

func (c *moderationServiceClientWithAuth) ReverseAction(ctx context.Context, actionIdArg string, requestArg ReverseActionRequest) (ModerationAction, error) {
	return c.client.ReverseAction(ctx, c.authHeader, actionIdArg, requestArg)
}

func (c *moderationServiceClientWithAuth) FileAppeal(ctx context.Context, actionIdArg string, requestArg FileAppealRequest) (Appeal, error) {
	return c.client.FileAppeal(ctx, c.authHeader, actionIdArg, requestArg)
}

func (c *moderationServiceClientWithAuth) ListAppeals(ctx context.Context, statusArg *AppealStatus, pageSizeArg *int, pageTokenArg *string) (AppealPage, error) {
	return c.client.ListAppeals(ctx, c.authHeader, statusArg, pageSizeArg, pageTokenArg)
}

func (c *moderationServiceClientWithAuth) DecideAppeal(ctx context.Context, appealIdArg string, requestArg DecideAppealRequest) (Appeal, error) {
	return c.client.DecideAppeal(ctx, c.authHeader, appealIdArg, requestArg)
}

func NewModerationServiceClientWithTokenProvider(client ModerationServiceClient, tokenProvider httpclient.TokenProvider) ModerationServiceClientWithAuth {
	return &moderationServiceClientWithTokenProvider{client: client, tokenProvider: tokenProvider}
}

type moderationServiceClientWithTokenProvider struct {
	client        ModerationServiceClient
	tokenProvider httpclient.TokenProvider
}

func (c *moderationServiceClientWithTokenProvider) ListReports(ctx context.Context, scopeArg *QueueScope, statusArg *ReportStatus, pageSizeArg *int, pageTokenArg *string) (ReportPage, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(ReportPage), err
	}
	return c.client.ListReports(ctx, bearertoken.Token(token), scopeArg, statusArg, pageSizeArg, pageTokenArg)
}

func (c *moderationServiceClientWithTokenProvider) TakeActionOnReport(ctx context.Context, reportIdArg string, requestArg TakeActionOnReportRequest) (ModerationAction, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(ModerationAction), err
	}
	return c.client.TakeActionOnReport(ctx, bearertoken.Token(token), reportIdArg, requestArg)
}

func (c *moderationServiceClientWithTokenProvider) TakeAction(ctx context.Context, requestArg TakeActionRequest) (ModerationAction, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(ModerationAction), err
	}
	return c.client.TakeAction(ctx, bearertoken.Token(token), requestArg)
}

func (c *moderationServiceClientWithTokenProvider) ReverseAction(ctx context.Context, actionIdArg string, requestArg ReverseActionRequest) (ModerationAction, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(ModerationAction), err
	}
	return c.client.ReverseAction(ctx, bearertoken.Token(token), actionIdArg, requestArg)
}

func (c *moderationServiceClientWithTokenProvider) FileAppeal(ctx context.Context, actionIdArg string, requestArg FileAppealRequest) (Appeal, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(Appeal), err
	}
	return c.client.FileAppeal(ctx, bearertoken.Token(token), actionIdArg, requestArg)
}

func (c *moderationServiceClientWithTokenProvider) ListAppeals(ctx context.Context, statusArg *AppealStatus, pageSizeArg *int, pageTokenArg *string) (AppealPage, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(AppealPage), err
	}
	return c.client.ListAppeals(ctx, bearertoken.Token(token), statusArg, pageSizeArg, pageTokenArg)
}

func (c *moderationServiceClientWithTokenProvider) DecideAppeal(ctx context.Context, appealIdArg string, requestArg DecideAppealRequest) (Appeal, error) {
	token, err := c.tokenProvider(ctx)
	if err != nil {
		return *new(Appeal), err
	}
	return c.client.DecideAppeal(ctx, bearertoken.Token(token), appealIdArg, requestArg)
}
